### ISSUE TITLE
Shuffle button doesn't light up?

### ISSUE THREAD

**Issue by AustinBee** [morpheusthewhite/spicetify-themes#105]
Hi guys I just downloaded and installed this theme, I'm using the Samurai skin and I noticed that the shuffle button stays the same cream color whether it's on shuffle or not. ![Screenshot_23](https://user-images.githubusercontent.com/67063203/84915412-c082e280-b08a-11ea-8905-27a2194428dc.png)
It  does light up orange when I hover over it though. The only way to tell is to tell is to wait for it to say 'Shuffle' or 'Don't Shuffle' when hovering over and that would be annoying when playing games haha. If anyone knows how to fix this that would be cool :) Thank you! and also is there anyway to make the scroll bar a different color? It blends in with the background so well. 
![Screenshot_22](https://user-images.githubusercontent.com/67063203/84915524-e4debf00-b08a-11ea-8fe7-f7db91d23df7.png)

**Comment by khanhas** [comment]
@spoutn1k

**Comment by spoutn1k** [comment]
Yeah so both of those issues are due to the limited color options. As the creator of the tool @khanhas is there a way to single those elements out via CSS ?

**Comment by AustinBee** [comment]
Thanks buddy I'll do that. It's really cool so that's a fair compromise for sure haha.

**Comment by spoutn1k** [comment]
Can someone please keep this open ? I'd like to fix the previously mentionned issues and have the issue open until taken care of.
