### ISSUE TITLE
Color Schemes don't show up properly unlike the example

### ISSUE THREAD

**Issue by vexx25** [morpheusthewhite/spicetify-themes#107]
I have just properly installed Dribbblish but whenever I choose a scheme including the base color it doesn't look like the one shown in the example

**My Spotify with a broken color scheme**
![broken](https://user-images.githubusercontent.com/67098824/85003591-01612100-b189-11ea-8321-5bbe41723730.PNG)

**color scheme (dark) that was advertised on the site**
![dark](https://user-images.githubusercontent.com/67098824/85003686-1d64c280-b189-11ea-99f4-ee194df4a01a.png)

**Comment by vexx25** [comment]
@morpheusthewhite could you help with this problem?

**Comment by vexx25** [comment]
@khanhas ??? anyone?

**Comment by heyyzoeyy** [comment]
I also have this problem, it is because spicetify does not have `secondary_bg` as a variable in when inspecting the css of spotify.
Since `main_fg` and `secondary_bg` are the same, I changed line 1273 of `user.css`.

`user.css` before:
`	background-color: var(--modspotify_secondary_bg);`

`user.css` after:
`	background-color: var(--modspotify_main_fg);`

**Comment by marmor157** [comment]
Try updating or reinstalling spicetify-cli.

I had the same problem and it've helped me.

**Comment by vexx25** [comment]
@marmor157 ok, I'll try that and update you

**Comment by vexx25** [comment]
@marmor157 it worked. Thanks for the suggestion!

**Comment by katawajojo** [comment]
the "secondary_bg" variable does work. The reason the colors are the same in colors.ini after my pull request are to preserve the look of the previously included themes before the variable addition. If your theme isn't working, you may have an earlier version of user.css and colors.ini, as the themes works perfectly fine over here with the newer changes. You may just need to update your copy of the theme.
![image](https://user-images.githubusercontent.com/13071927/85213042-09969900-b30e-11ea-991c-11f7a3218699.png)
