### ISSUE TITLE
Might be a brain-dead issue

### ISSUE THREAD

**Issue by SillyQuestionAlt** [morpheusthewhite/spicetify-themes#108]
Hey! Just had a dumb question. Was just wondering how in the pictures for the example themes, the title bar for Spotify seems to be missing. It doesn't seem to disappear for me, how would I go about getting rid of it? I like the clean look without it. Thanks!

**Comment by morpheusthewhite** [comment]
It depends not on the Spotify Application but on your OS (specifically from your DE/WM if you're on Linux)

**Comment by SillyQuestionAlt** [comment]
Well I have GNOME. I have some CSS to normally title bars, but for this specific theme it does not work.
