### ISSUE TITLE
Rounded corner issue

### ISSUE THREAD

**Issue by retesta** [morpheusthewhite/spicetify-themes#110]
More like a nuisance really :/

Hover selection won't fit in the rounded corner (both top and bottom). Theme is Dribbbblish (with custom color.ini), OS is Zorin 15.2 (Ubuntu Based - Gnome) - Don't know if this happens on other OSs

![Screenshot from 2020-06-20 20-09-27](https://user-images.githubusercontent.com/64700989/85213734-d7a72600-b351-11ea-91b9-f1a469b91191.png)

**Comment by khanhas** [comment]
Still look fine on mine:
![image](https://user-images.githubusercontent.com/26436809/85215539-8e8cbb80-b3bd-11ea-980e-7a88d9c528ad.png)

What your spotify version and are you using latest dribbblish copy?

**Comment by retesta** [comment]
My Spotify version is 1.1.10.546.ge08ef575

I noticed I was not using the latest update of Dribbblish, updating it has solved most of the issues. The only thing that still doesn't have rounded corners is the New Playlist option.

![Screenshot from 2020-06-21 21-33-28](https://user-images.githubusercontent.com/64700989/85238922-a8abb580-b420-11ea-9dfe-28e77390cfa9.png)
![Screenshot from 2020-06-21 21-14-06](https://user-images.githubusercontent.com/64700989/85238698-54540600-b41f-11ea-81fb-4c8a6b157984.png)

**Comment by khanhas** [comment]
Thank you for the report. I couldn't find any optimal solution and I don't think it's significant enough to spend more time over. I would close this for now.
