### ISSUE TITLE
shuffle/repeat button color isssue

### ISSUE THREAD

**Issue by retesta** [morpheusthewhite/spicetify-themes#111]
I am using Dribbbbish with a custom 3 colour scheme (greenish, darkish, dark) and I can't see when the shuffle and repeat buttons are active or not (since the colours of main_fg and secondary_fg are the same). How can I change the colour of those icons when they are **disabled**? The quick fix from issue #105 does the opposite of what I need; it changes the colours of those two buttons when they are active. 

Here is a screenshot of my theme: I wish for them to be greenish, like so, when they are active (instead of all the time), and for them to be the darkish colour when they are **inactive**. How I can I accomplish this?

![spotify](https://user-images.githubusercontent.com/64700989/85213950-8d737400-b354-11ea-807e-2cdbbf1a4a99.png)

**Comment by khanhas** [comment]
If you want some personal touch, you have to it yourself:
1. Use devtool to find element name
2. Add CSS rules in user.css
3. Reapply
