### ISSUE TITLE
Dribblish: weird green-on-blue button on Artist page

### ISSUE THREAD

**Issue by ewen-lbh** [morpheusthewhite/spicetify-themes#113]
The "Edit Profile" button on artist pages has a blue button with green text, see image:

![2020-06-22T18-17-50--2](https://user-images.githubusercontent.com/39094199/85310898-e0fcd380-b4b4-11ea-98f7-16c94f16597d.png)

An appropriate CSS selector would be `button[data-ta-id="artist-button-edit-profile"]`

Something more legible would use `main_bg` as the text color and `main_fg` as the text color:

![2020-06-22T18-21-37--D](https://user-images.githubusercontent.com/39094199/85311120-3a650280-b4b5-11ea-83c7-8f72fc36dc58.png)

**Comment by khanhas** [comment]
Unnecessary .

**Comment by ewen-lbh** [comment]
@khanhas it'd literlally take 3 lines of CSS and I can make a PR if you want

this isn't going to make it any worse for anyone, just better for people who are artists on spotify
