### ISSUE TITLE
Colors inverted for all themes

### ISSUE THREAD

**Issue by ZacheryMcLaughlin** [morpheusthewhite/spicetify-themes#114]
Whenever I use any of the themes, the colors are completely inverted from what is shown in the example photos. Top is what I'm getting and the bottom is the expected.
 
![image](https://user-images.githubusercontent.com/44444169/85357784-fbd84380-b4c6-11ea-9630-e8e17d8e569f.png)

![image](https://user-images.githubusercontent.com/44444169/85357800-0692d880-b4c7-11ea-8100-835f187c9ff1.png)

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/issues/217
