### ISSUE TITLE
Volume controls and fullscreen positioning issue with dribblish

### ISSUE THREAD

**Issue by matthaigh27** [morpheusthewhite/spicetify-themes#117]
![image](https://user-images.githubusercontent.com/44395485/86001478-48d19200-ba52-11ea-8a7a-4df52f4698f7.png)
![image](https://user-images.githubusercontent.com/44395485/86001499-4d964600-ba52-11ea-9c4c-0cbd5209b7fb.png)

The first image is on my 1680x1050 screen and the second is on my 1080p screen. Not a huge issue but just thought I'd raise it to you. Theme is dribblish dracula. I am using Arch Linux , awesome wm, on X11, with an nvidia 2080 super if you need this...

**Comment by khanhas** [comment]
Fixed. Please git pull or download theme package again.
