### ISSUE TITLE
Problem with Liked Songs Playlist in Dribblish Dark Theme.

### ISSUE THREAD

**Issue by AbhayAysola** [morpheusthewhite/spicetify-themes#118]

**Comment by AbhayAysola** [comment]
I restarted my laptop and it worked. Sorry for inconvenience.

**Comment by eliasmrcs** [comment]
I have this problem! I can’t seem to find where my liked songs are located, I tried looking everywhere. I'll attach a screenshot marked with where they usually were. Already tried restarting my laptop.
<img width="318" alt="screenshot" src="https://user-images.githubusercontent.com/53603870/88199298-f21c3a00-cc44-11ea-90e5-ed26dc247ed3.png">

**Comment by UrSok** [comment]
You haven't installed it correctly. Look in the readme once again.
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#how-to-install
