### ISSUE TITLE
How to uninstall Dribbblish? 

### ISSUE THREAD

**Issue by AustinBee** [morpheusthewhite/spicetify-themes#120]
Hey guys, I was using Dribbblish for awhile and then I switched to Lovelace. But now my playlist icons are the background for my playlists? 
![Screenshot_28](https://user-images.githubusercontent.com/67063203/86518961-d8d15c00-be03-11ea-90ca-ff6dafcb4ba9.png)

**Comment by morpheusthewhite** [comment]
Try `spicetify restore` and then apply again the theme

**Comment by AustinBee** [comment]
Yeah I'm sorry I forgot to say I tried that and it still looks like that

**Comment by khanhas** [comment]
run:
```
spicetify config extensions dribbblish.js-
```
to remove Dribbblish script

**Comment by AustinBee** [comment]
Yep that worked, thanks so much.

**Comment by morpheusthewhite** [comment]
Maybe this should be specified in the README, too
