### ISSUE TITLE
Device selection broken in Dribblish

### ISSUE THREAD

**Issue by spoutn1k** [morpheusthewhite/spicetify-themes#121]
The new commits broke the device selection window in Dribbblish, when devices are available, clicking on the icon brings up only the shadow of the usual pop-up:
![Screenshot from 2020-07-05 14-48-54](https://user-images.githubusercontent.com/22240065/86542897-ae000a00-bece-11ea-9fd4-f7d609c08ddd.png)

**Comment by khanhas** [comment]
Oh shoot!

**Comment by khanhas** [comment]
Okay, fixed. Thank you!
