### ISSUE TITLE
open C:\Users\Name\.spicetify\AppX:

### ISSUE THREAD

**Issue by Archibold2** [morpheusthewhite/spicetify-themes#122]
I am using powershell and ran the command required to install spicetify. Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

When I ran the backup it came up with this. open C:\Users\Name\.spicetify\AppX:
I played around a bit then found this fatal open C:\Users\name\.spicetify\AppX\zlink\css\user.css: The system cannot find the path specified.
Can I have any help on this please?
![spicetify](https://user-images.githubusercontent.com/67985687/86857679-ebbf8700-c0b6-11ea-90f7-bb402ebeef93.PNG)

**Comment by khanhas** [comment]
Did you ever run `spicetify backup`?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/issues/232
