### ISSUE TITLE
Dribbblish: Round sidebar icons are slightly cut off on the left

### ISSUE THREAD

**Issue by laurinneff** [morpheusthewhite/spicetify-themes#125]
Images:
![grafik](https://user-images.githubusercontent.com/29987831/87200732-75f92c80-c2fd-11ea-9649-7a41a4be17aa.png)
![grafik](https://user-images.githubusercontent.com/29987831/87200743-7b567700-c2fd-11ea-9204-f00443f33902.png)

As shown in the images, some of the sidebar icons are cut off on the left.

**Comment by khanhas** [comment]
Huh, it buggered me too. I always thought it was chrome renderer problem that it rounds pixel position number when rendering circle (it happened in ImageMagick), so I just neglected it.
Actually, it was clipped by a default rule. Now just add:
```css
.SidebarListItem__label {
    overflow: unset;
}
```
I will push an update soon when I can.

**Comment by khanhas** [comment]
Fixed.
