### ISSUE TITLE
OnePunch - bug

### ISSUE THREAD

**Issue by VeronFX** [morpheusthewhite/spicetify-themes#126]
![nTPX8kX - Imgur](https://user-images.githubusercontent.com/64342397/87222618-fddf4500-c396-11ea-9560-9bced9cb0619.gif)

https://i.imgur.com/QgA8sDx.mp4

OnePunch theme

Lag after playing a song
After playing any song background flickers for a split second

**Comment by morpheusthewhite** [comment]
@saitama42069

**Comment by saitama42069** [comment]
Well, this is new. I was working on some changes, but I'm releasing it as there is not much to worry about. After @morpheusthewhite allows it, please check if the lag persists.

**Comment by morpheusthewhite** [comment]
@VeronFX you can actually check it on @saitama42069 fork, if it's ok I'll merge, otherwise wait for it to be fixed

**Comment by saitama42069** [comment]
Yes, that'll be better. I've pushed the commit.

**Comment by VeronFX** [comment]
@saitama42069 I don't know how github works. I copied the code of 0.9 beta version and pasted to the user.css, but lag is still there. I am on OSX Catalina 10.15.4

**Comment by morpheusthewhite** [comment]
@VeronFX make sure to apply again the theme, I think it is needed to update the theme into the application

**Comment by VeronFX** [comment]
@morpheusthewhite Yeah I know. I did it and other changes are applied well, but the lag is still there. :(

The lag is strange. Background flickers occasionally. Play button flickers constantly. My theory is that it's animation lag, because if I try to click fast (play,pause,play,pause....) it won't recognize all clicks.
*new video: https://i.imgur.com/POJzJJ4.mp4

**Comment by saitama42069** [comment]
@VeronFX try to do a clean install of theme. If that doesn't help clean install spotify.  My spicetify theme has nothing to do with animations. Also, I've never experienced this while in catalina. 

Macos 10.15.4. can't be trusted. I myself downgraded to 10.14. Not going to upgrade anytime soon.
