### ISSUE TITLE
(dribblish) fg color of sidebar not working in windows.

### ISSUE THREAD

**Issue by NicTanghe** [morpheusthewhite/spicetify-themes#127]
Foregroundcolor of the side bar is the same as the player color and not as the play button ect.
![image](https://user-images.githubusercontent.com/13624265/87222681-15f29c80-c376-11ea-8d4a-adc5ec2949d3.png)

**Comment by khanhas** [comment]
The key for sidebar buttons color is `preserve_1`, just change it to what you want.
 Please spare customization question like this in Spectrum.

**Comment by NicTanghe** [comment]
im not talking about the buttons im talking about the bar this is incorrectly closed.

**Comment by Amil-Gaoul** [comment]
I have the same problem. Sidebar color doesn't change. I set base color scheme and sidebar color the same player color
![image](https://user-images.githubusercontent.com/16349083/87320242-e64dbb00-c554-11ea-9f5a-9a5e96f2726b.png)

I did't change the color.ini file
```ini
[base]
main_fg                               = 1db954
active_control_fg                     = 1db954
secondary_fg                          = F0F0F0
secondary_bg                          = 1db954
main_bg                               = 000
sidebar_and_player_bg                 = 000
scrollbar_fg_and_selected_row_bg      = 313235
miscellaneous_bg                      = 313235
preserve_1                            = FFF
```
