### ISSUE TITLE
Error When Applying Theme

### ISSUE THREAD

**Issue by Noman-Aziz** [morpheusthewhite/spicetify-themes#129]
Hi, i am trying to apply a theme using this guide
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish 
I followed his steps but then when i hit spicetify apply, an error message comes
spicetify v1.0.2
Copying raw assets:
fatal unlinkat /opt/spotify/Apps/about.spa: permission denied
then i use sudo to run the command but another error comes,
spicetify v1.0.2
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config.ini
How can i fix this error?

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Installation#spotify-installed-from-aur

**Comment by khanhas** [comment]
Just change the permission, dont run anything with SUdo

**Comment by Noman-Aziz** [comment]
Thank You! It Worked.

**Comment by pm0u** [comment]
Original link to a solution seems to be dead, can't seem to find what instructions were contained there.. i tried setting all perms recursively on the App dir but didn't change anything. Any advice here?
