### ISSUE TITLE
Extension "dribbblish.js" not found

### ISSUE THREAD

**Issue by Trek3** [morpheusthewhite/spicetify-themes#130]
I have followed the README instructions and copied "dribbblish.js" in the Extensions folder, but when I do

`spicetify apply`

It says "extension dribbblish.js not found".
Spotify then opens but nothing happens, the window is just empty.

Any suggestions?

Using arch-linux, downloaded spicetify-cli from AUR

**Comment by khanhas** [comment]
Read README again
```
spicetify config extensions dribbblish.js
spicetify apply
```

**Comment by Trek3** [comment]
I did that, that's the whole point of this issue.

**Comment by khanhas** [comment]
Before using Dribbblish, does any other theme work? does the default SpicetifyTheme work?

**Comment by vlackbyeli** [comment]
not for me

**Comment by riskirills66** [comment]
"dribblish.js is already in the list," PowerShell says.
but Spotify says different.
