### ISSUE TITLE
Not all themes from wiki are in the repo

### ISSUE THREAD

**Issue by tstrijdhorst** [morpheusthewhite/spicetify-themes#135]
A number of themes that have screenshots on the wiki are not actually in the repo.

Including but not limited to these:
* White
* Nord-Dark
* Horizon

**Comment by morpheusthewhite** [comment]
They are different color schemes.

> Here you can find a preview of all the themes. Some of them may have different color scheme (in that case you'll find different entries in the same theme, each one named after the color theme).

**Comment by tstrijdhorst** [comment]
Ah my bad. I did read that note but did not identify these as such. Thanks for taking the time to answer :pray:
