### ISSUE TITLE
Cant apply "--transparent-window-controls" to Spotifty shortcut

### ISSUE THREAD

**Issue by FoxKandii** [morpheusthewhite/spicetify-themes#141]
I can't figure out how to add "--transparent-window-controls" to the end of the Target field. I keep getting an error saying
"The name 'C:\Users\[USER]\AppData\Roaming\Spotify\Spotify.exe ----transparent-window-controls' specified in the Target box is not valid. Make sure that the file path and filename are correct."

![explorer_jvisrGQT5f](https://user-images.githubusercontent.com/68959743/88816057-1b723280-d210-11ea-80a7-49654a05fb50.png)

**Comment by khanhas** [comment]
The double quote at the end is unnecessary

**Comment by FoxKandii** [comment]
Without the quotation marks it just gives the error "The name 'C:\Users[USER]' specified in the Target box is not valid. Make sure that the file path and filename are correct."

**Comment by khanhas** [comment]
Just wrap the double quote in spotify.exe path, do not include the flag

**Comment by FoxKandii** [comment]
Thanks, that worked. I could've sworn I tried that already haha. Thanks again for dealing with my incompetence, I really do love the theme :) .
