### ISSUE TITLE
Dribbblish theme 

### ISSUE THREAD

**Issue by EikelFlo** [morpheusthewhite/spicetify-themes#142]
Dear morpheus,
The side colors on the dribblish theme dont work for me.
![image](https://user-images.githubusercontent.com/53355483/88941672-988dbe00-d289-11ea-81bd-70c22d40936b.png)
The dark theme should have a green side color. 
I am using the SpotifyNoControl.exe and have set --os-windows-icon-dodge to 0

**Comment by khanhas** [comment]
Please upgrade spicetify and run 
```
spicetify restore backup apply
```

**Comment by EikelFlo** [comment]
I am using spicetify v0.9.8 which should be the newest version right?

**Comment by khanhas** [comment]
v1.0.2 is the newest
Check the spicetify-cli repo

**Comment by EikelFlo** [comment]
Yeah sorry khanhas my bad, I installed your spicetify with choco and choco only has the 0.9.8 version.
Its working perfectly now thanks (:

**Comment by sheeepdev** [comment]
I have this same issue on 1.1.0 and setting --os-windows-icon-dodge to 0 does not do anything.
