### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by kroist** [morpheusthewhite/spicetify-themes#144]
I have a problem with the Dribbblish theme right bar icons. Only the first one and the second are displayed correctly.

![image](https://user-images.githubusercontent.com/36311724/89065865-24304900-d375-11ea-9a3f-4bb36e1ea147.png)

It seems to happen on all colorschemes. This string was also executed at the installation.
`spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
`
Access to /opt/spotify (paht to my AUR-installed spotify) is 

> drwxrwxrwx.

My spotify default appearance. There are only three icons, which are correctly shown in my dribblish setup (however there are three dots after each of them) 

![image](https://user-images.githubusercontent.com/36311724/89065514-876dab80-d374-11ea-8be3-f49ff9b2daef.png)

I searched for some icons, described in dribbblish.js and it seems that spotify has them all.

![image](https://user-images.githubusercontent.com/36311724/89066004-5c378c00-d375-11ea-8029-c40cdde9fc0e.png)

My version is 1.0.2

**Comment by emmettmccann** [comment]
I had the same problem.
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#how-to-install

Copy the dribblish.js file into the extensions folder of Spicetify then run `spicetify config extensions dribbblish.js`
