### ISSUE TITLE
Dribbblish: no playlist pictures but titles

### ISSUE THREAD

**Issue by Joppepe** [morpheusthewhite/spicetify-themes#148]
Hi, I just installed spicetify and like the Dribbblish theme. How do you get the playlist pictures on the left hand side of the application? I get the name of the playlist and not the picture.
![o2obw2x75ze51](https://user-images.githubusercontent.com/57362274/89316076-e59fd480-d67b-11ea-9c42-e65983e54c65.png)

**Comment by khanhas** [comment]
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#how-to-install

**Comment by Joppepe** [comment]
Thanks for the help! I think I did something wrong during my first attemt. Is it normal that the top 50 charts don't use their picture?
![Aantekening 2020-08-05 190542](https://user-images.githubusercontent.com/57362274/89442204-b1e1af00-d74e-11ea-90ba-57f5e2ff44f5.png)

**Comment by khanhas** [comment]
Thank you!
I just pushed fixes, please pull new update.
