### ISSUE TITLE
-bash: spicetify: command not found

### ISSUE THREAD

**Issue by qfaq** [morpheusthewhite/spicetify-themes#150]
I keep getting this error whenever I type "spicetify" at the begging of a command. I have to instead type `/Users/~/spicetify-cli/spicetify` followed by whatever command. How do I fix this?

**Comment by morpheusthewhite** [comment]
You installed `spicetify` to a directory which is not contained in the PATH. The simplest solution is to link it in some other directory which instead is in the path, for example

```
cd /usr/bin && sudo ln -s ~/spicetify-cli/spicetify spicetify
```

**Comment by qfaq** [comment]
I get `ln: spicetify: Operation not permitted` when doing the command. I did it a second time and I got no message. I went to check my home directory and `spicetify_data`, `spicetify_data`, `spicetify` we're still there. Should I move them manually to my `/usr/bin` folder?

**Comment by qfaq** [comment]
Got it working, I uninstalled then installed using Homebrew.
