### ISSUE TITLE
-bash: cd: /Users/joe/spicetify_data/Themes/Dribbblish: No such file or directory (MacOS 10.15.5)

### ISSUE THREAD

**Issue by qfaq** [morpheusthewhite/spicetify-themes#151]
I ran the command on the readme but I kept getting no such file directory. It's trying to locate a file that doesn't exist. The themes folder does, but there is no Dribbblish anywhere.

**Comment by morpheusthewhite** [comment]
Use the spectrum chat for these problems, which are related to YOUR installation, not to the content of the repository. This is clearly related to misplaced directories (I don't know how to help you, I don't have MacOS).

Do not use GitHub issues for asking for support.

**Comment by qfaq** [comment]
Sorry, I feel like a complete asshole now. I will leave.
