### ISSUE TITLE
Some tooltip in the left side menu aren't shown.

### ISSUE THREAD

**Issue by SalahAdDin** [morpheusthewhite/spicetify-themes#152]
Hi, I just met these amazing themes today and I'm testing them like a child with a new toy.

I just realized the next bug:
![Screen Capture_select-area_20200808175914](https://user-images.githubusercontent.com/5034215/89713627-9a4e3480-d9a1-11ea-9d74-0ddc49502572.gif)

As you can see, some tooltips aren't shown at hovering their respective button.

What's the problem?
Thanks.

**Comment by khanhas** [comment]
Fixed. Thank you!

**Comment by SalahAdDin** [comment]
Cool, but that one for the clock icon... is not working yet.

![Screen Capture_select-area_20200809000351](https://user-images.githubusercontent.com/5034215/89719714-e9ad5880-d9d3-11ea-8932-3a0d8e3d76de.gif)

Thanks!

**Comment by khanhas** [comment]
Works normal in mine
![image](https://user-images.githubusercontent.com/26436809/89720632-93620900-da17-11ea-93cb-b66905045807.png)

**Comment by SalahAdDin** [comment]
Did you test it in English?
