### ISSUE TITLE
Gradianto doesn't set the colorscheme in album view.

### ISSUE THREAD

**Issue by angelocarly** [morpheusthewhite/spicetify-themes#16]
I apologize if this is not the correct place to open an issue about this, I tried to open an issue on @auditt98 's fork, but was unable to.

![out](https://user-images.githubusercontent.com/33165985/68845738-29a51080-06cc-11ea-99c9-3532534f7640.png)

When using the Gradianto theme, the colors are not applied in album view as seen in the picture. When hovering, there is no color at all, and when not hovering it is white. I would fix it myself, but have no understanding of the spotify css.

Thanks!

**Comment by auditt98** [comment]
Oh oops!! I forgot to theme the album view, the screenshots were from the Playlist pages. Working on a fix now.
