### ISSUE TITLE
Downloading pop up doesn't fit theme

### ISSUE THREAD

**Issue by Dizeeee** [morpheusthewhite/spicetify-themes#165]
When songs are downloading, text appears in the bottom right corner that doesn't seem to match the rest of the theme. While I'm not familiar with the development process for Spicetify, this could potentially be displayed as a downloading icon or progress wheel below the list of playlists.

OS: Ubuntu 18.04
Spotify: Flatpak
Theme: Dribbblish, dark

With Downloading text:
![image](https://user-images.githubusercontent.com/17105387/92507979-731b9a80-f1cd-11ea-8474-f5fc79a50602.png)

Without:
![image](https://user-images.githubusercontent.com/17105387/92508223-de656c80-f1cd-11ea-9c38-364c1da33d2c.png)

**Comment by JulienMaille** [comment]
@khanhas any idea how to bring this on top? Or maybe moving it to `notification-bubble-container`?

**Comment by JulienMaille** [comment]
I was able to get this, I'm going to push it
![image](https://user-images.githubusercontent.com/182520/107693210-1bb6b480-6cae-11eb-82f7-ccf82760cafb.png)
