### ISSUE TITLE
Dribbblish Mac window controls overlap with UI

### ISSUE THREAD

**Issue by MyYogurt** [morpheusthewhite/spicetify-themes#174]
The Dribbblish side bar on the left slightly overlaps with the Mac window control buttons.
<img width="461" alt="Screen Shot 2020-09-24 at 1 18 24 PM" src="https://user-images.githubusercontent.com/40012201/94178158-baaa5380-fe68-11ea-9461-e53649f456af.png">

**Comment by wl03355609** [comment]
I made some changes in user.css

.LeftSidebar .SidebarListItem,
.RootlistItem {
    padding-top: 30px;
    padding-bottom: 10px;
}

.LeftSidebar__section .SidebarListItem--is-active:after {
    top: 25px;
}

.LeftSidebar__scroll-section .SidebarListItem--is-active:after {
    top: 20px;
}

And the overlaps are gone

**Comment by MyYogurt** [comment]
Thank you these changes fixed the issue.

**Comment by wl03355609** [comment]
I think that you should make this remain open because update the theme will screw it up again
@khanhas Can you make some changes here?
It didn't do that on Windows (Maybe because the macOS window control thing is there)

**Comment by wl03355609** [comment]
I forgot about those scrollable icon down there @MyYogurt 

.RootlistItem--is-active:before {
    top: 20px;
}

It'll get a little too left but I didn't find the way to correct that

**Comment by in-atus** [comment]
I'm using the Windows version and making these changes moved the three-dotted icon so it doesn't interfere with the Home button. Playlists, however, show up at the left side menu unaligned. What part in the user.css should I change to fix it?
![image](https://user-images.githubusercontent.com/74826989/99931237-bc23c980-2d8e-11eb-8217-12ba24a932e2.png)

**Comment by wl03355609** [comment]
@in-atus
if the icon (circular one) is NOT unaligned then you just adjust these two (top:25) make it higher might help I think?

.LeftSidebar__section .SidebarListItem--is-active:after {
top: 25px;
}

.LeftSidebar__scroll-section .SidebarListItem--is-active:after {
top: 20px;
}

**Comment by in-atus** [comment]
Already did that. Same results.

**Comment by whatsnewsisyphus** [comment]
Here is the correct fix:
/* Sidebar */
.LeftSidebar {
    margin-top: 24px;
}

**Comment by khanhas** [comment]
Thank you @whatsnewsisyphus!
Can someone test with this CSS:
```css
.body-container--mac .LeftSidebar {
    margin-top: 24px;
}
```
Also try zooming in and out to see if sidebar still positions correctly.

**Comment by whatsnewsisyphus** [comment]
> Thank you @whatsnewsisyphus!
> Can someone test with this CSS:
> 
> ```css
> .body-container--mac .LeftSidebar {
>     margin-top: 24px;
> }
> ```
> 
> Also try zooming in and out to see if sidebar still positions correctly.

That works, including zoom in.
