### ISSUE TITLE
[Dribbblish] What's the easiest way to switch positions of control buttons and title+cover section?

### ISSUE THREAD

**Issue by DanyGee** [morpheusthewhite/spicetify-themes#179]
I would like to switch positions of `control buttons section` and `cover+title section`.
What would be the easiest way to achieve that in all views (normal, fullscreen etc.)?

**Comment by JulienMaille** [comment]
You should swap `order` values here:
https://github.com/morpheusthewhite/spicetify-themes/blob/bed10d36d3fb21717616481e2467070970910fe4/Dribbblish/user.css#L1085-L1102

**Comment by DanyGee** [comment]
THX, it worked!
