### ISSUE TITLE
Certain themes simply do not work

### ISSUE THREAD

**Issue by jojoharry16** [morpheusthewhite/spicetify-themes#180]
First of all, these themes are all beautiful and everyone who worked on them deserve one hell of a pat on the back.

I'm setting the Nord theme across my system, and for a while Spicetify worked as intended and got the Nord theme on Spotify. At one point (maybe an hour into using it) the Spotify window became a single coloured block with just the 3 buttons in the top right visible. Hardware media buttons still controlled it, but the window itself was unresponsive. 

I did a quick restore and Spotify was back to its original self, so I redownloaded Spicetify and installed it but some themes just don't change Spotify either at all or only partially. 
From what I've tested Bittersweet works perfectly, Nord changes nothing (I redownloaded Nord from GitHub), and BIB-Green changes the font but incorrectly.

Thanks for reading, and let me know if this should go on the Spicetify-cli issues page

**Comment by morpheusthewhite** [comment]
Does spicetify gives you any error/warning after applying these themes?

**Comment by jojoharry16** [comment]
Nothing, just says "success Custom CSS is updates"

**Comment by morpheusthewhite** [comment]
This is either related to your themes and or spicetify. Can you try to delete and reinstall both spicetify (latest version) and all the themes?

On which platform are you running spicetify?

**Comment by jojoharry16** [comment]
I copied and pasted the full css for Nord directly from GitHub, so I doubt that's the cause.

I'm running Windows 10 version 2004

How, uh.... How do I uninstall it?

**Comment by morpheusthewhite** [comment]
You should instead download this repository and copy its content (with all the many folders) into the `spicetify` theme folder

**Comment by jojoharry16** [comment]
You were right about redownloading the repository. I had downloaded the whole repository before as well, all themes included, but somehow all the color.ini files had vanished. 

Hopefully this doesn't happen to anyone else, but in case it does there's this issue to look for
