### ISSUE TITLE
All icons are not showing up. Pop OS 20.04 LTS.

### ISSUE THREAD

**Issue by Myles124** [morpheusthewhite/spicetify-themes#186]
Icons do not show up, they are just displayed as boxes. I've done everything correctly installation wise so please do not link it. The dribbblish.js exstention is in the exstentions folder as it should be. Seems like a bug.
![Screenshot from 2020-10-25 20-26-26](https://user-images.githubusercontent.com/65736812/97125014-62cd6980-1700-11eb-81c4-ec419968fd96.png)

**Comment by morpheusthewhite** [comment]
Can you try to restore the default theme and reinstall Dribbblish and check if something changes. Also check to have the lastest `spicetify` version installed

**Comment by moukle** [comment]
Got the same problem (with default theme too).

**Versions**
- `spotify --version: 1.1.42.622.gbd112320, Copyright (c) 2020, Spotify Ltd`
- `spicetify --version: 1.1.0`
- Themes pointing to git head 058a27221ec1e7444f22a15b7bdaa3c427a48d8f

**Comment by morpheusthewhite** [comment]
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Check Console window to see if there is any error.

**Comment by moukle** [comment]
Did `spicetify enable-devtool` and I couldn't login anymore. Did reinstall spotify and now it's working again. I don't know why; I tried this a couple times before. But now it's working again for me :grin:
