### ISSUE TITLE
Dribbblish Themes Incredibly Slow (Windows 10)

### ISSUE THREAD

**Issue by lbibass** [morpheusthewhite/spicetify-themes#187]
Hey, so I followed the Dribbblish install process, and it looks great, but oh my dear god is it slow. It takes about 10-15 seconds for the app to respond to me trying to pause and play my music. It uses up about 20% of my CPU, which on a 3900x, is utterly ridiculous.

Any ideas on what's going on?

**Comment by morpheusthewhite** [comment]
I think this is more related to `spicetify-cli` than to this repository. @khanhas confirm this, I can eventually transfer the issue

**Comment by lbibass** [comment]
Sounds good, thanks for letting me know. I have no performance issues on the macOS Big Sur Beta.

**Comment by lbibass** [comment]
> Do you have many local files?

No, I have no local files whatsoever on my windows installation. on MacOS, I have quite a few.

**Comment by mowaffles** [comment]
I had this problem and it helped alot to enable hardware acceleration in the spotify settings

**Comment by JulienMaille** [comment]
Please reopen if you have more details on how to reproduce
