### ISSUE TITLE
[DribbblishDynamic] Local Files break the theme

### ISSUE THREAD

**Issue by oscargb1** [morpheusthewhite/spicetify-themes#189]
After playing a local song, the theme will be broken for following songs: the color will either not change or start randomly changing and the playing bar will show an incorrect album and "invalid date" @JulienMaille

**Comment by JulienMaille** [comment]
I don't think we can extract colors from local media, can we @khanhas ?

**Comment by JulienMaille** [comment]
@oscargb1 Can you confirm it is fixed?

**Comment by oscargb1** [comment]
Yeah, the issue is fixed now
