### ISSUE TITLE
Now playing not centered on Dribbblish

### ISSUE THREAD

**Issue by TheJaake** [morpheusthewhite/spicetify-themes#193]
After stretching the Dribbblish theme horizontally, the now-playing section is shifted to the right. This problem remains after a restart of the client and even a complete reinstall. I attempted editing the CSS myself, but to no avail. The dribbblish.js does imply that the now-playing section is centered, but the problem seems to be located in the underlying layer. 

I am running dwm window manager on Fedora Linux and using the Flatpak installation of Spotify.

![dribblish](https://user-images.githubusercontent.com/21030860/97522530-f8216580-196d-11eb-83e6-9897ecb006fc.png)

**Comment by SupremMotu** [comment]
I have the same problem. It happens on i3, dwm, and kde on Arch Linux.

**Comment by MyYogurt** [comment]
Can recreate problem on MacOS

**Comment by JulienMaille** [comment]
Can you guys try to remove this and see if it helps?
```css
.view-player .now-playing .cover-image-link-wrapper {
    width: var(--bar-cover-art-size);
    height: var(--bar-cover-art-size);

```

**Comment by SupremMotu** [comment]
> Can you guys try to enter dev mode, remove this from `user.css` and see if it helps?
> 
> ```css
> .view-player .now-playing .cover-image-link-wrapper {
>     width: var(--bar-cover-art-size);
>     height: var(--bar-cover-art-size);
> ```

![tmp2](https://user-images.githubusercontent.com/47583325/97788217-941cbe00-1b74-11eb-96e0-df54c8db81e1.png)

I believe the fix you said only moves the cover picture up.

**Comment by JulienMaille** [comment]
I don't have this issue under Windows, that's weird

**Comment by SupremMotu** [comment]
https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/user.css#L1212

You were talking about these lines right? It's only off center when the window is wide to a certain point.

**Comment by JulienMaille** [comment]
Can you try this
```css
.view-player .now-playing-container {
    max-width: none !important;
}
```

**Comment by SupremMotu** [comment]
![tmp3](https://user-images.githubusercontent.com/47583325/97791280-f1713900-1b8d-11eb-860a-468ee4932599.png)


> Can you try this
> 
> ```css
> .view-player .now-playing-container {
>     max-width: none !important;
> }
> ```

This seemed to work. Thank you very much.

**Comment by JulienMaille** [comment]
May I suggest to try DrribbblishDynamic :) ?

**Comment by SupremMotu** [comment]
I tried it, but the translucency for the album art was a little over what I prefer. Also, I have a little theme going on and the colors changing constantly doesn't work for me. Other than that it works fine.

**Comment by TheJaake** [comment]
> Can you try this
> 
> ```css
> .view-player .now-playing-container {
>     max-width: none !important;
> }
> ```

After applying this change in the user.css file and re-applying, the now-playing section doesn't shift nearly as far to the right as it had before, but on my ultrawide, the problem persists.
![dribbblish](https://user-images.githubusercontent.com/21030860/97827973-58c0e300-1c8b-11eb-8cea-83d9b8c6c0aa.png)
