### ISSUE TITLE
Dribbblish Dynamic stuck to yellow

### ISSUE THREAD

**Issue by ShadeReogen** [morpheusthewhite/spicetify-themes#197]
Im on v.0.9.9.
I copied the .js into the extensions folder by hand.

The Theme gets applied but it's stuck to yellow, the blurred album art in the background does change but the accent color doesn't

Edit: I'm on Windows 10.

I tried updating spicetify, now on v.1.1.0
Reset the config,ini, repeated the steps in Powershell.
Still only yellow.

**Comment by morpheusthewhite** [comment]
@JulienMaille

**Comment by JulienMaille** [comment]
Can you install with normal spicetify commands? Please check the developer console for any error message

**Comment by ShadeReogen** [comment]
> Can you install with normal spicetify commands? Please check the developer console for any error message

As I stated in the edit, I have then reset the default theme, and then installed it again through powershell

**Comment by JulienMaille** [comment]
Ok, what about the developer console? Any message here that could help?

**Comment by ShadeReogen** [comment]
I am sorry, but I have no idea about what that is, if you could tell me more or send me a link to figure out how to access it and see if any exceptions happen I'd appreciate it

**Comment by JulienMaille** [comment]
In order to help I need a way to reproduce your issue or at least know what is failing.
Press Ctrl+Shift+I to open the developer tools
![image](https://user-images.githubusercontent.com/182520/98279836-c5ddbc80-1f9a-11eb-9661-0ba342a6c8a2.png)
Then navigate to the console tab and share any error message you might see here
![image](https://user-images.githubusercontent.com/182520/98279894-da21b980-1f9a-11eb-8afd-d6166ea4e8c7.png)

**Comment by ShadeReogen** [comment]
Well I manually checked the drop down menu and tried the various shortcuts depicted in your screenshot, but nothing happens and that option is not there, and doesn't pop up either...

**Comment by morpheusthewhite** [comment]
You need to enable it first by running `spicetify enable-devtool`

**Comment by ShadeReogen** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/45570380/98396978-e8390e00-205e-11eb-90d9-78edc8a9e952.png)

Well, doesn't look good

**Comment by JulienMaille** [comment]
What's the content of `C:\Users\YOUR_NAME_HERE\AppData\Roaming\Spotify\Apps\zlink`?
It seems that `spicetifyWrapper.js` is missing from your install

**Comment by ShadeReogen** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/45570380/98402199-3225f200-2067-11eb-9a26-ed2a7af0e80a.png)

Looks like it is present tho..

**Comment by JulienMaille** [comment]
This file is outdated, you're missing some old Spicetify commit https://github.com/khanhas/spicetify-cli/commit/99468dd0e3536ee568084b7de132bee52992c78b
Not sure what you did, I think you did not follow the installation steps.

**Comment by JulienMaille** [comment]
Did the update fix it?

**Comment by ShadeReogen** [comment]
Sorry I didn't reply yet. I just did this:
`spiceitfy restore`
then deleted the `.spicetify` and `spicetify-cli` folders.
Reinstalled spicetify following all the steps shown in the official repo
Redownloaded this repo and put the themes into `.spicetify/Themes`
run the Dribbblish Dynamic install instructions.

Now it works.

Thank you very much for your help!
