### ISSUE TITLE
[Dribbblish] Sidebar Folders "break" after double-click

### ISSUE THREAD

**Issue by CREEATION** [morpheusthewhite/spicetify-themes#198]
![spicetify-dribbblish-folders](https://user-images.githubusercontent.com/3277769/98206102-a2cef080-1f39-11eb-8a08-b1d5af7e8049.png)

I've double-clicked the first two folders and didn't touch the third, see attachment.

Double-clicking plays the whole folder and lets me rename it. Guess the input field for renaming appearing causes this issue.
Clicking on a folder arrow icon to open/close it in the sidebar makes all folders appear normal again.

Probably just a UI update issue?

**Comment by morpheusthewhite** [comment]
Try to repeat the process and checking the console output

1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Check Console window to see if there is any error.

**Comment by CREEATION** [comment]
Oh, nah. No errors, or any output for that matter.

**Comment by khanhas** [comment]
Thanks for your report! I don't think this is a big problem and it doesn't destroy user experience any how, unless you try really hard. Just right click and hit rename, after you don't changing folder names, just hit reload or restart the client.
