### ISSUE TITLE
[Dribblish] Right drop-down menu not positioned correctly

### ISSUE THREAD

**Issue by mjuzikfrik** [morpheusthewhite/spicetify-themes#199]
Hello, 
I've search through open and closed issues but haven't seen it brought up. The drop-down menu on the right is set too far to left. I'm using Spotifynocontrol and set icon dodge to 0. I've seen it placed correctly on preview images.
![dribblish](https://user-images.githubusercontent.com/16630872/98523985-e34ea700-2276-11eb-8a8a-ae6047e25054.png)

**Comment by SupremMotu** [comment]
Do you happen to be using windows?

**Comment by mjuzikfrik** [comment]
Yes, I'm using Windows.  That'd be weird if there were inconsistencies between OSes.

**Comment by SupremMotu** [comment]
In windows that space is reserved for the buttons. The inconsistency is caused by spotify.

**Comment by mjuzikfrik** [comment]
Okay, thanks. I've got rid of the button altogether. :)
