### ISSUE TITLE
Sidebar problem

### ISSUE THREAD

**Issue by Ramdonx** [morpheusthewhite/spicetify-themes#200]
Hi!
I change --sidebar-width: 85px to --sidebar-width: 70px
![Sidebar](https://user-images.githubusercontent.com/40654074/99149450-140a5400-265c-11eb-8913-52cc50fea063.jpg)
Playlist icons are not centered, Any way to correct that?

**Comment by morpheusthewhite** [comment]
This is a question for the [Spectrum chat](https://spectrum.chat/spicetify)
