### ISSUE TITLE
bittersweet top banner

### ISSUE THREAD

**Issue by greengiant09** [morpheusthewhite/spicetify-themes#207]
When sitting at the top of an artist's page you can see a portion of their banner where there should be a border (on OSX)
<img width="1792" alt="Screen Shot 2020-12-02 at 11 57 49 PM" src="https://user-images.githubusercontent.com/75370848/100981332-88b60d00-34fb-11eb-8f2a-918b831fd2cd.png">

**Comment by morpheusthewhite** [comment]
@bandithedoge

**Comment by bandithedoge** [comment]
I will be doing a full rewrite of the theme soon and I'll make sure to address this.
