### ISSUE TITLE
DribblishDynamic Fullscreen Button Missing?

### ISSUE THREAD

**Issue by rsa16** [morpheusthewhite/spicetify-themes#209]
![image](https://user-images.githubusercontent.com/47797856/101365421-c4d9cc80-3871-11eb-9ac8-1d776e0b053d.png)
And in the gif here, https://github.com/morpheusthewhite/spicetify-themes/blob/master/DribbblishDynamic/color-match-bg.gif
![image](https://user-images.githubusercontent.com/47797856/101365714-1f732880-3872-11eb-8e60-299c69c4c961.png)
There is no fullscreen option other than the fullAppDisplay one. How can I fix this, and is this a bug?

**Comment by morpheusthewhite** [comment]
@JulienMaille

**Comment by rsa16** [comment]
Man, I feel so dumb. Sorry for the issue, I just restarted SpotifyNoControl and it worked.

**Comment by rsa16** [comment]
Sorry I closed it, I thought I fixed the issue, but nevermind... Apparently, when I restart Spotify it comes back, but when I click the fullscreen option and then try to use the... I dunno what it's called, the skip bar. This thing:
![image](https://user-images.githubusercontent.com/47797856/101388917-961e1f00-388e-11eb-94cf-4fb6eb28fe9d.png)
So apparently if I try to skip to a different part of the song, the fullscreen option goes away again, and I have to restart Spotify to get it back.

**Comment by JulienMaille** [comment]
Everything works fine on my side. Did you try not using SpotifyNoControl?

**Comment by rsa16** [comment]
Yes, I just tried. The same thing. Also weirdly, without SpotifyNoControl, it displays like so:
![image](https://user-images.githubusercontent.com/47797856/101408688-c5428980-38aa-11eb-9584-2a94473ce43f.png)
I don't think that's how it's supposed to behave?

**Comment by JulienMaille** [comment]
What about regular Dribbblish?

**Comment by rsa16** [comment]
Just tried the same thing.

**Comment by rsa16** [comment]
Regular Dribblish, same thing happens.

**Comment by rsa16** [comment]
Something I found using inspect element, (it's actually pretty helpful):
![image](https://user-images.githubusercontent.com/47797856/101556786-9a7b3280-3989-11eb-8d93-56b4003368bd.png)
Apparently, to my understanding at least, it's set to be visible on a certain condition? Also, for me `...style="display: none"`, and if I take that out, the button becomes greyed out like so:
![image](https://user-images.githubusercontent.com/47797856/101556994-0fe70300-398a-11eb-8804-b709dcd4f61d.png)
I think I'm gonna experiment a bit around with the CSS and JS, I may find something.

**Comment by JulienMaille** [comment]
Not sure what you have found exactly, but I've noticed the css will hide the button if the width is <900pix
In the inpector, you should be able to locate the css rules which did set `display: none`

**Comment by rsa16** [comment]
I did find that, and I removed that bit. It still doesn't work.

**Comment by JulienMaille** [comment]
@rsa16 Can you locate where the `display: none` comes from?
![image](https://user-images.githubusercontent.com/182520/101835776-93485600-3b3c-11eb-803e-84453e6d2523.png)

**Comment by rsa16** [comment]
Yes, I located it in my text editor, I removed it and applied it to Spicetify. I'm still having the same issue.

**Comment by JulienMaille** [comment]
Is that reproduced by anyone else?
