### ISSUE TITLE
Question about background blur.

### ISSUE THREAD

**Issue by OhItsTom** [morpheusthewhite/spicetify-themes#210]
I know this isnt a "bug" but i didnt know where else to ask, is there anyways to lessen how strong the blur is? Obviously i dont expect it to be ui based, im fine with editing the css or anything else. Just feel like the background blur is slightly too strong, especially for detailed cover art making it look just like a ugly blur of something unfamiliar.

Any help would be awesome!

DribbblishDynamic

**Comment by morpheusthewhite** [comment]
This is a question for the [spectrum chat](https://spectrum.chat/spicetify)
