### ISSUE TITLE
Local files have no logo

### ISSUE THREAD

**Issue by OhItsTom** [morpheusthewhite/spicetify-themes#211]
![image](https://user-images.githubusercontent.com/22730962/101837769-74939080-3b37-11eb-8255-a9e75987fac6.png)
DribbblishDynamic

**Comment by morpheusthewhite** [comment]
@JulienMaille

**Comment by rsa16** [comment]
I'm having the same issue, maybe it has something to do with the Local Files not showing unless you pick a folder in the settings?

**Comment by morpheusthewhite** [comment]
@OhItsTom please reinstall and check again
