### ISSUE TITLE
No secondary colour on the outside of the theme

### ISSUE THREAD

**Issue by Section3622** [morpheusthewhite/spicetify-themes#213]
I've searched for a solution but i couldn't find 1 so please help

![Capture](https://user-images.githubusercontent.com/75932284/102009455-7c8b4480-3d72-11eb-9041-644d3d7510b8.PNG)

**Comment by morpheusthewhite** [comment]
First, make sure you followed all the instructions in the [README](https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/README.md)

If you did, please provide:
- spotify version
- spicetify version
- logs in the console. To do that:
      - Run spicetify enable-devtools in terminal
      - Spotify will be restarted
      - Hit Ctrl + Shift + I to open DevTools window
      - Navigate to tab Console
      - Open lyric app on Spotify window
      - Check Console window to see if there is any error.

**Comment by Section3622** [comment]
Spotify Version: 1.1.4.197
Spicetify Version: v1.1.0
Logs: Pictures down there somewhere
![Capture](https://user-images.githubusercontent.com/75932284/102081548-6309fb80-3e4b-11eb-960a-f5adea803e36.PNG)

**Comment by morpheusthewhite** [comment]
@khanhas

**Comment by khanhas** [comment]
Are you using Spotify ad-blocked version?
Sorry, that spotify version is ancient and I have no plan to backward support.
