### ISSUE TITLE
Cannot see time left in song

### ISSUE THREAD

**Issue by basenjimae** [morpheusthewhite/spicetify-themes#214]
In normal Spotify, you can see the length of the song left to play along the progress bar. This is not the case with spicetify.

Play any song, and there is simply a lack of time for the song.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Spotify version: Any
 - Spicetify version: most recent

**Comment by morpheusthewhite** [comment]
Does it regard a specific theme?

**Comment by Ushrio** [comment]
For the Dribblish theme you can fix this issue by going into the `user.css` file and changing the `#player-text-elapsed` and `#player-text-remaining` from `display:none` to `display:flex`. Then just issue a `spicetify update` command to apply the changes. I don't know about any other themes.
