### ISSUE TITLE
NoSleep Offset Sidebar

### ISSUE THREAD

**Issue by onkoe** [morpheusthewhite/spicetify-themes#217]
**Describe the bug**
NoSleep causes many graphical bugs within Spotify with the new update. It offsets all playlists and, unlike how it is intended to look, the sidebar is quite large and shows the names. 

**To Reproduce**
1. Install NoSleep on Spotify 1.1.48.625.g1c87c7f7 or higher. 
2. Eyes bleed

**Expected behavior**
NoSleep should make the sidebar quite small, hide all text within it, and show playlists in small bubbles. This behavior happened with previous versions of Spotify, but I do not have a backup handy to show it. 

**Screenshots**
![Sidebar Issues](https://user-images.githubusercontent.com/66580279/102411844-4212e900-3fb8-11eb-8f7d-a94a8cf264f3.png)

**Logs**
https://hastebin.com/xevahudizo.sql

**Specifics (please complete the following information):**
 - OS: Windows 10 LTSC 1809
 - Spotify version: 1.1.48.625.g1c87c7f7
 - Spicetify version: 1.1.0
 - Theme name: NoSleep

**Comment by morpheusthewhite** [comment]
@3raxton

**Comment by khanhas** [comment]
I guess you have tried Dribbblish theme and it required you to inject its own extension. But you didn't unload that extension before trying other theme, run following commands to revert:
```
spicetify config extensions dribbblish.js-
spicetify apply
```

**Comment by 3raxton** [comment]
Let's hope that @khanhas is right here. @onkoe let me know if there are any issues & I'll help sort this out. 

Thanks for the mention @morpheusthewhite

**Comment by onkoe** [comment]
> I guess you have tried Dribbblish theme and it required you to inject its own extension. But you didn't unload that extension before trying other theme, run following commands to revert:
> 
> ```
> spicetify config extensions dribbblish.js-
> spicetify apply
> ```

This is correct. It's interesting that Dribbblish had caused the theme to look so different. I much prefer NoSleep without the minimized sidebar lol. Closing thread now.
