### ISSUE TITLE
Open /var/lib/snapd/snap/bin/spotify/Apps: not a directory

### ISSUE THREAD

**Issue by Ec4ll** [morpheusthewhite/spicetify-themes#218]
**Describe the bug**
When trying to run `spicetify apply` i get the error `open /var/lib/snapd/snap/bin/spotify/Apps: not a directory`.

**To Reproduce**
1. Download spotify with `snap install spotify`
2. Install spicetify.
3. Set `spotify_path = /var/lib/snapd/snap/bin/spotify` in `config.ini`
4. Set `prefs_path = /home/ecal/snap/spotify/43/.config/spotify/prefs` in `config.ini`
5. Run `spicetify apply`

**Expected behavior**
Spicetify to apply my selected color theme

**Logs**
<Ctrl>+<Shift>+I does not bring up devtools.

**Specifics (please complete the following information):**
 - OS: Arch
 - Spotify version: 1.1.46.916.g416cacf1
 - Spicetify version: 1.1.0

**Comment by morpheusthewhite** [comment]
Try to install Spotify through AUR and reset the configs

**Comment by Ec4ll** [comment]
Thank you everything works now. Just a note, [spotify](https://www.spotify.com/ca-en/download/linux/) recommends snap as the installation method, so it might be worthwhile noting spicetify doesn't work with it installed this way.
