### ISSUE TITLE
[Suggestion] Adding instruction for custom font file

### ISSUE THREAD

**Issue by auditt98** [morpheusthewhite/spicetify-themes#22]
I think we can update README.md with instructions on how to include custom fonts (if supported).

**Comment by morpheusthewhite** [comment]
Pull requests are welcome

**Comment by morpheusthewhite** [comment]
Why did you close this issue?

**Comment by auditt98** [comment]
Oh I thought I don't need to open the issue anymore since later I'll make a pull request for it anyway. I can reopen it if you want to.

**Comment by morpheusthewhite** [comment]
Oh good, then It is not necessary to reopen it

**Comment by morpheusthewhite** [comment]
I think this and other information about how creating custom themes should be added in the wiki, in a proper page.

If someone is interested in writing/contributing such a page, let me know
