### ISSUE TITLE
Weird Name on right side popup?

### ISSUE THREAD

**Issue by Alankar-Mahajan** [morpheusthewhite/spicetify-themes#220]
![weird name](https://user-images.githubusercontent.com/30779480/102727402-73d6d780-434b-11eb-8e06-b1281a230fb7.png)

What is this weird string in place of my profile name?

Installed Theme: Dribblish Dynamic (color scheme Dark, followed steps as given in its readme.md file)

Spicetify Version: 1.1.0
Distro: Ubuntu 20.04 LTS

**Comment by morpheusthewhite** [comment]
I think it does not depend on the theme itself, but on your Spotify version.

Try to change theme and check if it is still there.

**Comment by Alankar-Mahajan** [comment]
> I think it does not depend on the theme itself, but on your Spotify version.
> 
> Try to change theme and check if it is still there.

I changed to Arc-Dark theme(base color scheme) now and it is fine now. Here is the attachment:

![arc_dark_name](https://user-images.githubusercontent.com/30779480/102769199-54ba6300-43a8-11eb-94aa-70be4ca88a37.png)

So I  think it has something to do with the theme.

**Comment by morpheusthewhite** [comment]
That's indeed strange @JulienMaille

**Comment by Alankar-Mahajan** [comment]
> That's indeed strange @JulienMaille

I have another issue now. Arc Dark Theme was not installed infact no other theme is getting installed excpet Dribblish dynamic. I checked config.ini and it shows the name of theme applied but spotify is in default theme.

**Comment by JulienMaille** [comment]
Its like that in original dribbling, I don't know why

**Comment by morpheusthewhite** [comment]
@khanhas

**Comment by Alankar-Mahajan** [comment]
I have found that in _~/.config/spotify/Users_ there is folder with the same name as this string. I tried renaming it to see if something chnages but on restarting spotify a new folder was automatically created there with the same string as above.

**Comment by khanhas** [comment]
It's your user name, the button there is for accessing profile page. It doesn't matter that much so I don't think there should be any change.

**Comment by Alankar-Mahajan** [comment]
Done
