### ISSUE TITLE
Multiple themes refuse to load font

### ISSUE THREAD

**Issue by Steve-Bros** [morpheusthewhite/spicetify-themes#221]
# Bug Report
There are several themes that, when applied, can't load their intended fonts.

## Steps to reproduce the behavior:
1. Load Spicetify
2. Enter Powershell or equivalent
3. Attempt to load theme with non native font
4. Spotify instead loads with Times New Roman

If the font is installed during the session, there is a chance it might work properly, but the bug will reoccur after a reboot.

## Expected behavior
Upon applying the theme, it is to be expected that the corresponding font family would be used in the interface, as long as it can be found in the system.

## Screenshots
![image](https://user-images.githubusercontent.com/40872506/102824518-a06a0e00-43a2-11eb-98f1-d427302aaa19.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

**Specifics (please complete the following information):**
 - OS: Windows 10, version 20H2
 - Spotify version: 1.1.48.625.g1c87c7f7
 - Spicetify version: 1.1.0
 - Theme name: WintergatanBlueprint

**Comment by khanhas** [comment]
Did you turn config `overwrite_assets` on?

**Comment by Steve-Bros** [comment]
I tried to do so, nothing changed.

**Comment by khanhas** [comment]
After you changed, did you run `spicetify apply` again?

**Comment by Steve-Bros** [comment]
I did

**Comment by khanhas** [comment]
Sorry, maybe your theme is the problem. Wrong font name, wrong syntax, just check everything.
