### ISSUE TITLE
[Midnight-Light] Hidden/missing text

### ISSUE THREAD

**Issue by axxx007xxxz** [morpheusthewhite/spicetify-themes#228]
**Describe the bug**
Text is missing or hidden in some parts of the program.

**To Reproduce**
1. Download and apply Midnight-Light theme
2. Run Spotify
3. That's it.

**Expected behavior**
Text should always be visible.

**Screenshots**
![Screenshoot 1](https://user-images.githubusercontent.com/18650221/103316498-0a308a80-4a29-11eb-971c-edc02e7214c4.png)
User icon appears white in settings

![Screenshoot 2](https://user-images.githubusercontent.com/18650221/103316525-203e4b00-4a29-11eb-905b-30c6fe81881d.png)
"Learn more" button's text in Spotify Connect menu is not visible

![Screenshoot 3](https://user-images.githubusercontent.com/18650221/103316607-4c59cc00-4a29-11eb-81cf-34bc38c4d525.png)
"Connect to Facebook" button's text in settings is barely visible

![Screenshoot 4](https://user-images.githubusercontent.com/18650221/103316650-64315000-4a29-11eb-976d-7a2c68a6d915.png)
(not sure if it's an actual theme bug or Spotify's)
There's a space before every comma when playing in full screen mode

**Specifics:**
 - OS: Fedora 33
 - Spotify version 1.1.46.916.g416cacf1
 - Spicetify version 1.1.0
 - Midnight-Light theme

**Comment by axxx007xxxz** [comment]
![Screenshoot 5](https://user-images.githubusercontent.com/18650221/103317045-b3c44b80-4a2a-11eb-908a-0aee6380e8f7.png)
Title of unavailable songs is not visible unless you click on them

**Comment by morpheusthewhite** [comment]
> **Screenshots**
> ![Screenshoot 1](https://user-images.githubusercontent.com/18650221/103316498-0a308a80-4a29-11eb-971c-edc02e7214c4.png)
> User icon appears white in settings

For me it is not
 
> ![Screenshoot 2](https://user-images.githubusercontent.com/18650221/103316525-203e4b00-4a29-11eb-905b-30c6fe81881d.png)
> "Learn more" button's text in Spotify Connect menu is not visible
> ![Screenshoot 3](https://user-images.githubusercontent.com/18650221/103316607-4c59cc00-4a29-11eb-81cf-34bc38c4d525.png)
> "Connect to Facebook" button's text in settings is barely visible

I can confirm this

> ![Screenshoot 4](https://user-images.githubusercontent.com/18650221/103316650-64315000-4a29-11eb-976d-7a2c68a6d915.png)
> (not sure if it's an actual theme bug or Spotify's)
> There's a space before every comma when playing in full screen mode

I think this is up to spotify

**Comment by morpheusthewhite** [comment]
> ![Screenshoot 5](https://user-images.githubusercontent.com/18650221/103317045-b3c44b80-4a2a-11eb-908a-0aee6380e8f7.png)
> Title, author, album, etc. of unavailable songs are not visible unless you click on them

Send the link of a playlist with unavailable songs to reproduce this

**Comment by morpheusthewhite** [comment]
@SmithPeder

**Comment by axxx007xxxz** [comment]
> For me it is not

I didn't set an icon but it's supposed to show the default one you can see in the top right corner before username. 

> I think this is up to spotify

Yes, confimed. I tried with another theme.

> Send the link of a playlist with unavailable songs to reproduce this

The availability of a song varies by country.
You have to find one that isn't available where you live, or technically in your account's country.


Found another two:
![Screenshoot 6](https://user-images.githubusercontent.com/18650221/103357793-51179200-4ab4-11eb-9c22-9e68dc6f3442.png)
The warning "Spotify can't play this right now. If you have the file on your computer you can import it." isn't visible.

![Screenshoot 7](https://user-images.githubusercontent.com/18650221/103357872-891ed500-4ab4-11eb-899c-7f1772ff4a6e.png)
The text "Offline" isn't visible.

**Comment by SmithPeder** [comment]
Sorry, I've just gotten used to some of these 🙃  I'll fix it now 🔧

**Comment by axxx007xxxz** [comment]
Great, thanks!

**Comment by axxx007xxxz** [comment]
I noticed another little detail:
![Screenshoot 6](https://user-images.githubusercontent.com/18650221/104813101-3577ef80-5807-11eb-8340-3b69ca6a85f0.png)
it's supposed to show a padlock during a private session.

**Comment by morpheusthewhite** [comment]
@SmithPeder

**Comment by SmithPeder** [comment]
This should do it
https://github.com/morpheusthewhite/spicetify-themes/pull/292
