### ISSUE TITLE
Dark theme on Dribblish Dynamic.

### ISSUE THREAD

**Issue by phoenix277yt** [morpheusthewhite/spicetify-themes#229]
How do you enable the dark theme on dribblish dynamic? it's in there in the readme but no instructions. i've tried using the theme without the color.ini and also with it. its the same result.

fyi - im talking about the main player and not the highlights.

![image](https://user-images.githubusercontent.com/73348506/103339453-6fc35c00-4aa7-11eb-9403-5c288c8da7f3.png)

**Comment by morpheusthewhite** [comment]
Please read https://github.com/morpheusthewhite/spicetify-themes/tree/master/DribbblishDynamic#color-schemes
