### ISSUE TITLE
The button customization is not working 

### ISSUE THREAD

**Issue by richardtanur** [morpheusthewhite/spicetify-themes#23]
How to change the customization button in all themes?
for example:
Pop-Dark
![image](https://user-images.githubusercontent.com/58125871/69488285-ed2a9f00-0e99-11ea-9518-03d02295ef66.png)

**Comment by auditt98** [comment]
I think you can't change how they look. It's a part of the window (to my knowledge as I haven't touched windows desktop since windows form a few years ago) and Spotify sure isn't using custom made buttons.

**Comment by morpheusthewhite** [comment]
> I think you can't change how they look. It's a part of the window (to my knowledge as I haven't touched windows desktop since windows form a few years ago) and Spotify sure isn't using custom made buttons.

Yes, I think that too: that buttons are managed by the OS
