### ISSUE TITLE
DribbblishDynamic continous RGB light effect?

### ISSUE THREAD

**Issue by ragnarcb** [morpheusthewhite/spicetify-themes#232]
Can we somehow achieve a continuous, with optional breathing (first the light fades to black and then comes back in different color) RGB effect by modifying the javascript or css codes? I believe it's possible since it already changes its colors according to album cover. Anyone good at js and kind to make this and share? Thanks

**Comment by morpheusthewhite** [comment]
Please use the [spectrum chat](https://spectrum.chat/spicetify) for asking for suggestions and tips
