### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by Julian9261** [morpheusthewhite/spicetify-themes#234]
Colors look weird and not like on the provided images, the "surroundings" of the main fg have the same color as the fg. I checked the color.api file and the colors were set correct there, but it looks completely different in my spotify. I followed all the steps on how to install and got no errors. This happens to all themes but I used the horizon theme in this image
https://user-images.githubusercontent.com/76516169/103477614-dc4c9c80-4dc0-11eb-8172-8912a279d741.png

**Comment by morpheusthewhite** [comment]
Please provide the following info
    OS: [e.g. iOS]
    Spotify version [e.g. 1.1.10.546.ge08ef575]
    Spicetify version [e.g. 1.1.0]
    Theme name (or if it applies to many)

**Comment by Julian9261** [comment]
OS: [Windows]
Spotify version [1.1.4.197.g92d52c4f]
Spicetify version [1.1.0]
Theme's (all)

**Comment by morpheusthewhite** [comment]
You probably mean all color schemes, right? The theme is just Dribbblish

**Comment by morpheusthewhite** [comment]
Check if the Spotify dev console logged something and post it here

**Comment by Julian9261** [comment]
> 
> 
> You probably mean all color schemes, right? The theme is just Dribbblish

Yeah, sorry

> 
>
> Check if the Spotify dev console logged something and post it here
Idk where to find that tbh

**Comment by morpheusthewhite** [comment]
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

**Comment by Julian9261** [comment]
https://user-images.githubusercontent.com/76516169/103549611-f1e8c180-4ea7-11eb-8ab9-3b1665a347c2.png

This is what it gives me

**Comment by morpheusthewhite** [comment]
Can you run `spicetify restore` and repeat the steps? It seems like fonts are not working at least

**Comment by Julian9261** [comment]
Didn't fix it unfortunately, the console still says the fonts aren't working

**Comment by Julian9261** [comment]
https://user-images.githubusercontent.com/76516169/103664355-7a339900-4f72-11eb-9064-64080ec1f302.png

A bit later this showed up

**Comment by khanhas** [comment]
Did you turn config `overwrite_assets` on?
If you didn't, set it to 1 and run `spicetify restore backup apply`.

**Comment by khanhas** [comment]
Wait, you are using old Spotify client. It is not supported, sorry.

**Comment by Julian9261** [comment]
Ah 1.14 is not? Too bad... That's the one without ads. Thanks for the help anyways !

**Comment by Julian9261** [comment]
Is there not a way for me to make it supported by changing something in a file? The only things that look messed up are the "surroundings"

**Comment by morpheusthewhite** [comment]
You probably need to tweak with the developer tools to try to change it easily
