### ISSUE TITLE
Material-Ocean volume slider displayed backwards

### ISSUE THREAD

**Issue by a1sop0s** [morpheusthewhite/spicetify-themes#241]
**Describe the bug**
The volume slider is displayed backwards upon hovering.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play a song of your choice
2. Hover over the volume slider

**Expected behaviour**
The portion behind the volume slider should be highlighted. (the lower part of the volume)

**Actual behaviour**
The portion after the volume slider is highlighted. (the higher part of the volume)

**Screenshots**
![Spotify_UCB0HycY0l](https://user-images.githubusercontent.com/18088532/104504833-b5c20900-55eb-11eb-9f22-9a1a7ca07cec.png)
![Spotify_sojYzkp9OH](https://user-images.githubusercontent.com/18088532/104504842-b8bcf980-55eb-11eb-918f-61ab5b0368df.png)

**Logs**
```console
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://genius.app.spotify.com/lyrics.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.48.625.g1c87c7f7
 - Spicetify version: 1.1.0
 - Theme name: Material-Ocean

**Comment by morpheusthewhite** [comment]
@Blacksuan19

**Comment by Blacksuan19** [comment]
🤔

**Comment by Blacksuan19** [comment]
@a1sop0s check the main theme repo [here](https://github.com/material-ocean/Spotify-Theme) I just pushed an update that should make the sliders better with other improvements

**Comment by a1sop0s** [comment]
> @a1sop0s check the main theme repo [here](https://github.com/material-ocean/Spotify-Theme) I just pushed an update that should make the sliders better with other improvements

@Blacksuan19 This seems to have solved the issue, just needs to be merged.

Not part of the current issue, (I'll create a new issue if necessary) but the shortcut button on the album cover has a very dislocated "hitbox" if you will. 
![image](https://user-images.githubusercontent.com/18088532/107545483-0705ee00-6bd4-11eb-9681-3bf548f4bee6.png)

**Comment by Blacksuan19** [comment]
> > @a1sop0s check the main theme repo [here](https://github.com/material-ocean/Spotify-Theme) I just pushed an update that should make the sliders better with other improvements
> 
> @Blacksuan19 This seems to have solved the issue, just needs to be merged.
> 
> Not part of the current issue, (I'll create a new issue if necessary) but the shortcut button on the album cover has a very dislocated "hitbox" if you will.
> ![image](https://user-images.githubusercontent.com/18088532/107545483-0705ee00-6bd4-11eb-9681-3bf548f4bee6.png)

will take a look into this as well.

**Comment by Blacksuan19** [comment]
> > > @a1sop0s check the main theme repo [here](https://github.com/material-ocean/Spotify-Theme) I just pushed an update that should make the sliders better with other improvements
> > 
> > 
> > @Blacksuan19 This seems to have solved the issue, just needs to be merged.
> > Not part of the current issue, (I'll create a new issue if necessary) but the shortcut button on the album cover has a very dislocated "hitbox" if you will.
> > ![image](https://user-images.githubusercontent.com/18088532/107545483-0705ee00-6bd4-11eb-9681-3bf548f4bee6.png)
> 
> will take a look into this as well.

the hitbox is not dislocated, the cursor changing to a pointer is part of the cover image when clicked it will take you to the current playlist

**Comment by Blacksuan19** [comment]
i have fixed the confusing cursor behaviour in that area, check the separate repo

**Comment by Blacksuan19** [comment]
@a1sop0s you can close this now
