### ISSUE TITLE
am i missing something? (missing text and player controls)

### ISSUE THREAD

**Issue by CodingArctic** [morpheusthewhite/spicetify-themes#244]
**Describe the bug**
For basically all themes I try, the side text is missing for the most part, and the player controls aren't there.

**To Reproduce**
1. Use Pop-Dark
2. See no player controls or text

**Expected behavior**
Things to be there? lmao

**Screenshots**
https://i.imgur.com/ARDYvib.png

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
webnowplaying.js:106 WebSocket connection to 'ws://127.0.0.1:8974/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
init @ webnowplaying.js:106
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/playlist.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/buddy-list.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/css/buddy-list.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/css/playlist.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
4webnowplaying.js:106 WebSocket connection to 'ws://127.0.0.1:8974/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version Can't find it, but its latest version
 - Spicetify version 1.1.0
 - Theme name Pop-Dark

**Comment by khanhas** [comment]
```
spicetify config extensions dribbblish.js-
spicetify apply
```

**Comment by CodingArctic** [comment]
@khanhas Pop-Dark isn't part of dribbblish? I do have the extension installed tho and it doesn't help

**Comment by morpheusthewhite** [comment]
You should UNINSTALL the dribbblish extension when not using Dribbblish theme, that's what khanhas's commands do

**Comment by CodingArctic** [comment]
I understand that now. The pop-dark still isnt working properly tho.
![image](https://user-images.githubusercontent.com/16868830/104880065-f5129180-592c-11eb-8676-cc5f160f8240.png)

**Comment by CodingArctic** [comment]
Dribbblish themes also don't work properly even with the extension still

**Comment by CodingArctic** [comment]
the common issue between the two seem to be missing icons, does this mean something?

**Comment by khanhas** [comment]
Please uninstall your Spotify and reinstall with latest installler from website. Then run `spicetify backup apply`

**Comment by CodingArctic** [comment]
alright, that seemed to work. thank you!
