### ISSUE TITLE
Flatten font/icons

### ISSUE THREAD

**Issue by czyzniek** [morpheusthewhite/spicetify-themes#245]
**Describe the bug**
Should Flatten or other themes have such bold and misplaces icons/font?
![image](https://user-images.githubusercontent.com/22362814/105717304-4370f300-5f20-11eb-8208-4fe09676970c.png)

**To Reproduce**
Load Flatten on newest Spotify + spicetify

**Expected behavior**
As is presented on Wiki page:
![image](https://user-images.githubusercontent.com/22362814/105717356-51267880-5f20-11eb-97ae-fd4baee91a6a.png)

**Logs**
There is no errors in console.

**Specifics (please complete the following information):**
 - OS: Manjaro 20.2.1 Nibia (Arch)
 - Spotify version: 1.1.42.622.gbd112320
 - Spicetify version: 1.1.0
 - Theme name: Flatten

**Comment by morpheusthewhite** [comment]
It shouldn't. It probably depends on your font configuration. You can try to `spicetify restore` and `spicetify apply`

**Comment by czyzniek** [comment]
Works, thanks! :+1:
