### ISSUE TITLE
[DribblishDynamic] border color don't change with local files

### ISSUE THREAD

**Issue by Syycorax** [morpheusthewhite/spicetify-themes#247]
**Describe the bug**
The border colors don't change with local files

**To Reproduce**
1. Import local songs in spotify 
2. play one 

**Expected behavior**
The colors should change according to the cover colors

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version 1.1.51.382.g8e3b11ed
 - Spicetify version 1.1.0
 - Dribblish Dynamic

**Comment by Halloyo** [comment]
I believe DribblishDynamic uses Spicetify's colorextractor which only works with songs/tracks/etc. that have a spotify URI. To use local file cover colours, you would have to use a third-party library afaik.

**Comment by morpheusthewhite** [comment]
> I believe DribblishDynamic uses Spicetify's colorextractor which only works with songs/tracks/etc. that have a spotify URI. To use local file cover colours, you would have to use a third-party library afaik.

Yes, see https://github.com/morpheusthewhite/spicetify-themes/issues/189
