### ISSUE TITLE
[Request] Nord: Increase Clickable Thickness of Track Bar

### ISSUE THREAD

**Issue by duncanam** [morpheusthewhite/spicetify-themes#25]
Hi @doubletruth , 

May I request that the thickness of the playback track progression bar is increased slightly in the Nord theme? As it is currently designed, it is very difficult to click locations on the bar to jump around in a track. 

Let me know if I can help in any way. Thanks!

**Comment by morpheusthewhite** [comment]
@rien333

**Comment by rien333** [comment]
I agree that the progress bar is hard to click, but then again, I rarely want to jump to specific moments in songs. So I feel like its importance warrants its size.  Most music players I've used have small progress bars (see this [iTunes screenshot](https://lh4.googleusercontent.com/-o69kmcQwqjg/ULv5cvt-RKI/AAAAAAAASr0/6d7YSH3n3qE/s640/iTunes%252011%252004.jpg)),  or lack them all together (e.g. cmus). 

What I would suggest instead is that you bind some key(s) to seek forward/backward in songs. That way, you won't ever miss the progress bar, and get a lot more precision and speed going. spicetify [allows you to do this](https://github.com/khanhas/spicetify-cli/issues/27). For example, you could add the following code to the `keyboardShortcut.js` extension (and run `spicetify apply` afterwards): 

```js
registerBind("[", false, false, false, seekBackward);
registerBind("]", false, false, false, seekForward);

...

function seek(amount) {
    Spicetify.Player.seek(Spicetify.Player.getProgress() + parseInt(amount) * 1000);
}

function seekBackward() {
    seek(-10)
}

function seekForward() {
    seek(10)
}

```
This will now jump backward/forward on <kbd>[</kbd> and <kbd>]</kbd>. You can make multiple functions (one that seeks very far, and one that seeks very precise),  or just change the value `10` if you want more fine-grained control over seeking.

**Comment by morpheusthewhite** [comment]
> Nonetheless, the progress bar is indeed too hard to click. Interestingly, the volume bar slider is way less easy to miss. It seems to have some non-visible height that adds to it's clickable bounding box (see the css inspector). If you could add a few pixels of such a non-visible height to the progress bar I would happily put it in the theme (and maybe just a couple of more for the visible portion of the bar). I must say that my css is not good enough to implement this myself, nor do I care enough atm to learn more of it.
> 
> That said, like I've already said before, most of the css is _not_ done by me, but by the main spicetify developer (I imagine that holds for a lot of other themes too). If you think some bar is too small, and should have a little extra non-visible height added to it, you should probably open an issue in the main repo.

@khanhas
