### ISSUE TITLE
DribbblishDynamic Spotify No Control Wont Open

### ISSUE THREAD

**Issue by OhItsTom** [morpheusthewhite/spicetify-themes#250]
**Describe the bug**
Spotify will open normally when launching straight from the source application, but when using DribbblishDynamic nocontrol shortcut a cmd flashes then spotify doesnt open, A reinstall and restart of pc did not help.

**Expected behavior**
To launch spotify without controls

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version Latest
 - Spicetify version Latest
 - DribbblishDynamic

**Comment by khanhas** [comment]
What version of Spotify you are using? Windows Store or normal?
By default it will start normal Spotify that locates at %APPDATA%. However, Windows Store version locates somewhere else, maybe that's why it doesn't launch.
You can simply just provide a parameter for SpotifyNoControl to know what to launch. I recommend just launch `spicetify auto`.
Now make a shortcut out of SpotifyNoControl.exe and add `"spicetify auto"` next to it like this:
![image](https://user-images.githubusercontent.com/26436809/106389414-ea78f180-642e-11eb-95d8-cd828c56e370.png)

**Comment by morpheusthewhite** [comment]
Can you start it from command line and see if something interesting gets printed?

**Comment by morpheusthewhite** [comment]
@bernawastaken

**Comment by bernawastaken** [comment]
@morpheusthewhite executing from the command line nothing gets printed but it now works, even running off the executable.
![image](https://user-images.githubusercontent.com/43864475/107127624-415b4c80-68af-11eb-9258-d5ad1d78ef93.png)

**Comment by adx74** [comment]
Same issue, but i have this error when i want to launch it
![image](https://user-images.githubusercontent.com/34185333/108621867-9a8db900-7435-11eb-89ec-a00a6ac3f60a.png)

**Comment by adx74** [comment]
Same problem here, i can't launch Spotify, the shortcut with "spicetify auto" doesn't work, and terminal doesn't work, if someone can help me please. (Je suis français si ça peut aider certains pour la rédaction des messages)
![image](https://user-images.githubusercontent.com/34185333/108621978-4c2cea00-7436-11eb-9f79-709227cca581.png)

**Comment by SunkenInTime** [comment]
I followed the steps and it still didn't work.
Just to confirm, you're telling me to run spicetify auto in Powershell, then go to the spotifynocontrol shortcut and do this:
![image](https://user-images.githubusercontent.com/76637177/110211754-117b7680-7e66-11eb-9953-6a2c3961f1be.png)
and then click on the shortcut and it should work/

**Comment by morpheusthewhite** [comment]
> I followed the steps and it still didn't work.
> Just to confirm, you're telling me to run spicetify auto in Powershell, then go to the spotifynocontrol shortcut and do this:
> ![image](https://user-images.githubusercontent.com/76637177/110211754-117b7680-7e66-11eb-9953-6a2c3961f1be.png)
> and then click on the shortcut and it should work?

It's actually not needed to run it in powershell, it is a debugging step that you can try to see if you get some errors

**Comment by SunkenInTime** [comment]
When I added spicetify auto to it, it still didn't launch. Keep in mind that spotify works with the theme, but I can't just get the spotify no control.exe to launch.

**Comment by SunkenInTime** [comment]
Ver is 1.2.0 for spicetify btw.

**Comment by morpheusthewhite** [comment]
> When I added spicetify auto to it, it still didn't launch. Keep in mind that spotify works with the theme, but I can't just get the spotify no control.exe to launch.

Did you try from powershell as well? Do you get something printed?

**Comment by JulienMaille** [comment]
Latest commited SpotifyNoControl can take arguments but not "spotify auto".
Have you pinned spotifynocontrol to the taskbar and ran it from here?

**Comment by zachjmurphy** [comment]
I'm having the same issue. SpotifyNoControl doesn't seem to launch.

- Latest Spotify Version
- Latest Spicetify Version
- Latest SpotifyNoControl Version

**Comment by morpheusthewhite** [comment]
@JulienMaille did you test it against the start bar as well?

**Comment by morpheusthewhite** [comment]
@zachjmurphy try to test this 2 different launcher and see if any of those works
- [previous Dribbblish launcher](https://github.com/morpheusthewhite/spicetify-themes/blob/79536a31be5e300dfef1e7360fc733c25cc9655a/Dribbblish/SpotifyNoControl.exe?raw=true)
- AHK alternative (produce 2 different icons on taskbar): https://github.com/SaifAqqad/AHK_SpotifyNoControl

**Comment by JulienMaille** [comment]
You can also try this one I just built: https://github.com/JulienMaille/SpotifyNoControl/releases/tag/0.1

**Comment by zachjmurphy** [comment]
> @zachjmurphy try to test these 2 different launcher and see if any of these work
> 
> * [previous Dribbblish launcher](https://github.com/morpheusthewhite/spicetify-themes/blob/79536a31be5e300dfef1e7360fc733c25cc9655a/Dribbblish/SpotifyNoControl.exe?raw=true)
> * [AHK alternative](https://github.com/SaifAqqad/AHK_SpotifyNoControl) (produce 2 different icons on taskbar)

The previous Dribbblish launcher works perfectly and doesn't cause any double icon issues on the taskbar.

**Comment by SunkenInTime** [comment]
The previous version works.

**Comment by allanf181** [comment]
I am having this error:
`Error: Failed to load shortcut file`

**Comment by dylan-thomas832** [comment]
I have the same issue: SpotifyNoControl.exe immediately closes after opening.

However, I noticed that if I have regular Spotify open (with Dribbblish theme applied), and then I open the SpotifyNoControl.exe, it applies the "no Windows controls" to the originally opened Spotify instance, and closes.

**Comment by JulienMaille** [comment]
Can you try latest commit? I have added a help message show if you pass it any argument
```
USAGE: SpotifyNoControl.exe [SpotifyNoControl.lnk] [Spotify.lnk] [spotify.exe]
  - [SpotifyNoControl.lnk] is the path to your shortcut pointing to SpotifyNoControl
    defaults to %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\SpotifyNoControl.lnk
             or %appdata%\Microsoft\Windows\Start Menu\Programs\SpotifyNoControl.lnk
  - [Spotify.lnk] is the path to your shortcut pointing to Spotify
    defaults to %appdata%\Microsoft\Windows\Start Menu\Programs\Spotify.lnk
  - [spotify.exe] is the path to Spotify executable
    defaults to %appdata%\Spotify\spotify.exe
```

**Comment by dylan-thomas832** [comment]
@JulienMaille Thanks! I just tried this out, and it worked for me. The "SpotifyNoControl.exe" opened with the correct theme and removed the Windows 10 control buttons.

For anyone else, I used the SpotifyNoControl.exe from commit b003a3ae82ac20e67e610fcca800548c0ca07fda

## Note:

 This opens in the "multi-task bar icon" way, and you have to pin the CMD window's icon to get it to launch correctly from the task bar (Not the actual Spotify client's window). I included screenshots, if that's helpful:

Immediately after opening. CMD window and Spotify open, removal of control buttons & menu not applied.
![image](https://user-images.githubusercontent.com/6612382/115054966-df225780-9eae-11eb-96f8-2b10ce87f290.png)

After ~5 seconds, the CMD window closes, and the control buttons and menu are removed. This also shows the multi-taskbar icons.
![image](https://user-images.githubusercontent.com/6612382/115055256-3f18fe00-9eaf-11eb-8a01-4dde26cd3d39.png)

**Comment by sinankizar** [comment]
Tried every version but no joy here :(
OS: Windows
Spotify Latest
Spicetify Latest

**Comment by morpheusthewhite** [comment]
@JulienMaille it seems like some people are still experiencing this problem

**Comment by ImCheesecake** [comment]
Yeah I can't get it to open anything

**Comment by JulienMaille** [comment]
I'm not using it, but I tried again today and it works fine.

**Comment by ImCheesecake** [comment]
@JulienMaille 

Yeah I have no idea why it works now. I've tested every version of it but now it just works. Before that the window just closed, no matter how I ran the file
