### ISSUE TITLE
cant get rid of this  playlist preview

### ISSUE THREAD

**Issue by abhisheknclt** [morpheusthewhite/spicetify-themes#251]
irrespective of what theme did i applied , this section wont  change . i once tried to install Dribbishdynamic. it appeared after that 
![2021-02-02_13-03](https://user-images.githubusercontent.com/76902855/106567322-a8979a80-6557-11eb-847d-6699d3de8f48.png)

**Comment by morpheusthewhite** [comment]
Try `spicetify restore` and then `spicetify apply`

**Comment by abhisheknclt** [comment]
yea thanks it worked man
