### ISSUE TITLE
Missing step / "wrong" command on Dribblish instructions for Linux

### ISSUE THREAD

**Issue by victorbrca** [morpheusthewhite/spicetify-themes#252]
**Describe the bug**
Missing step / "wrong" command on Dribblish instructions for Linux. With the current instructions, if the Extensions folder doesn't already exist, `dribbblish.js` gets copied as a file named `Extensions`.

**To Reproduce**
1. Install spicetify and themes on a new Linux machine
2. Follow the instructions for Dribblish

**Specifics (please complete the following information):**
 - OS: Arch
 - Spotify version: N/A
 - Spicetify version: N/A
 - Theme name: Dribbblish
 
---

Instructions should be:

```
cd "$(dirname "$(spicetify -c)")/Themes/Dribbblish"
mkdir -p ../../Extensions
cp dribbblish.js ../../Extensions/.
spicetify config extensions dribbblish.js
spicetify config current_theme Dribbblish color_scheme base
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply
```

* _Added line 2 and modified line 3_

**Comment by Xanaxus** [comment]
hey i tried to use the given commands but i am unable to execute can you help me 

* os : Pop!OS
* 
![image](https://user-images.githubusercontent.com/53279068/107668722-f9756480-6cb6-11eb-9d2a-805475e359cf.png)

**Comment by JulienMaille** [comment]
@khanhas agreed?

**Comment by khanhas** [comment]
Okay. If you can pull request on Dribbblish too, that would be great.
