### ISSUE TITLE
[DribbblishDynamic] --transparent-window-controls not working

### ISSUE THREAD

**Issue by JacProsser** [morpheusthewhite/spicetify-themes#253]
--transparent-window-controls is not working on the spotify exe shortcut.

**Comment by khanhas** [comment]
Spotify version, Windows version? And how did you add the flag?

**Comment by JacProsser** [comment]
Spotify Version: 1.1.52.687.gf5565fe5
Windows Version: Microsoft Windows 10 Home, 10.0.18363 n/a BUILD 18363
Way flag was added: C:\Users\Jac\AppData\Roaming\Spotify\Spotify.exe  --transparent-window-controls

**Comment by khanhas** [comment]
Does it stop working recently?
My spotify is still at 1.1.51 and I see no new update.

**Comment by JacProsser** [comment]
if you are talking about the --transparent-window-controls then i don't know because it has never worked when i've tried it

**Comment by khanhas** [comment]
I don't know about 1.1.52 but it still works normally on my 1.1.51
Did you exit Spotify first before running with that flag?

**Comment by JacProsser** [comment]
indeed i've completely closed it down

**Comment by xpopy** [comment]
I'm guessing I have the same issue. Using --transparent-window-controls only makes the button semi-transparent and not completely hidden
![image](https://user-images.githubusercontent.com/3540971/107216723-71b8fd00-6a0d-11eb-87f3-cf7283014837.png)

**Comment by JulienMaille** [comment]
I think it works exactly as described here: https://github.com/khanhas/spicetify-cli/wiki/Spotify-Commandline-Flags
Please use this instead
https://github.com/morpheusthewhite/spicetify-themes/blob/a634ac005090f08d3a2e8f96df9b0763b1cac488/Dribbblish/README.md#L73-L75

**Comment by JulienMaille** [comment]
Still works fine with 1.1.52.687

**Comment by morpheusthewhite** [comment]
I think we can leave it open for the moment, it's still quite recent as an issue

**Comment by jeeeem** [comment]
> ols reg

How to use the SpotifyNoControl.exe as the spotify client? I tried opening it without an existing spotify but nothing happens. It just flash like it usually do.

**Comment by JulienMaille** [comment]
> How to use the SpotifyNoControl.exe as the spotify client? I tried opening it without an existing spotify but nothing happens. It just flash like it normally does.

It is launcher, you still need to Install Spotify

https://github.com/morpheusthewhite/spicetify-themes/blob/a634ac005090f08d3a2e8f96df9b0763b1cac488/Dribbblish/README.md#L74

**Comment by jeeeem** [comment]
> 
> 
> > How to use the SpotifyNoControl.exe as the spotify client? I tried opening it without an existing spotify but nothing happens. It just flash like it normally does.
> 
> It is a launcher, you still need to Install Spotify
> 
> https://github.com/morpheusthewhite/spicetify-themes/blob/a634ac005090f08d3a2e8f96df9b0763b1cac488/DribbblishDynamic/README.md#L45

Yes, I already installed spotify, I even already using the dribblish theme, but since I could not use the `SpotifyNoControl.exe` as a launcher I just use the flag `--transparent-window-controls`. But my question is why when I use the `SpotifyNoControl.exe` as a launcher, nothing happens. I don't know what is the issue, but it is working when I used it in already existing spotify client, the 3 dots and other buttons are hidden.

**Comment by morpheusthewhite** [comment]
@JacProsser did you solve it? How?

**Comment by JacProsser** [comment]
well i didn't actually fix anything i just realised how stupid i was being where it says "transparent" not like completely invisible but yes it works in the version i was on
