### ISSUE TITLE
[DribbblishDynamic] Icons hard to see when there is a bright accent color in the album art.

### ISSUE THREAD

**Issue by 9hax** [morpheusthewhite/spicetify-themes#260]
You cant see the Icons in the side menu when the Scrtipt picks a bright accent color from the album art.

![image](https://user-images.githubusercontent.com/23525377/107191258-335f1600-69ec-11eb-8284-9bd44809e4c2.png)

I have already implemented a fix and will publish it as a pull request.

**Comment by morpheusthewhite** [comment]
Solved with https://github.com/morpheusthewhite/spicetify-themes/pull/261
