### ISSUE TITLE
Feature request - Album Covers next to songs in playlists

### ISSUE THREAD

**Issue by Idyllwilde** [morpheusthewhite/spicetify-themes#267]
Hi,

I think it would be great to upgrade themes to have the album covers next to the songs in playlists.
Would this be a possibility? Cause it really helps when browsing through a playlist.

**Comment by n00bhax** [comment]
I would love this feature too

**Comment by Idyllwilde** [comment]
I saw this feature will be in the newest Spotify update for the Desktop app,.

**Comment by morpheusthewhite** [comment]
Then this is not really a feature anymore

**Comment by n00bhax** [comment]
The newest Spotify update is the reason I installed a custom theme. There are lots of things I don't like about it except for the album covers next to songs. Why would this feature not be needed anymore? Will it automatically come to custom themes?

**Comment by morpheusthewhite** [comment]
Yes I think it should
