### ISSUE TITLE
Dribbblish(for example): how to make song timer working.

### ISSUE THREAD

**Issue by mlunax** [morpheusthewhite/spicetify-themes#269]
I would love to know if it possible to custom themes to show the timers of a song: (e.g)
![image](https://user-images.githubusercontent.com/11018865/107810111-744c8700-6d6c-11eb-9755-91b9ae2533d9.png)
Thank you for advance.

**Comment by khanhas** [comment]
It's only hidden by CSS. Find their class name and search in user.css file.
You need to find a place to put them tho, it's not gonna be easy.

**Comment by mlunax** [comment]
I am asking if it you know the class name cuz in Dribbblish's user.css isn't something like 'timer' or 'time'.

**Comment by morpheusthewhite** [comment]
@mlunax enable and use dev-tools

**Comment by mlunax** [comment]
Dev-tools not working here.

**Comment by khanhas** [comment]
```
spicetify enable-devtool
```

**Comment by mlunax** [comment]
I know, it doesn't working.
