### ISSUE TITLE
[Midnight-Light] (Ugly) gradient at top of Home and Radio tabs

### ISSUE THREAD

**Issue by r0uv3n** [morpheusthewhite/spicetify-themes#276]
Using Midnight-Light, open the "Home" or "Radio" tabs and scroll to the top. You will see an unseemly gradient that clashes with the constant colors around it:

**Expected behavior**
The same constant color as in the "Browse" tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/26653862/108577017-ddf60380-731f-11eb-886a-c7f5cbeb960f.png)

![image](https://user-images.githubusercontent.com/26653862/108576999-d0407e00-731f-11eb-8d01-c3fbc69e9b6d.png)

**Specifics:**
 - OS: Windows 10
 - Spotify version 1.1.52.687.gf5565fe5
 - Spicetify version 1.2.0
 - Theme name: Midnight-Light

**Comment by morpheusthewhite** [comment]
@SmithPeder

**Comment by xxxbetterrun** [comment]
same prob as you

**Comment by xxxbetterrun** [comment]
same prob. x x

**Comment by SmithPeder** [comment]
This https://github.com/morpheusthewhite/spicetify-themes/pull/291 should do it @r0uv3n and @xxxbetterrun

**Comment by r0uv3n** [comment]
Thank you very much!
