### ISSUE TITLE
1.1.53.608.g7ed9c03a broke Dribbblish

### ISSUE THREAD

**Issue by JulienMaille** [morpheusthewhite/spicetify-themes#277]
Just got an update, I ran `spicetify backup apply` as usual, but now the theme is totally broken, I believe the css doesn't match the new design. Do you confirm this is not an issue on my side?

**Comment by khanhas** [comment]
Still stuck at 1.1.51 and see no sight of any update.

**Comment by JulienMaille** [comment]
You can probably force the update using the official setup. Here what dribbblish looks like on my setup, I'm desperate
![image](https://user-images.githubusercontent.com/182520/108621120-fc97ef80-7430-11eb-98f4-6daf2159360b.png)

**Comment by JulienMaille** [comment]
I ran the official installer and got `1.1.52.687.gf5565fe5` which is broken too. At this point I really wish it's just me

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/108625898-1ff68500-7499-11eb-952e-5eca15917e31.png)

Yeah, you probably applied old backup.
Reinstall and run `spicetify clean backup apply`

**Comment by JulienMaille** [comment]
Why the hell is your client in french? :)
> Reinstall spotify and run `spicetify clean backup apply`

Thanks, for readers the command is `clear` no `clean`
