### ISSUE TITLE
Bittersweet click issue

### ISSUE THREAD

**Issue by Milo123459** [morpheusthewhite/spicetify-themes#279]
**Describe the bug**
Pause / resume button turns green
**To Reproduce**
Go onto a playlist
Hold down click on play / resume button
It turns green (theme bittersweet)
**Expected behavior**
It should go some shade other then green
**Screenshots**

**Logs**
n/a
**Specifics (please complete the following information):**
 - OS: windows 10
 - Spotify version n/a
 - Spicetify version n/a
 - Theme name bitter sweet

**Comment by morpheusthewhite** [comment]
@bandithedoge
