### ISSUE TITLE
Weird Line In Dribble Theme

### ISSUE THREAD

**Issue by OblivionGhoul** [morpheusthewhite/spicetify-themes#281]
I get this weird space in the middle of the Dribble theme. 

![image](https://user-images.githubusercontent.com/45471929/109109403-216abc00-76ea-11eb-9255-653a0f5dfbc1.png)

![image](https://user-images.githubusercontent.com/45471929/109109427-2d567e00-76ea-11eb-84ff-18cdc8d88087.png)

**Comment by khanhas** [comment]
Doesn't occur to me. Can you use devtool to find what element is it at?

**Comment by OblivionGhoul** [comment]
It only happens when you want spotify to show your friends list.

![image](https://user-images.githubusercontent.com/45471929/109185726-201aad00-7745-11eb-8902-c73c976fd5b4.png)
I think this is the element. (when I select the empty space with the devtool)

**Comment by khanhas** [comment]
Sorry, I can't find any element, around the element you pointed to, has that border.
Is this Dribbblish or DribbblishDynamic?

**Comment by OblivionGhoul** [comment]
This is dribbblish, did I point to the wrong element? I just selected the element of the space. You only see it if you have your friends list open.

**Comment by khanhas** [comment]
>You only see it if you have your friends list open.
Yes, I'm aware of that. But still, I didn't see it.
>This is dribbblish, did I point to the wrong element
I have no idea. I looked around and I didn't see any element has border attribute.

**Comment by OblivionGhoul** [comment]
![image](https://user-images.githubusercontent.com/45471929/109340469-e8336880-781d-11eb-8562-9440f8d76343.png)

This might be the correct element

**Comment by khanhas** [comment]
Can you fix it yourself and put it in your user.css?

**Comment by OblivionGhoul** [comment]
Sure I will try
