### ISSUE TITLE
Spicetify no control, not launching for Dribblish

### ISSUE THREAD

**Issue by SunkenInTime** [morpheusthewhite/spicetify-themes#283]
I don't know how to replicate this problem.

specs: 
Windows 10 home latest version
Spotify latest version
Dribblish

**Comment by soarn** [comment]
I get this off and on as well, running `SpotifyNoControl.exe` spawns the terminal window but crashes.  This happens even after clean install, it's only worked once but never again.  (This was with dynamic.)

**Comment by soarn** [comment]
@SunkenInTime #250

**Comment by morpheusthewhite** [comment]
Please specify Spotify version (latest is not unique nor meaningful)
