### ISSUE TITLE
Playlist images not aligned correctly within sidebar when using Dribbblish

### ISSUE THREAD

**Issue by strafe** [morpheusthewhite/spicetify-themes#286]
**Describe the bug**
Playlist pictures are not centred within the in the sidebar, or within the selected highlight. I've seen this in a bunch of screenshots so I'm sure it's not unique to my environment.
<img width="66" alt="image" src="https://user-images.githubusercontent.com/15663890/110200247-dde42080-7e54-11eb-9045-99f2753bc9a1.png">

**Expected behavior**
Setting `margin` to `10px auto` on `.playlist-picture` seems to fix it for me, but I'm not sure how portable that is.
<img width="69" alt="image" src="https://user-images.githubusercontent.com/15663890/110200207-aaa19180-7e54-11eb-99e7-9b56885e5836.png">

**Specifics (please complete the following information):**
 - OS: macOS
 - Spotify version: 1.1.54.592.gc0b20638
 - Spicetify version: 1.2.1
 - Theme name: Dribbblish

**Comment by khanhas** [comment]
When did you download the themes package? Is it the latest?

**Comment by strafe** [comment]
> When did you download the themes package? Is it the latest?

Just cloned the repository an hour before making the issue.

**Comment by felipemldias** [comment]
Hey there, sorry to budge in (and thanks for the awesome theme btw), but I'm also facing this minor "issue". Playlist folders also show their first letter dislocated, as shown here. My specifications are the same as strafe's, except that I'm using Dribblish dynamic

![image](https://user-images.githubusercontent.com/63819261/110210093-dcbfed00-7e6e-11eb-9644-377b439e736f.png)

**Comment by khanhas** [comment]
@felipemldias What is your OS?

**Comment by felipemldias** [comment]
macOS Big Sur 11.2.1

**Comment by khanhas** [comment]
I guess it only happens on macOS then.

**Comment by felipemldias** [comment]
Yeah, it's not a big thing anyway. I was just wondering, do your know how can I make the playlist folder font transparent? I don't know which line I should change

**Comment by felipemldias** [comment]
Yes, it might be. I was just wondering, do your know how can I make the playlist folder font transparent? I don't know which line I should change

**Comment by felipemldias** [comment]
Setting margin to 10px auto on .playlist-picture definitely didn't work for me btw hahah

![image](https://user-images.githubusercontent.com/63819261/110211416-4e9b3500-7e75-11eb-9dee-9e7207b71cf3.png)

**Comment by mateusmlo** [comment]
> I guess it only happens on macOS then.

It doesn't. I'm currently on Windows 10 and playlist folders also appear with the first letter dislocated. There should be a better way to show folders in this theme, some users have a lot of them.
![image](https://user-images.githubusercontent.com/13263031/111088995-9c184180-8508-11eb-806b-7994521f303b.png)

**Comment by felipemldias** [comment]
I find the hovering cards pretty useful to identify the folder's name, it's just a pity that the menu icon is dislocated like this

**Comment by khanhas** [comment]
What is the "better way" you think it should be?

**Comment by felipemldias** [comment]
Personally I find the hover card pretty useful/sufficient, it's just a pity there's this little detail with the border alignment and folder first letter. But I find this a pretty awesome theme!

**Comment by stpnwf** [comment]
Love the theme, but I find it very hard to use without folders, specially if one has too many playlists. This is how I get around the dislocated letter issue, so the folders are usable.
![Screenshot from 2021-03-27 13-48-00](https://user-images.githubusercontent.com/81482539/112728140-7d507c80-8f04-11eb-82cb-94ef038d2678.png)

**Comment by JulienMaille** [comment]
Is it still an open bug?

**Comment by felipemldias** [comment]
I'm afraid it is, at least on my end, as I'm unaware of any new releases

**Comment by JulienMaille** [comment]
Can you try latest DribblishDynamic?

**Comment by felipemldias** [comment]
I apologize, I was wrong. The playlist icons look much better now, thanks! However, the images are still a little misaligned, at least on my end.

![image](https://user-images.githubusercontent.com/63819261/115799544-1b721e00-a3af-11eb-991e-66a9570b02bd.png)
![image](https://user-images.githubusercontent.com/63819261/115799554-22009580-a3af-11eb-95d8-f219f628eb2c.png)
![image](https://user-images.githubusercontent.com/63819261/115799571-2b89fd80-a3af-11eb-912c-3b39ea020810.png)

**Comment by JulienMaille** [comment]
Do you have a retina display?

**Comment by felipemldias** [comment]
Yes, but these screenshots were taken on a 1080p external monitor, I use my
computer with its lid closed

**Comment by JulienMaille** [comment]
What about other icons? are they well centered?

**Comment by felipemldias** [comment]
Yes, other icons on the sidebar are perfectly centered. Just the playlist images are dislocated

![image](https://user-images.githubusercontent.com/63819261/115912036-3abb8a80-a445-11eb-97f8-28d40b038df4.png)

**Comment by JulienMaille** [comment]
Can you share a snapshot with a playlist item selected in the source viewer? Like this:
![image](https://user-images.githubusercontent.com/182520/115913449-e8905e80-a470-11eb-993c-5707cfb962ad.png)

**Comment by felipemldias** [comment]
I'm afraid I'm on a mac, and I'm not sure how to use DevTools to see an app's source. I'm downloading Xcode to see if I can view Spotify's source and I'll get back to you as soon as I can

PS: I don't really code 😅

**Comment by JulienMaille** [comment]
Not sure it it woks on MacOs, but if you right click (or do the equivalent thing on a mac) on an empty section of Spotify, you should get a menu with "Inspect Element". No need for xcode, spotify is a web app, and all you need is to display the source of the webpage like you would do on safari. You can try F12 too

**Comment by felipemldias** [comment]
I believe in mac it doesn't give me that option, I can only right click items to see their options. I even tried to use chrome's dev tools to see if I could inspect Spotify, but it didn't work too 😕

![image](https://user-images.githubusercontent.com/63819261/115920170-2fba2780-a450-11eb-9f50-398a96032099.png)

**Comment by JulienMaille** [comment]
Can you open `~/spicetify_data/config.ini` and then look for `prefs_path` file?
Do you have something like this: `app.enable-developer-mode=true`

**Comment by felipemldias** [comment]
I the prefs file this is what I've found:

![image](https://user-images.githubusercontent.com/63819261/115926491-4fa21900-a459-11eb-9e3a-ad4d5aebf0c9.png)

**Comment by felipemldias** [comment]
I didn't fin that line. What I found on the prefs file was this:
![image](https://user-images.githubusercontent.com/63819261/115926902-f8e90f00-a459-11eb-8adc-221a78c419b7.png)

**Comment by JulienMaille** [comment]
add the line and try again to right click in an empty spot

**Comment by felipemldias** [comment]
It worked! 
![image](https://user-images.githubusercontent.com/63819261/115929771-b4ac3d80-a45e-11eb-91e8-705fc6eab651.png)

**Comment by JulienMaille** [comment]
Cool! But unfortunately not helpful.
Can you click the item above
![image](https://user-images.githubusercontent.com/182520/115951404-dea64400-a4e0-11eb-8539-9e33260533fb.png)
and share both the style and computed tab content (please expand them a little bit)
![image](https://user-images.githubusercontent.com/182520/115951450-101f0f80-a4e1-11eb-91b3-3768f9d0eac9.png)

**Comment by felipemldias** [comment]
I see now! 

![image](https://user-images.githubusercontent.com/63819261/115965023-8b8eba00-a4fd-11eb-90ed-38e6751b41a6.png)

![image](https://user-images.githubusercontent.com/63819261/115964969-51bdb380-a4fd-11eb-8984-aa8c2b448eb1.png)

I found that setting indentation to 0.45 seemed to center it better

**Comment by JulienMaille** [comment]
I don't think you are running the latest DribblishDynamic because the padding should be overridden by user.css
![image](https://user-images.githubusercontent.com/182520/115969970-f3fe8b00-a53f-11eb-9b41-3f771b01c1d5.png)

**Comment by felipemldias** [comment]
But if that were so, how can I have the new playlist icons? Perhaps I
missed something during installation, but I did substitute the Driblish
dynamic folder on themes folder and the js file on the extensions folder
and then ran the spicetify apply command. I apologize if I'm just wasting
your time, I'm a bit clueless 😅

**Comment by JulienMaille** [comment]
@felipemldias this is weird
do you have the `.scrollbar-style-visible-mac` class here? (instead of my `.scrollbar-style-visible-windows`)
![image](https://user-images.githubusercontent.com/182520/115972088-b6542f00-a54c-11eb-9e70-45ea344aed00.png)

Do you have this around line 670 of user.css?
```css
.scrollbar-style-visible-linux .RootlistItem,
.scrollbar-style-visible-mac .RootlistItem,
.scrollbar-style-visible-windows .RootlistItem {
    padding-right: var(--left-sidebar-padding-right);
    padding-left: var(--left-sidebar-padding-left);
}
```

**Comment by felipemldias** [comment]
I have .scrollbar-style-when-scrolling-mac

![image](https://user-images.githubusercontent.com/63819261/115972504-159e4900-a525-11eb-99db-a5a71ae2e121.png)

I have it around line 636

![image](https://user-images.githubusercontent.com/63819261/115972583-a6752480-a525-11eb-9d97-2fa494d98bab.png)

**Comment by JulienMaille** [comment]
can you replace it with
```css
.RootlistItem {
    padding-right: var(--left-sidebar-padding-right);
    padding-left: var(--left-sidebar-padding-left);
}
```

**Comment by felipemldias** [comment]
Yep! That did it! Thank you so much and sorry for taking that long! 

![image](https://user-images.githubusercontent.com/63819261/115973304-56e52780-a52a-11eb-95e0-3a813da56297.png)

**Comment by strafe** [comment]
@morpheusthewhite not sure why this was closed as nothing actually got changed upstream. Also @JulienMaille's suggestion does not center the albums correctly for me. 

This issue is specifically about Dribbblish (not dynamic) on macOS. Although I realise this seems to be an issue on many platforms/setups.

![](https://waifu2x.booru.pics/outfiles/4ff69fc2c8b84b6bfd213769b9e54b9212e22541_s2_n0.jpg)
<sup>With @JulienMaille's changes.</sup>

**Comment by JulienMaille** [comment]
My suggested changes are for DribblishDynamic, I'll push à commit later today

**Comment by strafe** [comment]
> My suggested changes are for DribblishDynamic, I'll push à commit later today

That's fine, appreciate your contribution :) Just that this issue is for the non-dynamic variant.

**Comment by morpheusthewhite** [comment]
I closed it since I expected JulienMaille's solution to work on more platforms. If this is still not solved on MacOs then I will reopen it

**Comment by Aerozolic** [comment]
Just installed the theme and can confirm that the playlist images are not centered.
Running macOS Catalina.
