### ISSUE TITLE
Dribbblish Dynamic theme gets broken when delete confirmation dialog is showed

### ISSUE THREAD

**Issue by pnthach95** [morpheusthewhite/spicetify-themes#290]
**Describe the bug**

When deleting a playlist, a warning text is shown at the bottom and isn't hidden when pressed cancel.

`You haven't installed 'dribbblish-dynamic.js' extension. Please follow instructions on theme README page.`

I actually installed that extension. See my config file screenshot below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find your playlist
2. Right-click and press Delete
3. See the error

**Expected behaviour**

Delete confirmation dialogue should be at the centre of the window.

**Screenshots**

Delete confirmation dialogue

![image](https://user-images.githubusercontent.com/31266357/110591596-d81b7180-81ab-11eb-8a0e-57fc07545d18.png)

After presssing cancel

![image](https://user-images.githubusercontent.com/31266357/110591625-e1a4d980-81ab-11eb-9f6d-94490f9cf986.png)

My `config.ini` file

![image](https://user-images.githubusercontent.com/31266357/110591642-e8335100-81ab-11eb-9871-aa5dd83dd003.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

![image](https://user-images.githubusercontent.com/31266357/110591659-ed909b80-81ab-11eb-8ed3-79b0d02ced05.png)

**Specifics (please complete the following information):**
 - OS: Windows 10 20H2 build 19042.804
 - Spotify version 1.1.54.592.gc0b20638
 - Spicetify version 1.2.1
 - Theme name Dribbblish Dynamic

**Comment by Mozartuss** [comment]
I have the same Versions installed (spotify and spicetify version) and I can not reproduce your issue. 
It looks like you did not copy the dribbblish-dynamic.js file to the extension folder.
Maybe you have to reinstall the dribbblish dynamic theme by following the installation guide step-by-step to solve the issue.

**Comment by pnthach95** [comment]
After reinstall everything, the issue is still there

![image](https://user-images.githubusercontent.com/31266357/111466764-42a55200-8756-11eb-93b4-f82eb3d10462.png)

I have dribbblish-dynamic.js in the extension folder

![image](https://user-images.githubusercontent.com/31266357/111467045-944ddc80-8756-11eb-9a88-7caa8f0799b4.png)

Config file:

```
[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
lyric_force_no_sync          = 0
song_page                    = 0
visualization_high_framerate = 0
experimental_features        = 0
fastUser_switching           = 0
home                         = 0
lyric_always_show            = 0
radio                        = 0
extensions                   = dribbblish-dynamic.js
custom_apps                  = 

[Setting]
current_theme           = DribbblishDynamic
color_scheme            = dark
inject_css              = 1
overwrite_assets        = 1
spotify_path            = C:\Users\thach\AppData\Roaming\Spotify
prefs_path              = C:\Users\thach\AppData\Roaming\Spotify\prefs
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.54.592.gc0b20638

```

**Comment by Mozartuss** [comment]
Sorry I can't reproduce your Issue,I don't know how to handle this.

**Comment by pnthach95** [comment]
I just reinstalled Windows and discovered that it only works if playlist is in range of left list. For more context, I recorded this:

https://user-images.githubusercontent.com/31266357/115065253-1bd66900-9f18-11eb-882b-2d2fee5a7acf.mp4

Look like it can't scroll left list to playlist to show delete dialog.

**Comment by JulienMaille** [comment]
I can reproduce it but I have no idea what's going on!

**Comment by JulienMaille** [comment]
Should be fixed in latest commit

**Comment by pnthach95** [comment]
It don't show error text, but still move up main view to show delete dialog. I don't delete playlist everyday, I can live with it.

Closed.
