### ISSUE TITLE
Dribbblish: Center controls

### ISSUE THREAD

**Issue by RhapsodySL** [morpheusthewhite/spicetify-themes#301]
I'm trying to center the controls on Dribbblish. I typically have Spotify in the background of my second monitor with a window covering the right half of the screen, so with the default configuration I can't see the currently playing song. I've actually done this before on an older version of Dribbblish (https://i.imgur.com/G1G9gPd.png) but I recently updated both it and Spicetify and overwrote the user.css. I've tried to replicate the changes but the closest I can get is this (https://rhap.city/i/mHSSS.png). In comparison, there's notable padding on both the left and right of the cover art, and on the right of the fullscreen button.

I'm asking for help on this instead of doing it myself because I have minimal knowledge of CSS and what's shown in the user.css file is basically wizardry to me. I've tried using the devtools to figure out what to modify but with no luck. Any help would be appreciated.

**Comment by khanhas** [comment]
I'm confused. You said you want centered control and you already got this https://rhap.city/i/mHSSS.png . What is the problem again?

**Comment by RhapsodySL** [comment]
Compare the two screenshots and you'll see as I said in the post that there's significant padding on the album image and to the right of the fullscreen button (there isn't in the first image, which was my setup before updating, and there is in the second, which is my setup after updating and trying to redo the customizations). I don't recall the specific customizations I made but it was only removing some of the code, so I'm wondering if anyone can point me in the right direction.

**Comment by khanhas** [comment]
Okay, just be brief next time.
If you can provide your current user.css, that would be helpful.

**Comment by RhapsodySL** [comment]
Here's my user.css: https://gist.github.com/RhapsodySL/caaf771b3ae842a5d5a95cfd15ba1d48

**Comment by khanhas** [comment]
Find `.view-player .now-playing .cover-image-link-wrapper` and add `flex: 0 1 60px`
Lower number 60px if you want.
