### ISSUE TITLE
Bittersweet playlist hover colors turn grin

### ISSUE THREAD

**Issue by brian-miranda** [morpheusthewhite/spicetify-themes#307]
**Describe the bug**
When you hover over tracks on a playlist, the song title will be highlighted in green instead of purple.

**To Reproduce**
1. Go to a created playlist
2. Play any song.
3. With or without the song selected, hover over it and the song title will turn green.

**Expected behavior**
Since the song that is playing is highlighted in purple and all fields remain purple on hover I expected the song title to also stay purple instead of green

**Screenshots**

**Logs**

```console
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/playlist.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/buddy-list.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/css/buddy-list.css.map: 
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/css/playlist.css.map: 
```

**Specifics (please complete the following information):**
 - OS: macOS 10.15.7
 - Spotify version 1.1.55.498.gf9a83c60
 - Spicetify version 1.2.1
 - Theme name: Bittersweet

**Comment by morpheusthewhite** [comment]
@bandithedoge

**Comment by bandithedoge** [comment]
I'm honestly thinking of ditching this theme. It's messy, has a lot of issues and would require a rewrite. Unless someone else bothers to maintain it, @morpheusthewhite has my permission to remove it from the repo.

**Comment by morpheusthewhite** [comment]
I am going to update the theme README then but not removing it for the moment. I will also properly label these issues and close them.
