### ISSUE TITLE
Arc-Dark message errors

### ISSUE THREAD

**Issue by Milo123459** [morpheusthewhite/spicetify-themes#312]
**Describe the bug**
The text looks weird and can't be read
**To Reproduce**
1. Click heart on a song
2. Text box appears with unredable text.
3. If you are offline, text is unreadable
4. You get the idea
**Expected behavior**
maybe some other colour?
**Screenshots**
![img](https://salvage.is-inside.me/UFYqX8YN.png)
**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.
logs won't be neeeded.
```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version n/a
 - Spicetify version 1.2.1
 - Theme name Arc-Dark

**Comment by morpheusthewhite** [comment]
@meliot

**Comment by Milo123459** [comment]
@santoru (doesn't ping if you edit)

**Comment by santoru** [comment]
I checked this but I can't find the CSS selector for that element, it seems it is not even drawn on the DOM. Do you know a theme that has it colored correctly or different than white?

**Comment by Milo123459** [comment]
The text just isn't readable because of the background colour basically being the same as the text colour
