### ISSUE TITLE
Dribblish Dracula toast notification not styled.

### ISSUE THREAD

**Issue by craigjamesdobson** [morpheusthewhite/spicetify-themes#317]
**Describe the bug**
When selecting dont like the toast notification is not styled within Dribblish Dracula theme (White background with white text)

**To Reproduce**
1. Go to: Discover Weekly
2. Click on: 'Dont like' button
3. See toast notification that appears unstyled to this theme.

**Expected behavior**
Match styling of this theme.

**Screenshots**
![popup](https://user-images.githubusercontent.com/21035045/114538319-29a39a00-9c4b-11eb-9236-7385ac290cd7.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.56.595.g2d2da0de
 - Spicetify version: 1.2.1
 - Theme name: Dribbish Dracula

**Comment by morpheusthewhite** [comment]
@katawajojo

**Comment by katawajojo** [comment]
oh! I never noticed this. Let me look into this and fix that up.

**Comment by katawajojo** [comment]
Heya! I made a pull request with the fix. I also noticed an issue with the "Offline" banner, so I fixed that as well c:

<img width="912" alt="Spotify_2021-04-19_17-46-45" src="https://user-images.githubusercontent.com/13071927/115320813-697cec80-a137-11eb-87a3-4555e5432618.png">
