### ISSUE TITLE
Changing font on DribblishDynamic

### ISSUE THREAD

**Issue by steviejeebies** [morpheusthewhite/spicetify-themes#322]
Hi @JulienMaille, just a quick question about the DribblishDynamic theme, if I want to change the fonts on my local machine for the following, what value should I change in the CSS? Tried playing around with it but had no luck. Excellent theme by the way!

![Untitled](https://user-images.githubusercontent.com/47434040/115159809-d5eee180-a08c-11eb-916d-b12a861a7fe2.png)

**Comment by JulienMaille** [comment]
Right click the element you want to style and select "Inspect Element"
![image](https://user-images.githubusercontent.com/182520/115212849-3cade280-a101-11eb-9e48-ef1a351b18e1.png)

Then look at the css selectors for that item
![image](https://user-images.githubusercontent.com/182520/115212994-636c1900-a101-11eb-8e0a-dae314590bb7.png)

In that case I would use `.Card__info-subtitle-description`

You can the edit user.css
```css
.Card__info-subtitle-description {
    font-family: Comic Sans MS;
}
```
![image](https://user-images.githubusercontent.com/182520/115213357-b940c100-a101-11eb-8a21-66b138b6ee17.png)

**Comment by JulienMaille** [comment]
If you can't find it, create it `.profile .username { /* your css here */ }`

**Comment by steviejeebies** [comment]
Thank you very much!
