### ISSUE TITLE
Quick question about theme updates

### ISSUE THREAD

**Issue by Jnss98b** [morpheusthewhite/spicetify-themes#324]
Do the updates get pushed automatically or do I have to download the css file (or the whole folder) every time?

**Comment by katawajojo** [comment]
You have to download the updates yourself for themes. I recommend setting up Git on your system to make updating super painless.

**Comment by Jnss98b** [comment]
> You have to download the updates yourself for themes. I recommend setting up Git on your system to make updating super painless.

How would I go about doing that

**Comment by Jnss98b** [comment]
@katawajojo How would I go about doing that

**Comment by morpheusthewhite** [comment]
Set up git and copy this entire repository inside `spicetify`'s theme folder (note that also the .git needs to be there). Then, to update, you just need to `git pull`

**Comment by Jnss98b** [comment]
I get the error below when I tried to run `git fetch origin master`

`fatal: repository 'https://github.com/morpheusthewhite/spicetify-themes/tree/master/DribbblishDynamic/' not found`

**Comment by morpheusthewhite** [comment]
Did you copy the .git folder? Because it seems like the origin url points to DribbblishDynamic

**Comment by Jnss98b** [comment]
Oh do I need to pull the whole repo with all other themes? That sounds kinda overkill

**Comment by morpheusthewhite** [comment]
Yes you need, this git repository tracks all the theme as you can see
