### ISSUE TITLE
Can i change buttons' bg color?

### ISSUE THREAD

**Issue by ArashMaghsoodi** [morpheusthewhite/spicetify-themes#330]
Hi, is it possible to change the "Play" button and other buttons' color? I just don't like them to be green and the text in it is light gray which isn't much visible. How can I change it?
![Can i change it](https://user-images.githubusercontent.com/82510375/115779143-d78e1180-a3cc-11eb-8afe-c9d9b167e9bf.PNG)

**Comment by JulienMaille** [comment]
Which thème is that?

**Comment by ArashMaghsoodi** [comment]
> Which theme is that?

"DribbblishDynamic" Dark
Changing secondry_fg and main_fg doesn't do anything at all.

**Comment by JulienMaille** [comment]
Those buttons shouldn't stay green

**Comment by morpheusthewhite** [comment]
@ArashMaghsoodi make sure you installed the theme correctly
