### ISSUE TITLE
Icons Disappeared 

### ISSUE THREAD

**Issue by p-marg** [morpheusthewhite/spicetify-themes#331]
![image](https://user-images.githubusercontent.com/82775791/115783894-b7a32180-a3bd-11eb-8901-a0f9ecb81052.png)
Dribbblish latest Update, Color SHeme Horizon.
I hide every icon at the sidebar, like Home, Browse, etc. and can't seem to find a way to get them back.

**Comment by crypticC0der** [comment]
how did you do this
