### ISSUE TITLE
DribbblishDynamic Dark glitchy

### ISSUE THREAD

**Issue by sicr0** [morpheusthewhite/spicetify-themes#332]
**Describe the bug**
Sometimes using the DribbblishDynamic Dark theme Spotify starts behaving glitchy with flickering colors. It solves only if I close the application.

**To Reproduce**
1. I tried to find a pattern but it appears to happen at random after some time using it, not with a specific song.

**Logs**
`spicetify enable-devtools` doesn't work

**Specifics (please complete the following information):**
 - OS: Linux 5.10.30-1-MANJARO
 - Spotify version 1.1.56.595.g2d2da0de
 - Spicetify version 1.2.1
 - DribbblishDynamic Dark

**Comment by morpheusthewhite** [comment]
Can you at least record a video and upload it?
