### ISSUE TITLE
Icons missing, dynamic colors not working

### ISSUE THREAD

**Issue by Aerozolic** [morpheusthewhite/spicetify-themes#333]
Just saw the DribbblishDynamic theme getting updated and wanted to try it out. Only that it doesn't seem to work. Screenshot added:

![Screen Shot 2021-04-25 at 21 23 40](https://user-images.githubusercontent.com/25500346/116004895-7d2fc380-a60d-11eb-87db-abdd0ad18cac.png)

 - macOS Catalina 10.15.7 and also Windows 10 21H1
 - Spotify version 1.1.58
 - Spicetify version 1.2.1
 - DribbblishDynamic

**Comment by marharols** [comment]
Having the same issue, the icons are rendered if I use a modified color.ini file they show up but they blend in with the default settings.

**Comment by NoTextToSpeech** [comment]
I found a solution to this issue.

Using the following commands I managed to fix the bug and make it work for me.

spicetify restore
spicetify config extensions dribbblish-dynamic.js
spicetify config extensions dribbblish.js-
spicetify config current_theme DribbblishDynamic
spicetify config color_scheme dark
spicetify apply

Hope this fixes it up for you :)

**Comment by morpheusthewhite** [comment]
> spicetify restore
> spicetify config extensions dribbblish-dynamic.js
> spicetify config extensions dribbblish.js-
> spicetify config current_theme DribbblishDynamic
> spicetify config color_scheme dark
> spicetify apply

@Aerozolic try running this
