### ISSUE TITLE
Recently Played icon missing

### ISSUE THREAD

**Issue by Aerozolic** [morpheusthewhite/spicetify-themes#334]
On Windows 10, Recently Played icon on the left pane is missing.

![Kuvatõmmis 2021-04-26 095146](https://user-images.githubusercontent.com/25500346/116040717-0cbc8d00-a675-11eb-9777-239f3e423214.png)

 - OS: Windows 10 21H1
 - Spotify version 1.1.58.818
 - Spicetify version 1.2.1
 - Dribbblish

**Comment by ArashMaghsoodi** [comment]
Sometimes re-installing fixes everything. Have you tried re-installing Dribbblish or Spicetify or even Spotify?

**Comment by morpheusthewhite** [comment]
> Sometimes re-installing fixes everything. Have you tried re-installing Dribbblish or Spicetify or even Spotify?

@Aerozolic

**Comment by DatAres37** [comment]
I have the same issue on Linux. Sometimes the icon is showing up when you close Spotify and open it again, sometime it doesn't.

**Comment by TheCultLeader666** [comment]
Having this problem as well

**Comment by makerio90** [comment]
@DatAres37 same issue
