### ISSUE TITLE
Shuffle/Repeat icons missing color when activated

### ISSUE THREAD

**Issue by Aerozolic** [morpheusthewhite/spicetify-themes#335]
**Describe the bug**
Dracula theme seems to miss color for shuffle and reapeat buttons.

![Kuvatõmmis 2021-04-26 095357](https://user-images.githubusercontent.com/25500346/116041301-b8fe7380-a675-11eb-89a2-7c1946eac16b.png)

 - OS: Windows 10 21H1
 - Spotify version 1.1.58.818
 - Spicetify version 1.2.1
 - Dribbblish

**Comment by morpheusthewhite** [comment]
@katawajojo

**Comment by katawajojo** [comment]
oh man, that's embarrassing. I'm really not sure how I missed that, but there's a pull request up with the fix.

#340 

I'm so sorry D:
