### ISSUE TITLE
Large Album Image class

### ISSUE THREAD

**Issue by baszin** [morpheusthewhite/spicetify-themes#338]
I would like to have a rounded Album image in the bottom right of the screen instead of a square. How is the class called in the .css file? I'm pretty sure I can do it alone but I don't know how the class is called.

For reference, I'm talking about the album image under the friends activity
![lol](https://user-images.githubusercontent.com/64983641/116727896-74f8cf00-a9e5-11eb-9cdd-0f7fade5d0e4.jpg)

(The theme is DribbblishDynamic)

**Comment by UrSok** [comment]
It's: cover-image

You can find the name yourself by enabling dev tool by using the command spicetify enable-devtool and then inspecting app trough dev tools.

**Comment by khanhas** [comment]
@morpheusthewhite You should turn on Discussion and move questions/ideas like these to it. And leave Issues for bug/issue report only.

**Comment by morpheusthewhite** [comment]
This should actually be on Spectrum

**Comment by khanhas** [comment]
Spectrum will be down very soon. They're out of business because of Github's Discussion

**Comment by morpheusthewhite** [comment]
It will be in August, so it can still be used for some time. I also personally don't like very much the idea of using GitHub discussion. This is why I was thinking of creating a subreddit, where it is easier to create discussions involving the community
