### ISSUE TITLE
[DribbblishDynamic] Text unreadable with some colors

### ISSUE THREAD

**Issue by jimmyli56** [morpheusthewhite/spicetify-themes#342]
Describe the bug
On yellow album covers, the theming makes it impossible to read the text on the progress bar

To Reproduce
1. Play any music with a yellow album cover
2. Hover over the progress bar

Expected behavior
Elapsed time text should be readable.

Screenshots
![image](https://user-images.githubusercontent.com/27116171/117106075-178db680-ad34-11eb-86eb-fa4891c46f5f.png)

Specifics :
 - OS: Windows 10 Pro
 - Spotify version 1.1.58.820.g2ae50076
 - Spicetify version 1.2.1
 - Theme used: DribbblishDynamic

**Comment by JulienMaille** [comment]
Please share a track that reproduce this issue

**Comment by jimmyli56** [comment]
https://open.spotify.com/show/3pXx5SXzXwJxnf4A5pWN2A?si=5nobe0aWRnugjXGsa_FL0Q

**Comment by JulienMaille** [comment]
Thanks, please try latest commit

**Comment by jimmyli56** [comment]
![image](https://user-images.githubusercontent.com/27116171/117212743-96740500-adaf-11eb-96da-c1b4cddf7491.png)
That fixed it. Thank you!
