### ISSUE TITLE
[DribbblishDynamic] Tooltips unreadable

### ISSUE THREAD

**Issue by DatAres37** [morpheusthewhite/spicetify-themes#343]
**Describe the bug**
Tooltips are (almost) unreadable when hovering over them. The song/color doesn't matter.

**To Reproduce**
1. Hover over the playlist images on the left side, an artist, an album name etc.

**Expected behavior**
A light tooltip font for the dark theme and a dark one for the white theme.

**Screenshots**

![spi-dark](https://user-images.githubusercontent.com/45577653/117489999-c5c87480-af5d-11eb-8bf9-045a80906711.png)
![spi-white](https://user-images.githubusercontent.com/45577653/117490001-c6610b00-af5d-11eb-84cf-28ccf5f197ae.png)

**Logs**

```console
Uncaught TypeError: Cannot read property 'length' of undefined
    at zlink.bundle.js:495
    at zlink.bundle.js:495
    at zlink.bundle.js:495
    at zlink.bundle.js:495
    at zlink.bundle.js:495
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/css/buddy-list.css.map: 
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/buddy-list.bundle.js.map: 
```

**Specifics (please complete the following information):**
 - OS: Manjaro Linux
 - Spotify version 1.1.56.595.g2d2da0de
 - Spicetify version v1.2.1
 - Theme name DribbblishDynamic dark

**Comment by JulienMaille** [comment]
See #342, make sure you work with latest commits

**Comment by DatAres37** [comment]
I just downloaded the theme again to make sure, but the problem persists. No issues with the normal Dribbblish theme.

I also don't have the issue mentioned in #342, the tooltip on the progress bar works as expected, but most of the other tooltips don't. The tooltips have the background of the generated colour, but the font should be white, not black:
![grafik](https://user-images.githubusercontent.com/45577653/118136278-7964b500-b3f3-11eb-8ff7-5149cab05e05.png)

Can a KDE theme somehow interfere with a spicetify theme?

My config:
```
[AdditionalOptions]
experimental_features        = 0
lyric_force_no_sync          = 0
radio                        = 0
visualization_high_framerate = 0
extensions                   = dribbblish-dynamic.js
custom_apps                  = genius
fastUser_switching           = 0
home                         = 0
lyric_always_show            = 0
song_page                    = 0

[Setting]
spotify_path            = /opt/spotify
prefs_path              = /home/user/.config/spotify/prefs
current_theme           = DribbblishDynamic
color_scheme            = dark
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    =
check_spicetify_upgrade = 0
overwrite_assets        = 1

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
```

**Comment by morpheusthewhite** [comment]
Did you run again the commands in the README?

**Comment by gordon-z** [comment]
Having same issue, tried latest commit as well but problem persists. After modifying the C:\Users\Gordon\.spicetify\Themes\DribbblishDynamic\user.css to latest commit, I ran spicetify update followed by spicetify apply, but nothing changed. Screenshot attached below.
![dribbblishDynamic](https://user-images.githubusercontent.com/43506099/118154824-867aa780-b3e5-11eb-892d-45e862e9fad9.png)
[usercss.txt](https://github.com/morpheusthewhite/spicetify-themes/files/6473737/usercss.txt)

**Comment by DatAres37** [comment]
> Did you run again the commands in the README?

The install commands? Yes

**Comment by gordon-z** [comment]
#tooltip,
.Tooltip {
    box-shadow: 0 0 4px rgba(0, 0, 0, 0.2) !important;
    border-radius: 4px !important;
    background-color: var(--modspotify_indicator_fg_and_button_bg);
    color: var(--modspotify_main_bg);
    padding: 10px 10px;
    
    backface-visibility: hidden;
    transform: translateZ(0);
    backdrop-filter: blur(20px);
}

I found it, the root cause is color: var(--modspotify_main_bg); I changed it to color: var(--modspotify_secondary_fg); and it's now clearly visible.

**Comment by JulienMaille** [comment]
No side effect on other tooltips?

**Comment by gordon-z** [comment]
Looks good for the tooltips I've tested so far. All of the left pane, friend activity, and personal profile work well.

Here is an example screenshot: 
![dribbblishDynamicWorking](https://user-images.githubusercontent.com/43506099/118178222-b20b8b00-b401-11eb-8fbe-876c297ee4cd.png)

**Comment by JulienMaille** [comment]
What about tooltips from topbar items and the progressbar's one?

**Comment by gordon-z** [comment]
![topbar](https://user-images.githubusercontent.com/43506099/118182413-fbaaa480-b406-11eb-9b63-f81404b51a7f.png)
![progressbar](https://user-images.githubusercontent.com/43506099/118182415-fbaaa480-b406-11eb-91a1-44a9e2a13fcc.png)
