### ISSUE TITLE
having trouble backing up app files

### ISSUE THREAD

**Issue by Salutiferous** [morpheusthewhite/spicetify-themes#346]
It keeps on saying "Cannot backup app files. Reinstall Spotify and try again." and i dont know what im meant to do
I downloaded spicetify v1.2.1 on windows and when i typed "spicetify backup apply enable-devtool\" it comes with "Cannot backup app files. Reinstall Spotify and try again." and although i reinstalled spotify adn deleted all the files it still happens.
![image](https://user-images.githubusercontent.com/83878084/117546621-e7108a00-b05d-11eb-8601-ec863e8d7535.png)

**Comment by morpheusthewhite** [comment]
This is not related to the themes, sorry. Open a discussion on khanhas's spicetify repository
