### ISSUE TITLE
Accidentaly hide the side bar, how do i restore it?

### ISSUE THREAD

**Issue by riskirills66** [morpheusthewhite/spicetify-themes#348]
I try to uninstall and reinstall specify, but the sidebar still hidden.
I try to restore the backup and reinstall the theme, but the sidebar is still hidden and I don't know what to do to unhide them.

**Comment by morpheusthewhite** [comment]
For which theme?

**Comment by crypticC0der** [comment]
how did u hide it?

**Comment by ajhawkings** [comment]
Is this due to the new re-sizable sidebar?

**Comment by riskirills66** [comment]
> Is this due to the new re-sizable sidebar?

Sorry, this is was Dribblish not Dribblish 2.0
