### ISSUE TITLE
[DribblishDynamic] Dark

### ISSUE THREAD

**Issue by rohanmrb** [morpheusthewhite/spicetify-themes#351]
Can the author please help me with the extension used to get the percentage next to the name of each song observed in the [DribblishDynamic] Dark theme preview image (color-match-bg) file
Thank you so much 
![color-match-bg](https://user-images.githubusercontent.com/60000863/118108012-1a0ba280-b3fd-11eb-8b3e-c18513afd10a.gif)

**Comment by JulienMaille** [comment]
It was removed in https://github.com/morpheusthewhite/spicetify-themes/commit/8a8516dd6df96c27bc6811335fd2afdf0915ed03 because people did not like it.

**Comment by rohanmrb** [comment]
Thank you @JulienMaille
