### ISSUE TITLE
Samourai Theme in Dribbblish does not properly display Popup Text or Song Time

### ISSUE THREAD

**Issue by mamamia-exe** [morpheusthewhite/spicetify-themes#352]
When you bring your mouse over the playback slider the time left in the song and the current position of the song is not visible, popup notifications which are supposed to display text are also blank. 

 - OS: Windows 10 
 - Spotify 1.1.58.820.g2ae50076
 - Spicetify 1.2.1
 - Dribbblish

**Comment by morpheusthewhite** [comment]
@spoutn1k

**Comment by collips** [comment]
having the same issue
