### ISSUE TITLE
[Bug] Spicetify appears black and unfunctional 

### ISSUE THREAD

**Issue by hewnly** [morpheusthewhite/spicetify-themes#355]
Spicetify appears black and you can't click anything. This happened when Spotify was updating its client.

To Reproduce
1. Spotify updates
2. Open Spicetify
3. Black screen appears

Expected behavior
open Spicetify and enjoy

Actual Behavior
black screen and cant click or see anything

**Screenshots**
![bug](https://user-images.githubusercontent.com/68442981/118357997-65a78300-b59a-11eb-9e12-f44dcb74e7ea.png)

Logs
![Untitled](https://user-images.githubusercontent.com/68442981/118358106-eebeba00-b59a-11eb-9231-590c0278306b.png)

 - OS: Windows 10
 - Spotify version: i don't know i cant see the version its irresponsive
 - Spicetify version: 1.2.1
 - Theme name: DribbblishDynamic

**Comment by hewnly** [comment]
I tried "spicetify apply" when i checked a similar thread on this repo but it still doesn't work

i also created a folder after zlink/css and created a user.css (following the dribbblish theme) but it still doesnt work

**Comment by hewnly** [comment]
i also used the SpotifyNoControl.exe in the wiki. is it part of the problem???

**Comment by khanhas** [comment]
https://github.com/khanhas/spicetify-cli/releases/tag/v.2.1.0

**Comment by hewnly** [comment]
thank you for the reply! it works- without the themes! thank you nonetheless!
