### ISSUE TITLE
Dribblish theme not displaying as expected

### ISSUE THREAD

**Issue by Geeekoid** [morpheusthewhite/spicetify-themes#357]
Colour theming works but it looks nothing like as expected. Happened after updating spicetify.

**To Reproduce**
1. Upgraded spicetify to latest
2. Reinstalled spotify
3. Standard Dribblish setup script for windows
4. Spicetify apply

Config:
[Patch]

[Setting]
check_spicetify_upgrade = 0
current_theme           = Dribbblish
color_scheme            = purple
inject_css              = 1
spotify_launch_flags    = 
spotify_path            = C:\Users\Cameron Dolan\AppData\Roaming\Spotify
prefs_path              = C:\Users\Cameron Dolan\AppData\Roaming\Spotify\prefs
replace_colors          = 1
overwrite_assets        = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions  = webnowplaying.js|dribbblish.js
custom_apps = 

; DO NOT CHANGE!
[Backup]
version = 1.1.58.820.g2ae50076

**Expected behavior**
Appearance should match the standard dribblish purple theme

**Screenshots**
![image](https://user-images.githubusercontent.com/44703001/118372442-888d6380-b5a9-11eb-8c7c-d532d56eae3a.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.59.712.g54f36e5d-a
 - Spicetify version 2.1.0
 - Theme name Dribblish

**Comment by UrSok** [comment]
https://github.com/khanhas/spicetify-cli/releases/tag/v2.1.0
