### ISSUE TITLE
Themes Compatibility Check for recent UI change

### ISSUE THREAD

**Issue by SaruDesu** [morpheusthewhite/spicetify-themes#358]
Due to the recent changes in the UI design of Spotify, I think there should be a thorough check on every theme for their compatibility. 
For example, the JarvisBot has some issues on the search bar as the asset was renamed from .Search_Input into .x-833-searchInput. And I think there are more issues to find out, not only in JarvisBot.

Edit: For now, I am using SpicetifyDefault with my custom color scheme because because of the issue I mention in the example above.

**Comment by SaruDesu** [comment]
After examining the code of SpicetifyDefault there is a fix for the disappearing searchbar.
`/* Topbar visibility bug */
.main-topBar-topbarContent:not(.main-topBar-topbarContentFadeIn)>* {
    opacity: unset !important;
}
.main-entityHeader-topbarContent:not(.main-entityHeader-topbarContentFadeIn)>* {
    opacity: 0 !important;
}
`

**Comment by morpheusthewhite** [comment]
I think basically all the themes need to be adapted for the new UI. 

But at the moment that is not the plan, also because many users are still using the old interface. Furthermore that would mean a huge update of the repository by all its mantainers, which appears to be unfeasible.
