### ISSUE TITLE
Gradianto isn't the same as the screens 

### ISSUE THREAD

**Issue by Maxcension** [morpheusthewhite/spicetify-themes#36]
Hello,
I installed the Gradiento theme but it doesn't look like the screens.
Gradiento in my spotify:
![2020-01-06 19_32_32-Window](https://user-images.githubusercontent.com/10364593/71839610-dcd22a80-30bb-11ea-9554-f09b78c0b46f.png)
I didn't touch anything in the color.ini or user.css.
Thanks!

**Comment by morpheusthewhite** [comment]
Maybe you forgot to run `spicetify apply`
