### ISSUE TITLE
Migrate all themes to new spotify ui.

### ISSUE THREAD

**Issue by Milo123459** [morpheusthewhite/spicetify-themes#360]
Hello.

All themes should be migrated to the new UI, in a roll-out type style. 

As in, new branch, and then, in a few months, when the new UI is normalized - merge it into stable. This would mean people have time to migrate, and would also give the maintainers enough time.

If you have a Discord, I'd love to chat with you and about how I can help out. Just to get into some further details.
I'll be happy to help out.

**Comment by morpheusthewhite** [comment]
@JulienMaille @khanhas what do you think about this? 

It will probably require a lot of time and effort doing it; basically, it means changing the entire repository. The other option I was thinking of is opening a new one for the new themes.

@Milo123459 you can contact me at morpheusthewhite#0260

**Comment by Milo123459** [comment]
Okay. I still think personally migrating all is a better idea.

**Comment by UrSok** [comment]
> The other option I was thinking of is opening a new one for the new themes.
I think this is a good idea.

**Comment by yougotwill** [comment]
My current PR https://github.com/morpheusthewhite/spicetify-themes/pull/345 is compatible with the old UI but I have updated it in my own repo https://github.com/yougotwill/Koushi. Will upload the changes once a decision has been made here.

**Comment by Milo123459** [comment]
Ok, came up with a proposal. 
Make a branch: `v2` - with all themes migrated to thew new UI. Once all are in place, merge it at same time in like July, so everyone has had time to migrate to the new spotify.

**Comment by xerta555** [comment]
Hello everyone.
I'm using the Elementary theme which is not compatible with the new Spotify interface.

I tried to compare the selectors in the different CSS of the different themes available that were initially made for the previous interface, i see that the HTML structure and CSS rules have not changed much between the previous version and the new one. Maybe i'm wrong, but for me it's mostly the CSS selectors that have changed names.

As for the repository issue, i advise to put the new versions of the themes in a new branch which would be defined by default, while keeping the old versions of themes in another branch.
I think arranging things this way would be more consistent for everyone.

**Comment by JulienMaille** [comment]
Migrating a skin basically means restarting from scratch

**Comment by Milo123459** [comment]
> Migrating a skin basically means restarting from scratch

Yeah I guess. You already have the colours tho

**Comment by ps13g** [comment]
> It will probably require a lot of time and effort doing it; basically, it means changing the entire repository. The other option I was thinking of is opening a new one for the new themes.
Is it possible that we can at least get the Dribbblish dynamic theme migrated since that seems to be one of the really popular ones out of the bunch?

**Comment by morpheusthewhite** [comment]
https://github.com/JulienMaille/spicetify-dynamic-theme @ps13g

**Comment by morpheusthewhite** [comment]
Here's a new idea I came up with: create another branch in this repository, `v2`, with no git history or files, where we add all the themes updated for the new UI. Once completed and stable we make it the master branch while renaming/moving the old master, which has the old themes, to another branch.

**Comment by Milo123459** [comment]
Sounds good. I'll start working on this. If you make the branch now, I can start committing to it. I'd need commit access tho.

**Comment by morpheusthewhite** [comment]
@Milo123459 you can open pull requests on the new branch `v2`. I opened a new issue (#368) tracking themes that need to be updated; if you want (as anyone else) you can contribute to themes with no maintainer specified.

**Comment by morpheusthewhite** [comment]
I closed this since the new issue summarizes all the needed info on the transition
