### ISSUE TITLE
Fix for the disappearing searchbar in new Spotify UI

### ISSUE THREAD

**Issue by physcrowley** [morpheusthewhite/spicetify-themes#361]
After examining the code of SpicetifyDefault there is a fix for the disappearing searchbar.
`/* Topbar visibility bug */
.main-topBar-topbarContent:not(.main-topBar-topbarContentFadeIn)>* {
    opacity: unset !important;
}
.main-entityHeader-topbarContent:not(.main-entityHeader-topbarContentFadeIn)>* {
    opacity: 0 !important;
}
`
_Originally posted by @SaruDesu in https://github.com/morpheusthewhite/spicetify-themes/issues/358#issuecomment-841766818_

>Edit after @Vialma7 's comment : this code just gets pasted into the `user.css` file for your theme. Any free line in the file will do.

This fix also worked for me on my WintergatanBlueprint theme. It was the one critical flaw affecting the usability of the new Spotify UI with Spicetify and I think this solves it (albeit only functionally, not by any beautiful integration with a theme).

**Comment by brenmadeit** [comment]
hi how should I add the code for this?

**Comment by Vialma7** [comment]
Thank you so much, I was trying to find out how to restore it and this worked so easily :)

> hi how should I add the code for this?
Go to the user.css file from your theme and just copy/paste there the code physcrowley shared.

**Comment by xerta555** [comment]
> After examining the code of SpicetifyDefault there is a fix for the disappearing searchbar.
> `/* Topbar visibility bug */ .main-topBar-topbarContent:not(.main-topBar-topbarContentFadeIn)>* { opacity: unset !important; } .main-entityHeader-topbarContent:not(.main-entityHeader-topbarContentFadeIn)>* { opacity: 0 !important; } `
> _Originally posted by @SaruDesu in [#358 (comment)](https://github.com/morpheusthewhite/spicetify-themes/issues/358#issuecomment-841766818)_
> 
> > Edit after @Vialma7 's comment : this code just gets pasted into the `user.css` file for your theme. Any free line in the file will do.
> 
> This fix also worked for me on my WintergatanBlueprint theme. It was the one critical flaw affecting the usability of the new Spotify UI with Spicetify and I think this solves it (albeit only functionally, not by any beautiful integration with a theme).

Personaly i just found the first rule you mentioned and it works immediatly through the CSS inspector, i didn't understand speciticly wich element the second CSS pattern target.

**Comment by morpheusthewhite** [comment]
Closing this issue as obsolete. New themes are currently being developed

**Comment by physcrowley** [comment]
Indeed!

I have been using the [V2 branch's stuff](https://github.com/morpheusthewhite/spicetify-themes/tree/v2) for at least a week and a half now and it is a much better experience than these patches on the obsolete themes.
