### ISSUE TITLE
Dribbblish extension not applying anymore

### ISSUE THREAD

**Issue by OBrien1510** [morpheusthewhite/spicetify-themes#363]
My Spotify reverted to the default this morning (happens every now and again) so I ran spicetify apply as I normally do but the spotify client just went completely blank. I thought there was some new update that messed stuff up so I reinstalled spotify and reinstally spicetify-cli and restored the themes and extensions. The themes now apply again fine but dribbblishdynamic.js doesn't seem to have any affect anymore. I copy and the most up to date code from git and copied it into my own file but that didn't affect anything. I also needed to comment out the very first line as it was throwing and error

`document.getElementById("popover-container").style.height = 0;`

I was getting null reference exception although that doesn't look to be a huge issue.

I can see that the .js file has been imported when I expect the spotify client and all the code is there, it just doesn't seem to have any affect. I also disabled caching.

Here is my config

[Setting]
current_theme           = DribbblishDynamic
color_scheme            = dark
replace_colors          = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\Hugh\AppData\Roaming\Spotify
prefs_path              = C:\Users\Hugh\AppData\Roaming\Spotify\prefs
inject_css              = 1
spotify_launch_flags    = 

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
fastUser_switching           = 0
home                         = 0
lyric_always_show            = 0
radio                        = 0
song_page                    = 0
visualization_high_framerate = 0
extensions                   = dribbblish-dynamic.js
experimental_features        = 0
lyric_force_no_sync          = 0
custom_apps                  = 

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.59.712.g54f36e5d

And this is the result

![image](https://user-images.githubusercontent.com/29002870/118618346-6c611080-b7bb-11eb-84af-2eafeefa801c.png)

There might have been a major update to the spotify client recently in which case this would probably make sense. Now that I look again, the basic themes (like Nord-Dark that I was running before) Looks slightly different so it might be that some html elements have changed after all?

 - OS: Windows 10
 - Spotify version: 1.1.59.712.g54f36e5d]
 - Spicetify version: e.g. 2.1.0]

**Comment by morpheusthewhite** [comment]
You need to use the old spicetify-cli, please read https://github.com/morpheusthewhite/spicetify-themes/blob/master/README.md#spicetify-community-themes
