### ISSUE TITLE
Dribbblish theme not working

### ISSUE THREAD

**Issue by Petee464** [morpheusthewhite/spicetify-themes#365]
When I apply the Dribbblish theme, only the colors apply to spotify.

I wanted it to be curvy and aligned better

![image](https://user-images.githubusercontent.com/84384294/118638986-b48e2c00-b7d7-11eb-9932-62fff1b6ca80.png)

**Logs**
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
dribbblish.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at dribbblish.js:2
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2317941)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2320525)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1755322
    at Ia (https://xpui.app.spotify.com/vendor~xpui.js:29:2587570)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2611422)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2804750)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2557078)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2611201)
    at Ts (https://xpui.app.spotify.com/vendor~xpui.js:29:2595972)
    at ys (https://xpui.app.spotify.com/vendor~xpui.js:29:2594894)
c @ vendor~xpui.js:29
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
4vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
5vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
​ Ads: HPTO HTML DFP Template: No iframe found for third party click tracking.
​ Ads: HPTO HTML DFP Template: No iframe found for third party click tracking.
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/773.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Specifics (please complete the following information):**
 - OS: Win 64
 - Spotify version: 1.69.712.g54f36e5d 
 - Spicetify version: 1.1.59.712.g54f36e5d 
 - Theme name: Dribbblish

**Comment by riskirills66** [comment]
I have this problem after installing the new spicetify 2.1 version.

**Comment by morpheusthewhite** [comment]
Please look at the README https://github.com/morpheusthewhite/spicetify-themes/blob/master/README.md, you need previous spicetify version and old UI for these themes to work
