### ISSUE TITLE
DribbblishDynamic update to v2

### ISSUE THREAD

**Issue by morpheusthewhite** [morpheusthewhite/spicetify-themes#377]
Update DribbblishDynamic to v2

**Comment by ajhawkings** [comment]
@JulienMaille Didn't you make this [here](https://github.com/JulienMaille/dribbblish-dynamic-theme)? 
Could this be included in the v2 branch in this repo?

**Comment by JulienMaille** [comment]
It's much easier for me to maintain my own repo and pick any changes coming from original Dribbblish.

**Comment by morpheusthewhite** [comment]
@JulienMaille do you still want to push your theme in the new branch? Because I think we should switch to v2 soon (around the middle of July) as most of the people are now using the new Spotify UI

**Comment by JulienMaille** [comment]
I use GitHub release to notify updates. I don't think I can do this if we have more than one theme on a repo
