### ISSUE TITLE
Where do I find `SpotifyNoControl.exe`?

### ISSUE THREAD

**Issue by DracTheDino** [morpheusthewhite/spicetify-themes#392]
It is mentioned in this section: https://github.com/morpheusthewhite/spicetify-themes/tree/v2/Dribbblish#hide-window-controls
There is also a broken link on the text `instruction1`.

**Comment by jiznon** [comment]
Its in the install location of Dribbblish. Eg. C:\Users\USERNAME\.spicetify\Themes\Dribbblish

**Comment by morpheusthewhite** [comment]
I think probably khanhas forgot to add it and/or will do it soon. In the meantime you can use the `.exe` from the `master` branch

**Comment by ImCheesecake** [comment]
Is it just me who can't get the SpotifyNoControl.exe to run? Nothing happens when I run it

**Comment by jiznon** [comment]
> Is it just me who can't get the SpotifyNoControl.exe to run? Nothing happens when I run it

Same here actually. I have to run Spotify from normal shortcut, then run SpotifyNoControl. This removes the top right buttons.

**Comment by EmstallZ** [comment]
Try using this version of SpotifyNoControl: https://github.com/SaifAqqad/AHK_SpotifyNoControl

If you have issues with Spotify not starting automatically when running `SpotifyNoControl.exe`, you can manually set the path to the Spotify shortcut or installation (As mentioned in the readme).

**Comment by morpheusthewhite** [comment]
I added it in the `_Extra` folder
