### ISSUE TITLE
Dribbblish V2 no default playlist icon

### ISSUE THREAD

**Issue by Sleepdealr** [morpheusthewhite/spicetify-themes#393]
**Describe the bug**
Doesn't give a default image or text for new playlists or playlist folders

**To Reproduce**
1. Create a new playlist or playlist folder but don't choose a photo for it or add any songs

**Expected behavior**
Should give a default image or text
I believe this worked before in V1

**Screenshots**
![](https://cdn.discordapp.com/attachments/718573098877583422/849668483833659392/unknown.png)

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version 1.1.60.672.g6ad9c215-a
 - Spicetify version 2.2.3
 - Dribbblish - nord-dark

**Comment by ps13g** [comment]
Was Dribblish actually updated to V2 yet?

**Comment by ps13g** [comment]
> @ps13g
> 
> Yep!
> https://github.com/morpheusthewhite/spicetify-themes/tree/v2/Dribbblish

Thank you I downloaded the Dribbblish but on MacOS I am running into issues with the code the entire app turns white and does not work after the application of the theme @khanhas

**Comment by Sleepdealr** [comment]
@ps13g 
Did you update both Spotify and Spicetify? You also have to switch to the V2 branch to get the updated theme

**Comment by ps13g** [comment]
> @ps13g
> Did you update both Spotify and Spicetify? You also have to switch to the V2 branch to get the updated theme

I have both updated to the most recent version and I downloaded the V2 branch and replaced all the themes but it still will not work

**Comment by Sleepdealr** [comment]
@ps13g 
Do you get any errors when you try to update the theme?
Also, did you run the required commands for Dribbblish to work?

**Comment by ps13g** [comment]
> @ps13g
> Do you get any errors when you try to update the theme?
> Also, did you run the required commands for Dribbblish to work?

Yea I did everything like a usually did for the older version of Dribbblish by going into the config changing the theme to the one i want and then I would put the commands in. I got no errors in the process either

**Comment by Sleepdealr** [comment]
@ps13g
I think you should open a separate issue instead of doing this here. Not really sure how to help you, sorry.

**Comment by morpheusthewhite** [comment]
@ps13g also make sure you have the latest Spotify and `spicetify` version (>=v2)

**Comment by ps13g** [comment]
> @ps13g also make sure you have the latest Spotify and `spicetify` version (>=v2)

Yea so in order for it to work I had to uninstall both Spotify and Spicetify (even though both were updated to the latest version) and I reinstalled everything possible and it managed to work at the end

**Comment by Tekunalogy** [comment]
I am having the same issue. Any solution to this issue? I have everything updated and even switched to the v2 branch. For me this happens for folders and playlists have no icon at all. The picture shows a folder that is expanded in the sidebar.

- OS: Windows
- Spotify version 1.1.62.583.gdac868ed-a
- Spicetify version 2.4.0
- Theme: Dribbblish - nord-dark

<img width="800px" src="https://user-images.githubusercontent.com/16601274/123505100-f9e11d00-d611-11eb-9303-f6df55ec7ef2.png" />
