### ISSUE TITLE
Dribbblish theme gone

### ISSUE THREAD

**Issue by hotsno** [morpheusthewhite/spicetify-themes#400]
What happened to some of the Dribbblish themes? I think I was using one called dracula but I no longer see it

**Comment by hotsno** [comment]
I see it looks like a bunch of stuff had to be redone due to a Spotify UI update or something. I'd really love it if the Dracula theme could be remade for the new version

**Comment by morpheusthewhite** [comment]
> I see it looks like a bunch of stuff had to be redone due to a Spotify UI update or something. I'd really love it if the Dracula theme could be remade for the new version

Yes, it's due to the last big Spotify update. We are migrating themes, but some of the color schemes may be left out.
