### ISSUE TITLE
Branch Naming

### ISSUE THREAD

**Issue by afonsojramos** [morpheusthewhite/spicetify-themes#410]
This is not exactly a bug, but it is leading to some confusion over at the spicetify repo.

I would suggest two things:
* Renaming the branches to `master` being the Spicetify v2 and the Spicetify v1 themes to be on the `legacy` branch, just like in `spicetify-cli`, i.e. Spicetify v2 = `master` & Spicetify v1 = `legacy`.
* Changing the default branch to v2 branch, which with the above will still be `master`.

What do you think @morpheusthewhite?

**Comment by afonsojramos** [comment]
Maybe this can be postponed to after the theme migration though.

**Comment by morpheusthewhite** [comment]
> This is not exactly a bug, but it is leading to some confusion over at the spicetify repo.
> 
> I would suggest two things:
> * Renaming the branches to `master` being the Spicetify v2 and the Spicetify v1 themes to be on the `legacy` branch, just like in `spicetify-cli`, i.e. Spicetify v2 = `master` & Spicetify v1 = `legacy`.

This is actually what will be done when the migration ends (approximately when the milestone deadline is reached)

**Comment by afonsojramos** [comment]
Oh, okay, sorry for troubling then. Thanks!
