### ISSUE TITLE
Windows Functions showing

### ISSUE THREAD

**Issue by BarnacledSquid** [morpheusthewhite/spicetify-themes#412]
**Describe the bug**
Windows minimize, fullscreen and close button showing

**To Reproduce**
1. Open spotify

**Expected behavior**
Windows functions hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/85329935/122628504-bcecc600-d0f9-11eb-9ded-95c88397e724.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console

```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.61.583.gad060c66-a
 - Spicetify version 2.2.6
 - Dribbblish

**Comment by morpheusthewhite** [comment]
Use spotify no control executable. It is not present yet on the `v2` branch but you can try to use the one on the master branch

**Comment by morpheusthewhite** [comment]
@khanhas did you avoid pushing `SpotifyNoControl.exe` for some specific reason?

**Comment by khanhas** [comment]
@morpheusthewhite Can you push it in root folder? Dribbblish might be not the only theme can benefit from it.

**Comment by ccrsxx** [comment]
@morpheusthewhite @khanhas I tried to run SpotifyNoControl.exe, but Spotify won't open. It just shows a flickering blank icon in the taskbar for a sec, and it disappears. 
Specifics:
OS: Windows 10
Spotify version 1.1.62.583.gdac868ed-a
Spicetify version 2.5.0
Dribbblish

**Comment by morpheusthewhite** [comment]
Added it to `_Extra` folder
