### ISSUE TITLE
Something went wrong, try to reload the page

### ISSUE THREAD

**Issue by Lochie123** [morpheusthewhite/spicetify-themes#413]
**Describe the bug**
Downloaded the newest version of Spotify and Spicetify, however when I open spotify it says "something went wrong, please reload the page. THis also happens on the web player.

**Comment by morpheusthewhite** [comment]
If it also happens on the web player then I guess the problem is not due to Spicetify or to the themes. Try cleaning browser cache. It may also be produced by some connection errors.
