### ISSUE TITLE
Dribbblish was supposed to show some microphone logo on the left side of spotify 

### ISSUE THREAD

**Issue by ObamaGamingKfc69** [morpheusthewhite/spicetify-themes#415]
I don't know if it's an issue, I generally don't know. But in the the left side "bar" of spotify it was supposed, as shown in the picture: https://github.com/morpheusthewhite/spicetify-themes/blob/v2/THEMES.md   --- I'm using a beach-sunset theme, and it's supposed to show some microphone and Reddit logo.

If it's not a issue or mistake, excuse me for not knowing Spicetify, and I'm extremely sorry about wasting your time.

**Comment by giannilabella** [comment]
It's [Lyrics Plus](https://github.com/khanhas/spicetify-cli/tree/master/CustomApps/lyrics-plus), a spicetify custom app like the reddit one showing above.

To install, just run: 
```bash
spicetify config custom_apps lyrics-plus
spicetify apply
```
