### ISSUE TITLE
Provide font stack

### ISSUE THREAD

**Issue by flying-sheep** [morpheusthewhite/spicetify-themes#42]
The Elementary theme looks weird, because I don’t have “Raleway” installed.

![grafik](https://user-images.githubusercontent.com/291575/75542247-b4154400-5a1f-11ea-96df-76c999bcbd68.png)

It would be nice to update all fonts stacks to be “FontName, sans-serif”. That way they’d use my system font.

**Comment by morpheusthewhite** [comment]
But if you try to install the font does it work?

**Comment by flying-sheep** [comment]
Sure.

**Comment by morpheusthewhite** [comment]
Then I don't think we really need to change it

**Comment by flying-sheep** [comment]
I just went into the devtools to figure out which fonts are used … things could really be more user friendly. Be it by providing a font stack or by listing the fonts next to the theme in the wiki or both.

**Comment by morpheusthewhite** [comment]
Yes, listing in the README of theme the needed font is much more feasible than changing the font in the theme, I think

I'll soon update the Contribution section of the README to suggest to add the needed font

**Comment by flying-sheep** [comment]
Cool thank you!
