### ISSUE TITLE
Theme Won't Load

### ISSUE THREAD

**Issue by EllisKopcho** [morpheusthewhite/spicetify-themes#427]
Hello! I followed a tutorial and everything, and in terminal, it said that spicetify worked, however, when spotify opened, nothing was changed, except for the volume/timeline bar having some gray behind them. Is there a way to fix this? The theme I used was Onepunch, and I'll put a photo below. 
<img width="877" alt="Screen Shot 2021-06-26 at 5 56 54 PM" src="https://user-images.githubusercontent.com/83428164/123529715-e54f6400-d6a7-11eb-8ae6-5dc76fec2aae.png">

**Comment by GeoT151** [comment]
I've heard spicetify is getting a bigfix, although idk if this already happened. Many people are experiencing the same problem as well. If the theme isn't applied then you don't need to do anything, but if it is then I suggest to do spicetify restore on powershell

**Comment by EllisKopcho** [comment]
Thanks! I'm on mac tho, so I dont think I can use powershell.

**Comment by CharlieS1103** [comment]
@EllisKopcho I mean you probably know this but I'm having trouble telling if you're joking, but just use terminal lol.

**Comment by DatAres37** [comment]
If you're using the new Spotify UI (>v1.1.56) and Spicetify >v2 you  have to use themes from the v2 branch apparently

**Comment by EllisKopcho** [comment]
@CharlieS1103 Huh, no, I'm not, and I did use terminal, sorry, I'm not that good with these kinds of things, and thanks @DatAres37!! I'll try doing that.
