### ISSUE TITLE
Dribbblish theme doesn't apply

### ISSUE THREAD

**Issue by MyBigFan2** [morpheusthewhite/spicetify-themes#428]
**Describe the bug**
Spotify doesn't apply Dribbblish theme after following the instructions

**To Reproduce**
1. Follow installation instructions from README.md in Dribbblish
2. "spicetify apply" in Powershell
3. Spotify remain the same

**Expected behavior**
Dribbblish Theme to be applied

**Screenshots**

**Logs**
Log:
![image](https://user-images.githubusercontent.com/27133275/123533925-dde19680-d74b-11eb-9631-3781dfe0694b.png)
Config:
![image](https://user-images.githubusercontent.com/27133275/123533974-26994f80-d74c-11eb-9ff2-690e536ae1ba.png)

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version 1.1.61.583.gad060c66
 - Spicetify version 2.4.0
 - Dribbblish

**Comment by khanhas** [comment]
Read README page.

**Comment by MyBigFan2** [comment]
I did follow all of the instructions correctly if I am not mistaken. Is my Spotify version the problem? I have seen videos showing how to do this and they can apply the theme to the newer xpui gui.

**Comment by khanhas** [comment]
Check one more time where did you get your theme, v2 branch or master branch?

**Comment by MyBigFan2** [comment]
Ah that seems to be the issue, I missed the v2 branch... It's working now after downloading from the v2 branch. Thanks and sorry for wasting your time on my stupid mistake! >.<
