### ISSUE TITLE
How do I minimize the sidebar ?

### ISSUE THREAD

**Issue by salahmak** [morpheusthewhite/spicetify-themes#430]
Hi, I'm using the Dribbblish theme with the base color scheme, but in the screenshot shows in THEMES.md it shows the sidebar minimized, but for me it is always maximized and won't get minimized if I drag it with the mouse.

To clarify more, here is the screenshot shows in THEMES.md:
![image](https://user-images.githubusercontent.com/49586511/123559167-e5c02b80-d789-11eb-82a4-fcdd7b31c6b2.png)

Here is a screenshot of my spotify:
![image](https://user-images.githubusercontent.com/49586511/123559181-05575400-d78a-11eb-8d36-94d25cc0363c.png)

**Comment by khanhas** [comment]
Please read the theme README one more time. You didn't add the script file, that's why sidebar is not interactable.

**Comment by salahmak** [comment]
@khanhas i did read the README and it doesn't say anything about scripts, I did this:


![image](https://user-images.githubusercontent.com/49586511/123693502-ad7f2280-d847-11eb-905c-a0f4f4435b8d.png)

**Comment by salahmak** [comment]
nvm just found what README u r talking about

thanks
