### ISSUE TITLE
Dribbblish v2 is not functioning correctly in 1080p display 

### ISSUE THREAD

**Issue by charindithjaindu** [morpheusthewhite/spicetify-themes#436]
I recently applied Dribbblish to my windows pc via autoscript. Then it looks like this

![image](https://user-images.githubusercontent.com/75799963/123825261-66169600-d91c-11eb-882f-c6dcc56812d6.png)

**Specifics (please complete the following information):**
 - OS:Windows 10 Pro
 - Spotify version :1.1.62.583.gdac868ed-a
 - Spicetify version v2
 - Dribblish

**Comment by DimitarSamarov07** [comment]
Can reproduce on Debian 11

**Comment by HeyItsJono** [comment]
Same exact issue on my end with Win 10 Enterprise and Spotify 1.1.61.583.gad060c66. I can resize the "Friends" menu on the right-hand side but not sidebar on the left.

**Comment by khanhas** [comment]
1. Can you check in config file that dribbblish.js is present in `extensions` field?
2. Console log would be helpful for me to debug.

**Comment by DimitarSamarov07** [comment]
Didn't have the dribbblish.js included, now that I do have it, it's even more broken. [Screenshot 1](https://imgur.com/a/wKTz3oo) and [Screenshot 2](https://i.imgur.com/VlRp6Fj.png) (pfp and friend names blurred out).
My config file for spicetify: [here](https://pastebin.com/9GY9s8iP). Used the autoinstall script mentioned [here](https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/README.md). 

Not sure which console output do you need. Do you need sth from Spicetify or ? Client outputs nothing helpful when ran through the console, except for 3 dbus warnings which were there either way.

**Comment by khanhas** [comment]
@DimitarSamarov07 Is your Spotify v1.1.55? Minimium requirement is v1.1.56.

**Comment by DimitarSamarov07** [comment]
> @DimitarSamarov07 Is your Spotify v1.1.55? Minimium requirement is v1.1.56.

Version from the repos is 1.1.55.498, but that seems to be the latest one for my OS, even tho I am using the official Spotify debian repo.

**Comment by khanhas** [comment]
http://repository.spotify.com/pool/non-free/s/spotify-client/

**Comment by DimitarSamarov07** [comment]
@khanhas Aight, that seems to have fixed most of the issues, it's strange why apt doesn't acknowledge the existence of the new version, but a manual install did the job. I still notice a major visual bug with the Dribbblish menu, here's a [screenshot](https://imgur.com/a/z7MCEUf). The menu seems to be going out of the app window, making it basically unusable,

**Comment by morpheusthewhite** [comment]
> @khanhas Aight, that seems to have fixed most of the issues, it's strange why apt doesn't acknowledge the existence of the new version, but a manual install did the job. I still notice a major visual bug with the Dribbblish menu, here's a [screenshot](https://imgur.com/a/z7MCEUf). The menu seems to be going out of the app window, making it basically unusable,
> 
> EDIT: Forgot to mention that happens when I click on the Dribbblish menu, the green thing to the right seems to be the submenu, for some reason when I click on Dribbblish, the text goes black, making it the same color as the background

Refer to https://github.com/morpheusthewhite/spicetify-themes/issues/467 for that

**Comment by charindithjaindu** [comment]
![image](https://user-images.githubusercontent.com/75799963/133871324-c62643a6-a355-447e-aeae-b37cc8abfbea.png)
