### ISSUE TITLE
DribbblishDynamic Theme sometimes doesn't show "Recently Played" icon

### ISSUE THREAD

**Issue by sicr0** [morpheusthewhite/spicetify-themes#439]
Sometimes when launching Spotify, in the left sidebar, instead of the "Recently Played" icon, appears simply the section name. 

I couldn't find a way to reproduce the bug. It happens from 10% to 20% of the times I launch Spotify. It seems more likely to happen (even though I'm not sure) when Spotify is launched for the first time. 

Instead of the "Recently Played" title, the icon with the clock should appear.

![Screenshot_20210701_030647](https://user-images.githubusercontent.com/49662650/124075498-52058e00-da1b-11eb-8cbe-79dc3c54264b.png)

```
Uncaught Error: sp://core-profile/v1/profiles responded with status 500
    at zlink.bundle.js:495
    at zlink.bundle.js:495
    at zlink.bundle.js:495
    at zlink.bundle.js:495
pubads_impl_2021062409.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
about:srcdoc:39 Uncaught TypeError: googletag.defineSlot is not a function
    at about:srcdoc:39
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/buddy-list.bundle.js.map: 
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/css/buddy-list.css.map: 
```

 - OS: GNU/Linux Manjaro KDE
 - Spotify version 1.1.56.595.g2d2da0de
 - Spicetify version 2.5.0-1
 - DribbblishDynamic Dark

**Comment by morpheusthewhite** [comment]
You are using the old theme with the new version of Spicetify. Use https://github.com/JulienMaille/dribbblish-dynamic-theme instead.

**Comment by sicr0** [comment]
Thanksss
