### ISSUE TITLE
[Dribbblish, Spicetify v2] Can't change sidebar width

### ISSUE THREAD

**Issue by Rohanite** [morpheusthewhite/spicetify-themes#443]
**Describe the bug**
When I try to resize the sidebar in Dribbblish nothing happens.

**To Reproduce**
1. Install Dribbblish
2. Click on sidebar
3. Try and drag mouse to change sidebar size

**Expected behavior**
The sidebar should have shrunk in width.

**Video**
https://user-images.githubusercontent.com/36016892/124354205-2dddc300-dc4e-11eb-880e-6ec02fc72dfb.mp4
(Cuz I recorded with Geforce Experience it recorded audio so turn off sound if ur in a quiet area)

(Couldn't get logs, devtools wouldn't enable)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.62.583.gdac868ed-a
 - Spicetify version 2.3.0
 - Theme name: Dribbblish

**Comment by morpheusthewhite** [comment]
Update Spicetify and reinstall the theme

**Comment by Rohanite** [comment]
Fixed it. I really should have though of that earlier.
