### ISSUE TITLE
Floating album cover gets covered by the player button bar

### ISSUE THREAD

**Issue by GRIMMboi** [morpheusthewhite/spicetify-themes#448]
When the album cover is in large format it gets covered by the player button bar when "youre listening"
 appears on dribbblish

Have the album art in large format. Listen to music on your phone while you have spotify on your pc open. The div covers the bottom of the album art.

The album art should move up when the div moves up.

https://imgur.com/VYxMUYc

 - OS: Windows 19043.1081
 - Spotify version  1.1.62.583
 - Spicetify version 2.5.0
 - Dribbblish

**Comment by morpheusthewhite** [comment]
Please add this to https://github.com/morpheusthewhite/spicetify-themes/issues/440
