### ISSUE TITLE
Dribbblish doesn't work after todays update

### ISSUE THREAD

**Issue by LatifSC** [morpheusthewhite/spicetify-themes#460]
Dribbblish doesn't work on 1.1.63.568. It stuck at startup. I can't even move the Spotify window.

![image](https://user-images.githubusercontent.com/68355853/125265885-f043fe80-e30d-11eb-9adc-f79861bbf5b2.png)

![image](https://user-images.githubusercontent.com/68355853/125265962-0225a180-e30e-11eb-97cc-011689c462cb.png)

**Logs**

I cant pull logs because i have AMD GPU so when i hit ctrl+shift+L it records driver log.

**Specifics (please complete the following information):**
 - OS: Windows 11 Pro Insider, Build: 22000.65
 - Spotify version 1.1.63.568.gda8cb5ac-a
 - Spicetify version 2.5.0
 - Theme name Dribbblish for V2

**Comment by SpiritLetsPlays** [comment]
Same thing for me. You can restore spotify to its normal theme by running "spicetify restore" in PowerShell for anyone that is wondering how to get it running again.

**Comment by KOBL1CK** [comment]
![image](https://user-images.githubusercontent.com/76731711/125327517-dfb27900-e34b-11eb-93ac-c39062f710b7.png)
Same thing with latest version and same theme
How to pull logs? (Nvidia GPU)

**Comment by jiznon** [comment]
Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
