### ISSUE TITLE
Spicetify is not showing

### ISSUE THREAD

**Issue by Idenix** [morpheusthewhite/spicetify-themes#461]
I installed Spicetify following a tutorial on youtube, followed each step but Spotify ends up looking like the screenshot below (i installed Dribbblish base, this the reason of the green screen)
![image](https://user-images.githubusercontent.com/22416425/125286749-6fd8ca00-e31c-11eb-93e5-95741039102c.png)

**Comment by SpiritLetsPlays** [comment]
Should be because of the new Spotify Update that dropped today, will hopefully be fixed soon.

**Comment by bruellkeafer** [comment]
this style of Layout reminds me of the Spotify Windows-Store Version wich is not supported. Are u shure u r using the right verison (u need the Version from the official Spotify Website)

**Comment by jiznon** [comment]
Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.

**Comment by antonioalvasan** [comment]
Same issue. I have already checked that i have the Spotify Website version, and I think i did everything fine. I have read that it may cause this issue to Spotify Premium users, which is my case.

**Comment by JumpingPig332** [comment]
> Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.

How?

**Comment by jiznon** [comment]
> > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> 
> How?

Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.

**Comment by JumpingPig332** [comment]
> > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > 
> > 
> > How?
> 
> Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.

I mean how do you install older versions, sorry

**Comment by jiznon** [comment]
> > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > 
> > > 
> > > How?
> > 
> > 
> > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> 
> I mean how do you install older versions, sorry

Download it and install it.

**Comment by JumpingPig332** [comment]
> > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > 
> > > > 
> > > > How?
> > > 
> > > 
> > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > 
> > 
> > I mean how do you install older versions, sorry
> 
> Download it and install it.
From where

**Comment by JumpingPig332** [comment]
> > > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > > 
> > > > > 
> > > > > How?
> > > > 
> > > > 
> > > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > > 
> > > 
> > > I mean how do you install older versions, sorry
> > 
> > 
> > Download it and install it.
>>
> > From where

@jiznon bump

**Comment by damzbl** [comment]
> > > > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > > > 
> > > > > > 
> > > > > > How?
> > > > > 
> > > > > 
> > > > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > > > 
> > > > 
> > > > I mean how do you install older versions, sorry
> > > 
> > > 
> > > Download it and install it.
> > > From where
> 
> @jiznon bump

Search "spotify 1.1.62" and download from uptodown. Its that easy.

**Comment by morpheusthewhite** [comment]
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/453. Please check the issues before opening the same one.
