### ISSUE TITLE
Theme won't load?

### ISSUE THREAD

**Issue by somofoji** [morpheusthewhite/spicetify-themes#468]
I used spicetify a few months ago but stopped using it cuz i had to reset my pc. I'm trying to use spicetify again but the themes wouldn't load so I uninstalled and reinstalled spotify and spicetify and followed a tutorial on spicetify but the theme still won't load.
When I start spotify I get a blank screen and the color of the theme.
![image](https://user-images.githubusercontent.com/47472933/125837507-a9b04764-e917-42ef-bc5a-61dfb26c294d.png)
![Screenshot_48](https://user-images.githubusercontent.com/47472933/125837525-7b11abec-a38d-4dbf-b5e0-0f0bd202db37.png)

**Comment by adi170-alt** [comment]
Yea same, I think that it stated yesterday Today I followed this [vid](https://www.youtube.com/watch?v=rRhratE0KNk&t=137s) again, but it is still  the same

**Comment by mchlbataller** [comment]
Same issue I've encountered so far. Would like to diagnose it via DevTools but it seems like I couldn't find any free time, but I'm looking for some time later.

**Comment by morpheusthewhite** [comment]
This appears to be a problem with Dribbblish itself. It is also discussed here https://github.com/morpheusthewhite/spicetify-themes/issues/453.
