### ISSUE TITLE
SpotifyNoControl.exe executes Spotify but doesn't remove controls right after

### ISSUE THREAD

**Issue by Anitoxx** [morpheusthewhite/spicetify-themes#479]
**Describe the bug**
Launching Spotify with 'SpotifyNoControl.exe' doesn't remove the controls right after.

**To Reproduce**
1. Go to 'spicetify-themes-legacy' folder
2. Click on '_Extra' folder
3. Click on 'SpotifyNoControl' folder
4. Execute 'SpotifyNoControl.exe'

**Expected behavior**
SpotifyNoControl.exe launches Spotify and removes controls right after

**Specifics:**
 - OS: Windows 10
 - Spotify version 1.1.38.558.g4b100958
 - Spicetify version v1.2.1
 - Theme name : Dribbblish

**Comment by Wawwior** [comment]
Same Problem over here!

**Comment by morpheusthewhite** [comment]
Try using this one 

https://github.com/SaifAqqad/AHK_SpotifyNoControl

**Comment by morpheusthewhite** [comment]
I updated the README, now you have 2 alternatives in case the executable in the folder does not work
