### ISSUE TITLE
Spicetify

### ISSUE THREAD

**Issue by stellqrr** [morpheusthewhite/spicetify-themes#486]
**Describe the bug**
When installing spicetify nothing works it just makes spotify a white blank screen and when installing the dribbblish them same thing.

**To Reproduce**
1. Download spicetify
2. See that its a blank white program
3. Apply dribbblish theme.
4. See blank colored program

**Expected behavior**
I expected a themed spotifty

**Screenshots**
![image](https://user-images.githubusercontent.com/72888549/127577137-6cbfb1ef-c403-4fd2-ae62-b77a5c6fe9ad.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window (failed to do so)
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: Windows 10 21H1
 - Spotify version 1.1.64.561.g71bd09eb
 - Spicetify version 2.5.0
 - Theme name Dribblish

**Comment by ExiledEye** [comment]
I have the same problem.

**Comment by morpheusthewhite** [comment]
Look at the pinned issue please, this is a duplicate
