### ISSUE TITLE
pauseAdd-Type : The term 'pauseAdd-Type' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by 0xChicken** [morpheusthewhite/spicetify-themes#487]
So i have added the themes to the theme folder and this message comes:

pauseAdd-Type : The term 'pauseAdd-Type' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pauseAdd-Type -AssemblyName PresentationFramework
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pauseAdd-Type:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

Update:

Found out i didnt extract the themes first and the copy them but now my spotify is all white :/ i have to re-download spotify for it to work again.

Update2:

Now i found out of the white part but when i load Dribbblish the screen of spotify is all green.

**Comment by morpheusthewhite** [comment]
Look at the pinned issue
