### ISSUE TITLE
Unreadable text in Coral color scheme

### ISSUE THREAD

**Issue by pWoLiAn** [morpheusthewhite/spicetify-themes#490]
There is some text here.Its black and not readable.Is there a way to change that particular text color only.this is Sleek>Coral theme btw

![image](https://user-images.githubusercontent.com/49567139/127981068-df7ddbf8-48fd-4b52-89f2-383c5f95f1f4.png)

**Comment by morpheusthewhite** [comment]
@harbassan

**Comment by harbassan** [comment]
It seems completely functional to me and in the right colors in the most recent version of the theme. If you haven't already install the most current files for the theme and the issue should be fixed.
