### ISSUE TITLE
Unable to install Dribblish theme 

### ISSUE THREAD

**Issue by yohann69** [morpheusthewhite/spicetify-themes#491]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish
2. Click on copy `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/morpheusthewhite/spicetify-themes/v2/Dribbblish/install.ps1" | Invoke-Expression`
3. Past it in powershell

**Expected behavior**
One click install of the theme

**Logs**
```
PS C:\Users\yohan> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/morpheusthewhite/spicetify-themes/v2/Dribbblish/install.ps1" | Invoke-Expression
Downloading themes package:
Invoke-WebRequest : 404: Not Found
At line:10 char:1
+ Invoke-WebRequest "https://github.com/morpheusthewhite/spicetify-them ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Specifics (please complete the following information):**
 - OS: windows 11
 - Spotify version: 1.1.62.583
 - Spicetify version: lastest
 - Theme name: Dribbblish

**Comment by adityas-31** [comment]
Same issue.

**Comment by Zaidanadli** [comment]
same here

**Comment by morpheusthewhite** [comment]
Use `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/morpheusthewhite/spicetify-themes/master/Dribbblish/install.ps1" | Invoke-Expression` instead

**Comment by Zaidanadli** [comment]
still not work for me 
`Invoke-WebRequest : 404: Not Found                                                                                      At line:10 char:1                                                                                                       + Invoke-WebRequest "https://github.com/morpheusthewhite/spicetify-them ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by morpheusthewhite** [comment]
Try again now with the new commands in the README, I just merged a PR
