### ISSUE TITLE
Sidebar text offscreen with Dreary theme

### ISSUE THREAD

**Issue by SrirachaSupreme** [morpheusthewhite/spicetify-themes#493]
Dreary sidebar text is offscreen. All I did was install it with the deeper color scheme, and it came like this. Using the latest version of spicetify, spotify vers. 1.1.62.583.gdac868ed-a.
![image](https://user-images.githubusercontent.com/81733335/128561283-70c565f0-cabd-47a6-9fb2-0b552f350f92.png)

**Comment by morpheusthewhite** [comment]
@CharlieS1103

**Comment by CharlieS1103** [comment]
@SrirachaSupreme This is most likely due to you not having Sidebar config enabled. The readme file of dreary has steps to enable it

**Comment by SrirachaSupreme** [comment]
Oh, alright! Thank you @CharlieS1103.

**Comment by CharlieS1103** [comment]
@SrirachaSupreme No problem dude, always nice to see people actually using my theme lol.
