### ISSUE TITLE
Dribbblish/DribbblishDynamic no picture in playlist folders

### ISSUE THREAD

**Issue by juniorafael** [morpheusthewhite/spicetify-themes#495]
I checked everything and they are all with recent versions
![image](https://user-images.githubusercontent.com/59783420/128761606-502b90e1-b0a2-4c84-99a7-d12e78165700.png)

No option to change image appears.
![image](https://user-images.githubusercontent.com/59783420/128760773-6e221098-f0f1-471d-8324-dc47e979e3a7.png)

**Comment by morpheusthewhite** [comment]
This is probably due to some unsolved issues on spicetify-cli. The recent Spotify updates caused several problems

**Comment by morpheusthewhite** [comment]
@juniorafael can you check if the issue has been solved by the most recent spicetify updates?

**Comment by brenmadeit** [comment]
please let me know if there is fix
mine happened too, im using newest spicetify ver 2.6

**Comment by morpheusthewhite** [comment]
Update both Spotify and Spicetify to the latest version, I am not experiencing it
