### ISSUE TITLE
Facebook Friends Incorrectly Displayed

### ISSUE THREAD

**Issue by aiden04** [morpheusthewhite/spicetify-themes#497]
**Describe the bug**
Facebook friends incorrectly displayed

**Expected behavior**
I expected my Facebook friends section too look like the screenshots provided

**Screenshots**
![image](https://user-images.githubusercontent.com/9298623/129078699-f059dfd5-ba0e-445f-aae5-480324dd8bc8.png)

**Specifics**
 - OS: [Windows 10 21h1]
 - Spotify version [1.1.65.643.g2d707698]
 - Spicetify version [2.5.0]
 - Theme name [Dribbblish(nord-light)]

**Comment by morpheusthewhite** [comment]
How do they look like instead?

**Comment by morpheusthewhite** [comment]
I'm not sure how they should look like, in the screenshots the friends tab is collapsed so they are not visible
