### ISSUE TITLE
Fluent theme looks broken when applied

### ISSUE THREAD

**Issue by miyukowo** [morpheusthewhite/spicetify-themes#504]
**Describe the bug**
The Fluent theme looks broken when I apply it.

**To Reproduce**
1. Install Spotify (on Flatpak)
2. Install spicetify-cli
3. Download and apply the theme
4. Restart Spotify

**Expected behavior**
Theme looks normal as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/40559090/129946868-1c07056d-41df-46b2-b766-e44482dc9945.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

Console logs
![image](https://user-images.githubusercontent.com/40559090/129946001-58974a2a-7c41-46b0-8970-5f1f78d591c9.png)

**Specifics (please complete the following information):**
 - OS: Linux Manjaro 5.10.59-1-MANJARO (KDE Plasma 5.22.4)
 - Spotify version 1.1.55.498.gf9a83c60
 - Spicetify version 2.6.0
 - Theme name: Fluent

**Comment by williamckha** [comment]
Try installing this updated version of the theme: https://github.com/williamckha/spicetify-fluent
Might fix some of the issues with the sidebar and player on the old Spotify client (v1.1.56 and older).

**Comment by miyukowo** [comment]
Thank you for the fix, that did it.

![Screenshot_20210821_112548](https://user-images.githubusercontent.com/40559090/130310410-9c71c0e8-effa-4080-95ed-ab0441626806.png)
