### ISSUE TITLE
Fluent theme minor bugs

### ISSUE THREAD

**Issue by pWoLiAn** [morpheusthewhite/spicetify-themes#510]
**Describe the bug**
Mainly i found two bugs:
(i) a small white dot above friend activity
(ii) repeat current song and repeat playlist have the same icon(in the screenshot i have set it as repeat current song but as you can see, its the same icon as for repeat playlist

**Screenshots**
![image](https://user-images.githubusercontent.com/49567139/130321935-042c0c08-e5c3-475a-947e-626eb13e401e.png)

**Specifics (please complete the following information):**
 - OS: [e.g. windows11]
 - Spotify version [1.1.62.583.gdac868ed
 - Spicetify version [e.g. 2.5.0]
 - Fluent dark

**Comment by williamckha** [comment]
I'm working on new styling for the friend activity panel and will add a repeat song icon soon

**Comment by williamckha** [comment]
Try installing this updated version of the theme: https://github.com/williamckha/spicetify-fluent
Not sure if it will fix the issues with the friend activity, but it should include the new repeat song icon + some other miscellaneous fixes

**Comment by morpheusthewhite** [comment]
@pWoLiAn update spicetify, update the theme and check if the error persists

**Comment by pWoLiAn** [comment]
Seems great now. Closing the issue.
