### ISSUE TITLE
Issue with Fluent theme

### ISSUE THREAD

**Issue by TheStupidOneHere** [morpheusthewhite/spicetify-themes#517]
I've tried using the fluent theme multiple times but it always gives my weird results, Am I doing something wrong?

> version = 1.1.66.580.gbd43cbc9
> with    = 2.5.0-itsmeow-patch4

![image](https://user-images.githubusercontent.com/71955577/130725659-7a77db11-b311-4452-b0be-288fe0a072f7.png)
(The white boxes are not part of the issue, just censors)

**Comment by morpheusthewhite** [comment]
Did you enable fluent.js?

**Comment by TheStupidOneHere** [comment]
Yeah, tried multiple times

**Comment by morpheusthewhite** [comment]
Try using spicetify 2.6.0

**Comment by williamckha** [comment]
This is due to the latest version of Spotify using different CSS mappings which has broken a lot of spicetify themes (see https://github.com/khanhas/spicetify-cli/issues/845)
Try downgrading Spotify to >= v1.1.64 until a spicetify patch is released

**Comment by HuyHung1408** [comment]
> I use https://spotify.en.uptodown.com/windows/versions
> You can also try running these commands to prevent future spotify updates, but they haven't seemed to work for me:
> 
> icacls "%localappdata%\Spotify\Update" /reset /T
> del /s /q "%localappdata%\Spotify\Update"
> mkdir "%localappdata%\Spotify\Update"
> icacls "%localappdata%\Spotify\Update" /deny "%username%":W

thank you, it did works. It still appear the update but when you updating it, it actually do nothing, still stay on the old ver

**Comment by morpheusthewhite** [comment]
@TheStupidOneHere @HuyHung1408 can you check if the problem persists with the latest Spicetify?

**Comment by HuyHung1408** [comment]
No problems in the lastest one ( v2.6.7 ???), my Spotify still works after updating to Spicetify v2.6.7.

> @TheStupidOneHere @HuyHung1408 can you check if the problem persists with the latest Spicetify?
