### ISSUE TITLE
Playlist images on left side bar bug

### ISSUE THREAD

**Issue by alessiocelentano** [morpheusthewhite/spicetify-themes#522]
**Describe the bug**
Playlist images on left side bar are stretched.

**Expected behavior**
Normal image size or no image at all.

**Screenshot**
![spotify_theme_screenshot](https://user-images.githubusercontent.com/48618881/131339069-fe26443f-505d-4e1e-a770-a95ec1ab885b.png)

**Specifics :**
 - OS: Arch Linux

 - Spotify version: 1.1.56.595.g2d2da0de
 - Spicetify version: v2.6.0
 - Theme name: Ziro

**Comment by morpheusthewhite** [comment]
@schnensch0

**Comment by morpheusthewhite** [comment]
Update to the latest version
