### ISSUE TITLE
Fluent BUG 

### ISSUE THREAD

**Issue by geti123** [morpheusthewhite/spicetify-themes#528]
**Describe the bug**
You can see the bug in the photo, and i've got the font too 

**Screenshots**
https://imgur.com/a/93M0aj9

**Logs**
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
vendor~xpui.js:29 Uncaught (in promise) TransportError: Cannot authenticate disconnected transport.
    at U._authenticate (vendor~xpui.js:29)
    at U.authenticate (vendor~xpui.js:29)
    at e.request (vendor~xpui.js:29)
    at e.resolveConfig (vendor~xpui.js:29)
    at t.<anonymous> (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at Object.next (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at new Promise (<anonymous>)
    at Oe (vendor~xpui.js:29)
    at t.fetch (vendor~xpui.js:29)
    at vendor~xpui.js:29
    at vendor~xpui.js:29
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at u (https://xpui.app.spotify.com/vendor~xpui.js:29:2062756)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2065038)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1517483
    at Ia (https://xpui.app.spotify.com/vendor~xpui.js:29:2346873)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2370725)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2556856)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2316381)
    at Rs (https://xpui.app.spotify.com/vendor~xpui.js:29:2370504)
    at Ts (https://xpui.app.spotify.com/vendor~xpui.js:29:2355275)
    at gs (https://xpui.app.spotify.com/vendor~xpui.js:29:2354197)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2316653
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2556856)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2316381)
    at _i (https://xpui.app.spotify.com/vendor~xpui.js:29:2316598)
    at gi (https://xpui.app.spotify.com/vendor~xpui.js:29:2316533)
    at hs (https://xpui.app.spotify.com/vendor~xpui.js:29:2353190)
    at Object.enqueueSetState (https://xpui.app.spotify.com/vendor~xpui.js:29:2321346)
    at bE.E.setState (https://xpui.app.spotify.com/vendor~xpui.js:29:2491529)
    at bE.componentDidMount (https://xpui.app.spotify.com/xpui.js:1:532305)
 
==========================================================
 - OS: Windows
 - Spotify version Lastest
 - Spicetify version Lastest
 - Fluent

**Comment by gmr458** [comment]
Same here
![spotify dark](https://user-images.githubusercontent.com/53343401/132145338-d4a5108b-9caf-4811-944e-cc7a8d5c48f0.png)
![spotify light](https://user-images.githubusercontent.com/53343401/132145342-3c49dae6-79bc-458b-98f9-65ed631b592b.png)

**Comment by mohad12211** [comment]
same here, linux with latest version

**Comment by TheHenkka** [comment]
`user.css` and `fluent.js` are broken. Some elements have been deleted or renamed

In `user.css` change this:

```
.main-repeatButton-button {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_off_24_regular.svg');
  background-color: var(--spice-subtext) !important;
  height: 22px !important; 
}

.main-repeatButton-on {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_24_filled.svg');
  background-color: var(--spice-text) !important;
  height: 22px !important;
}

.main-repeatButton-on[aria-label="Disable repeat"] {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_once_24_filled.svg') !important;
}

.main-shuffleButton-button {
  -webkit-mask-image: url('./phosphor-icons/shuffle.svg');
  background-color: var(--spice-subtext) !important;
  height: 22px !important;
}

.main-shuffleButton-on {
  -webkit-mask-image: url('./phosphor-icons/shuffle-bold.svg');
  background-color: var(--spice-text) !important;
  height: 22px !important;
}

.main-repeatButton-on:after,
.main-shuffleButton-on:after {
  content: none !important;
}


.main-trackList-rowPlayPauseButton {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_play_24_filled.svg');
  background-color: var(--spice-text) !important; 
  padding: 0px !important;
}

.main-trackList-rowPlayPauseButton[aria-label="Pause"] {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_pause_16_filled.svg') !important;
  background-color: var(--spice-text) !important;
}
```

to this:

```
.main-repeatButton-button[aria-label="Enable repeat"]{
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_off_24_regular.svg');
  background-color: var(--spice-subtext) !important;
  height: 22px !important; 
}

.main-repeatButton-button{
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_24_filled.svg');
  background-color: var(--spice-text) !important;
  height: 22px !important;
}

.main-repeatButton-button[aria-label="Disable repeat"]{
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_arrow_repeat_all_once_24_filled.svg');
  background-color: var(--spice-text) !important;
  height: 22px !important;
}


.main-shuffleButton-button {
  -webkit-mask-image: url('./phosphor-icons/shuffle.svg');
  background-color: var(--spice-subtext) !important;
  height: 22px !important;
}

.main-shuffleButton-button[aria-label="Disable shuffle"] {
  -webkit-mask-image: url('./phosphor-icons/shuffle-bold.svg');
  background-color: var(--spice-text) !important;
  height: 22px !important;
}


.gro_tSi7cwspepH0as03 {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_play_24_filled.svg') !important;
  mask-image: url('./fluentui-system-icons/ic_fluent_play_24_filled.svg') !important;
  background-color: var(--spice-text) !important; 
  padding: 0px !important;
}

.gro_tSi7cwspepH0as03[aria-label="Pause"] {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_pause_16_filled.svg') !important;  
  background-color: var(--spice-text) !important;
}
```

And in  `fluent.js` change this:

```
  waitForElement([
    ".main-rootlist-rootlistItemLink",
    "#spicetify-playlist-list"
  ], function() {
```
to this:
```
  waitForElement([
    ".main-rootlist-rootlistItemLink"
  ], function() {
```

**Comment by morpheusthewhite** [comment]
@williamckha

**Comment by hollowshiroyuki** [comment]
@TheHenkka the fix doesn't seem to fully work ? 🤔
![image](https://user-images.githubusercontent.com/35398794/132258574-b297663e-4fc0-4d8b-a9d3-d7e4e52dfaa6.png)

**Comment by geti123** [comment]
@TheHenkka can u give the .css and .js file ?

**Comment by TheHenkka** [comment]
@hollowshiroyuki Yeah looks like lot of element names have been changed. That only fixed sidebar folders and control bar.

@geti123 Here:
https://github.com/williamckha/spicetify-fluent/commit/da39293e01a8b7666ba365fd80772f3b99abc677

**Comment by williamckha** [comment]
I'm working on a fix, will push changes to https://github.com/williamckha/spicetify-fluent

**Comment by hollowshiroyuki** [comment]
@TheHenkka indeed, the js might need a fix too, the screenshot I sent doesn't show it but on scroll down and then back up on the playlists, the icons disapear...

**Comment by geti123** [comment]
@williamckha is working fine for now but the icons of playlist need to fix too https://imgur.com/a/MMVjUcy

**Comment by geti123** [comment]
https://imgur.com/a/S79GXO4 and butons to apply needs to be black XD

**Comment by williamckha** [comment]
This should fix most of the issues https://github.com/williamckha/spicetify-fluent/commit/553e25f8a9654419400910edf35b628ca769bf17
Thanks to @TheHenkka for the sidebar and player fixes.
@geti123 I haven't updated some of the class names (e.g. dialog boxes, podcast elements) just because there's too many to change. Scrolling through playlists on the sidebar is also still broken. There should be another release of spicetify with more updated CSS mappings coming soon, so I think we'll wait and see if future spicetify updates fix things before I fix the bugs myself

**Comment by luke-uppx** [comment]
is fixed this bug?

**Comment by HuyHung1408** [comment]
I stayed on the older version of Spotify and it still works well. I think you guys should downgrade to an older one. 
![image](https://user-images.githubusercontent.com/86362423/132798294-5b90cb98-b8bd-4bc4-a91d-965a05848995.png)

**Comment by s1kee** [comment]
> I stayed on the older version of Spotify and it still works well. I think you guys should downgrade to an older one.
> ![image](https://user-images.githubusercontent.com/86362423/132798294-5b90cb98-b8bd-4bc4-a91d-965a05848995.png)

what version are you on?

**Comment by HuyHung1408** [comment]
1.1.60.668.gff09d345

**Comment by HuyHung1408** [comment]
> > I stayed on the older version of Spotify and it still works well. I think you guys should downgrade to an older one.
> > ![image](https://user-images.githubusercontent.com/86362423/132798294-5b90cb98-b8bd-4bc4-a91d-965a05848995.png)
> 
> what version are you on?

1.1.60.668.gff09d345

**Comment by ccrsxx** [comment]
> > > I stayed on the older version of Spotify and it still works well. I think you guys should downgrade to an older one.
> > > ![image](https://user-images.githubusercontent.com/86362423/132798294-5b90cb98-b8bd-4bc4-a91d-965a05848995.png)
> > 
> > 
> > what version are you on?
> 
> 1.1.60.668.gff09d345

What spicetify version is this? I tried with the version you mentioned, got blank screen instead.

**Comment by HuyHung1408** [comment]
I think it is V2.2.2+

**Comment by ccrsxx** [comment]
> I think it is V2.2.2+

Thanks for the fast response lol, I'll try.

**Comment by ccrsxx** [comment]
> I think it is V2.2.2+

I tried it, and it's still broken. I guess I'll use the stock for a while till the fixes come.
![image](https://user-images.githubusercontent.com/55032197/133169352-e3d4a612-f40d-4062-9b6d-36951934cb16.png)

**Comment by HuyHung1408** [comment]
Oh, sorry if I can't help you

**Comment by ccrsxx** [comment]
> Oh, sorry if I can't help you

no probs, thanks anyway for trying to help me.

**Comment by luke-uppx** [comment]
Not fixed yet? When I lauch "spicetify apply" I get "Applying additional modifications:
error Cannot find symbol for Custom app React symbols"

**Comment by williamckha** [comment]
Most up to date version of Fluent can be found here: https://github.com/williamckha/spicetify-fluent 
Includes fixes for most bugs, make sure spicetify >= v2.6.3 is installed

**Comment by luke-uppx** [comment]
> Most up to date version of Fluent can be found here: https://github.com/williamckha/spicetify-fluent
> Includes fixes for most bugs and fixes issues with playlists in the sidebar, make sure spicetify >= v2.6.3 is installed

It works with latest spotify version 😍 Thanks

**Comment by JoaoPedroPierri** [comment]
![image](https://user-images.githubusercontent.com/58857531/134381974-ded4a7ec-293f-44ac-8c3b-b62be3e021bf.png)

Still not showing the pause button

**Comment by HuyHung1408** [comment]
> ![image](https://user-images.githubusercontent.com/58857531/134381974-ded4a7ec-293f-44ac-8c3b-b62be3e021bf.png)
> 
> Still not showing the pause button

What version are you on

**Comment by ccrsxx** [comment]
> ![image](https://user-images.githubusercontent.com/58857531/134381974-ded4a7ec-293f-44ac-8c3b-b62be3e021bf.png)
> 
> Still not showing the pause button

![image](https://user-images.githubusercontent.com/55032197/134809909-f6ce20ec-6673-4ea6-bb67-81c736677713.png)
The latest Spotify version works fine here. Make sure you have the latest version of spicetify and the fluent theme.
