### ISSUE TITLE
Ziro Theme: "playback-bar" position when playing on other device

### ISSUE THREAD

**Issue by Woosy** [morpheusthewhite/spicetify-themes#529]
**Describe the bug**
The "playback-bar" is missplaced when playing music on an other device (see following screenshot)

![image](https://user-images.githubusercontent.com/26418696/132366961-0301c441-ed81-49d4-b04e-5e6ae01f4a47.png)

**To Reproduce**
1. Open Spotify with Ziro theme on a computer
2. Play a song on your phone

**Expected behavior**

"playback-bar" should be like this:
![image](https://user-images.githubusercontent.com/26418696/132367322-28d73dfa-83dc-40cb-a033-2a77b2a94ee5.png)

**Specifics (please complete the following information):**
 - OS: MacOS
 - Spotify version: 1.1.67.586.gbb5ef64e-a
 - Spicetify version: 2.6.2
 - Theme name: Ziro

**Comment by Woosy** [comment]
This has to do with [the following styles](https://github.com/morpheusthewhite/spicetify-themes/blob/2585b6360b68452764fc25145f5cba1c75738fdf/Ziro/user.css#L510), if I set the bottom to 110px it's perfectly placed, but if I stop playing music on my phone the bar is too high

I don't know how to do something like a condition (whether I'm playing on another device or not)

**Comment by morpheusthewhite** [comment]
@schnensch0

**Comment by schnensch0** [comment]
this happens because the css map is unfinished atm
you can try to replace `.main-nowPlayingBar-container` with the parent of `.main-connectBar-connectBar` in your devtools
https://github.com/morpheusthewhite/spicetify-themes/blob/2585b6360b68452764fc25145f5cba1c75738fdf/Ziro/user.css#L515

**Comment by Woosy** [comment]
Issue fixed with latest spicetify.
