### ISSUE TITLE
Dribbblish FullScreen Mode does not refresh upon song change

### ISSUE THREAD

**Issue by thgilartlu** [morpheusthewhite/spicetify-themes#535]
**Describe the bug**
Title 
Dribbblish does not transition album art, title, info in while in fullscreen mode.

**To Reproduce**
1. Play Song
2. Enter FullScreen mode by pressing button in bottom right next to volume slider
3. Observe bug

**Expected behavior**
Album Art, Artist Info, Song Title do not change when song changes, additionally all elements will fade after ~5s (I'm assuming intended but can't figure out why)

**Screenshots**
While playing "Ultralight Beam - Kanye West":
![image](https://user-images.githubusercontent.com/71095679/132967256-f606e408-7740-412f-beaf-75eb5e774ff6.png)
While playing "Ultralight Beam - Kanye West" (After ~5s):
![image](https://user-images.githubusercontent.com/71095679/132967272-7648ebcb-093b-4a76-a1fc-9ca2bbb3015a.png)
While playing "Love Yourz - J.Cole" (After Ultralight Beam):
![image](https://user-images.githubusercontent.com/71095679/132967276-a4a757dc-4f5b-4138-8207-b80d5919caaf.png)

**Specifics (please complete the following information):**
 - OS: Windows 10 19041.1165
 - Dribbblish Base

**Comment by morpheusthewhite** [comment]
Update spicetify and Spotify and it should be fixed
