### ISSUE TITLE
Fluent Theme Error on Spotify startup

### ISSUE THREAD

**Issue by OscarArranz** [morpheusthewhite/spicetify-themes#549]
After setting Fluent theme on spicetify I get a window that shows a generic error and I can't use Spotify. I had previously installed Dribbblish without any problems.

### Steps to reproduce the behavior:
1. Set Dribbblish theme
2. Set Fluent theme

### Screenshots:
![image](https://user-images.githubusercontent.com/39172137/135155320-cbf400eb-f19e-4780-9a31-36348dd63f73.png)

### Logs:
```
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
xpui.js:1 Error: GET request to sp://offline/v1/connection failed with status code 404
```

## System Info
 - OS: 5.13.19-2-MANJARO 
 - Spotify version: 1:1.1.68.632-1
 - Spicetify version: 2.7.0
 - Fluent theme

**Comment by morpheusthewhite** [comment]
@williamckha

**Comment by morpheusthewhite** [comment]
You're not using the latest Spicetify

**Comment by OscarArranz** [comment]
> You're not using the latest Spicetify

I've updated Spicetify version to latest 2.6.6 but the error persists

**Comment by williamckha** [comment]
Try upgrading spicetify to v2.7.0

**Comment by OscarArranz** [comment]
> Try upgrading spicetify to v2.7.0

Upgraded to v2.7.0 but still the error persists, (I tried using a clean Spotify install).

**Comment by OscarArranz** [comment]
I fixed it, somehow my Spicetify config got corrupted and was persisting even after reinstalling and updating, however deleting it and regenerating it fixed the issue and I got Fluent theme correctly installed!

I'll close this issue now.
