### ISSUE TITLE
Playlists on the Dribbblish theme look weird

### ISSUE THREAD

**Issue by ImQrispy** [morpheusthewhite/spicetify-themes#551]
**Describe the bug**
There are backgrounds behind the names of the playlists that I'm fairly certain aren't supposed to be there. (They don't look nice if they are)
**To Reproduce**
Use Dribbblish (Sunset-Beach) theme. 

**Expected behavior**
No background behind the playlist names. It should have the little circle icon with the album covers and that's it.

**Screenshots**
![image](https://user-images.githubusercontent.com/91637751/135529654-51089c7f-1cfc-4fc2-8df5-04cb41127dc3.png)

**Logs**
![image](https://user-images.githubusercontent.com/91637751/135528999-9b3e837a-630c-490c-8879-10122ccbfa0a.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.68.632.g2b11de83
 - Spicetify version 2.6.7
 - Dribbblish (Sunset-Beach)

**Comment by fortoszone** [comment]
got the same problem here on mac

**Comment by ImQrispy** [comment]
updated to 2.7.0 problem still persists

**Comment by morpheusthewhite** [comment]
I am not able to reproduce the issue on Linux with spicetify 2.7.0 and spotify 1.1.68.632

**Comment by morpheusthewhite** [comment]
Make sure to update both spotify and spicetify and check if the error persists

**Comment by fortoszone** [comment]
![Screen Shot 2021-10-07 at 12 30 57](https://user-images.githubusercontent.com/13508492/136325555-8cd886da-f396-4291-80bd-0f6b6d892369.png)

@morpheusthewhite got the newer spotify version, still not working
and btw this issue also occurs on other theme like fluent

**Comment by ImQrispy** [comment]
The issue was occurring because I forgot to disable/remove the fluent.js extension, so if you're having this same issue then it may be because there is another extension active that is messing with your primary extension.
