### ISSUE TITLE
[Dribbblish] Timestamp tooltip not working

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [morpheusthewhite/spicetify-themes#552]
It only shows NaN:NaN0/3:49 (the remaining time is also not shown correctly....it's stuck at 3:49) 
![Screenshot_20210319](https://user-images.githubusercontent.com/70870070/135743905-fbd8bca1-abe0-4bd4-aee5-1c3211cb6e87.png)

**Comment by 1-minute-to-midnight** [comment]
Still not working

**Comment by DashCruft** [comment]
I have this issue too.

I tried everything but yet it doesn't work and shows NaN

Any solutions yet?

**Comment by jhilker1** [comment]
Also confirming this

**Comment by khanhas** [comment]
It was fixed in latest update. Please redownload the theme package to update your Dribbblish.
