### ISSUE TITLE
[Dribbblish] Blank Screen on latest spotify update

### ISSUE THREAD

**Issue by xFGhoul** [morpheusthewhite/spicetify-themes#556]
**Describe the bug**
running `spicetify apply` always gives me this blank screen

**To Reproduce**

1. Use Dribbblish on the latest spotify and spicetify (Any Theme)

**Expected behavior**
Theme loading

**Screenshots**
![Spotify_pHn3oCbxeD](https://user-images.githubusercontent.com/70284239/135915594-9248170e-d5e1-4dae-9983-73ad2adc62e2.png)

**Logs**
![Spotify_Xan1i846sk](https://user-images.githubusercontent.com/70284239/135915520-0a6c638f-2a16-476f-ba3a-a81185a25dd6.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.69.612.gb7409abc
 - Spicetify version: 2.6.7
 - Theme name: Dribbblish

**Comment by morpheusthewhite** [comment]
Update spicetify

**Comment by xFGhoul** [comment]
Thank you.
