### ISSUE TITLE
[Fluent] Shuffle & Repeat control not changing when toggling shuffle/repeat modes

### ISSUE THREAD

**Issue by lmpham1** [morpheusthewhite/spicetify-themes#560]
**Describe the bug**
When using Fluent theme, shuffle and repeat control appears the same regardless of the shuffle/repeat modes. In other words, there is no visual indication of what the current shuffle/repeat mode is.

**To Reproduce**
1. Install [Fluent](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent) theme as per the installation guide
2. Play any songs on Spotify, switching shuffle modes does not change the shuffle icon in the control bar. Same with repeat control icon.

**Expected behavior**
Visual indication when the repeat/shuffle mode is changed.

**Screenshots**
Expected (using Default theme to illustrate):
![image](https://user-images.githubusercontent.com/43410858/135961745-fb652e20-935a-4c6b-8935-ab9eed0326c5.png)

Current (with Fluent theme, Shuffle and Repeat are enabled, but not showing as such):
![image](https://user-images.githubusercontent.com/43410858/135961795-6db7c425-3a34-4b8e-8a08-dfbeeda99f97.png)

**Logs**
N/A

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.69.612.gb7409abc
 - Spicetify version: v2.7.0
 - Theme name: Fluent

**Comment by williamckha** [comment]
I'm unable to reproduce the issue. Are you using the latest version of Fluent? Bugs with icons not working in non-English languages should be fixed.

**Comment by lmpham1** [comment]
Hi, just fetched the latest version, and this issue seems to be fixed. Thanks! I also ran into another issue with the play button being completely white, but someone else already filed an issue for that, so I'm gonna close this one.
