### ISSUE TITLE
[Dribbblish] Can't scroll(or arrowkey) playlist

### ISSUE THREAD

**Issue by Crylia** [morpheusthewhite/spicetify-themes#573]
**Describe the bug**
I can't scroll my playlist so some playlists are unreachable, not even with the arrow keys.

**To Reproduce**
Fresh install with Spotify from newest Flatpak

**Expected behavior**
I should be able to scroll down my playlists

**Logs**
Add logs from console. To do that
Step 3 doesnt work for me, spotify restarted but i cannot open the devtools

**Specifics (please complete the following information):**
 - OS: Pop!_OS 21.10
 - Spotify 1.1.68.632.g2b11de83
 - Spicetify 2.7.1
 - Dribbblish

EDIT: I also tested it on my main machine running the same os but this time with the apt package.
APT-Source=http://repository.spotify.com stable/non-free amd64 Packages

**Comment by Crylia** [comment]
Can confirm it also happens with the Fluent theme.

**Comment by khanhas** [comment]
Did you add Patch lines in config file?
Check theme readme for their instruction.

**Comment by Crylia** [comment]
Pulling the latest changes fixed it for me

**Comment by Darelife** [comment]
Hey umm how did u fix it exactly? like i'm facing the same issue

**Comment by Darelife** [comment]
nvm, i just edited the user.css file and changed the value in this
```
.dribs-playlist-list {
    padding-bottom: 300px;
}
```
