### ISSUE TITLE
[FLUENT] Suggestion: Add option to show playlist names

### ISSUE THREAD

**Issue by NotIPlayForFun** [morpheusthewhite/spicetify-themes#574]
Hey,

on the playlist-sidebar it only shows the icons made up of song covers. I have a bunch of playlist saved, as do lots of people probably, that I don't know the icons of by heart. I love the fluent theme and it is my favourite, but this makes it very user-unfriendly for me, since I need to click through them to see the names.

I tried changing this, but it seems rather complicated since it involves the .css aswell as the .js files.

I think the theme would be greatly approved by at lease an option to show the playlist names, doesnt even have to look pretty imo, just so that those of us who want this feature have an option to use it :)

Thanks for reading , kind regards ^^

**Comment by sagars007** [comment]
Hey this is a really good idea and even I wanted it. I got some time to play around with the css and came up with this workaround. It's not the most good looking design imo, but it works! U can also resize the sidebar if needed just like the default theme. 

Following changes in user.css:

```
.Root__nav-bar {
  z-index: 1 !important;
  /*max-width: 85px !important; */
  height: calc(100% + 107px);
  padding-bottom: 127px;
}

.main-navBar-navBar {
  /* max-width: 85px !important; */
}

.main-rootlist-textWrapper {
  display: block;
  text-overflow: clip;
  text-shadow: 2px 2px 2px #000000;
}

.ellipsis-one-line{
  text-overflow: clip;

} 
```

https://imgur.com/a/FAhqZ2h

**Comment by NotIPlayForFun** [comment]
awesome, thank you ^^
