### ISSUE TITLE
[Fluent] (Dark) Resizing the friends bar on the right doesnt work

### ISSUE THREAD

**Issue by znicuuu** [morpheusthewhite/spicetify-themes#577]
I have Spotify open on half of the screen and normally I resize the friends to the smallest so it doesnt take up half of spotify. After switching from the Default Theme to the dark Fluent Theme the resizing doesnt work anymore and its always open. When trying to resize it only the Text is gone but the bar is still as big as it was before.

**Expected behavior**
The resizing of the friends list works normally

**Screenshots**
![image](https://user-images.githubusercontent.com/73033465/138146127-0b3c8a71-59d7-45aa-b4a3-9424cfb32fe6.png)

**Logs**
![image](https://user-images.githubusercontent.com/73033465/138146395-ba3801f3-2903-454f-9972-de8474e30639.png)

**Specifics (please complete the following information):**
 - OS: Windows 10 Pro
 - Spotify version: 1.1.70.610.g4585142b
 - Spicetify version: 2.7.1
 - Fluent: Dark

**Comment by TheCrafterGaming** [comment]
Just change this part in the user.css file:

`.main-buddyFeed-buddyFeedRoot,
.main-buddyFeed-buddyFeed {
  width: 280px;
  z-index: 0;
}`

to

`.main-buddyFeed-buddyFeedRoot,
.main-buddyFeed-buddyFeed {
  z-index: 0;
}`

The set width is what is not allowing you to change the friend activity size but I'm gonna warn you it does look a little janky if you go in between the smallest and regular size
