### ISSUE TITLE
[Dribblish] Song Queue Button not Displaying Icon

### ISSUE THREAD

**Issue by emekoi** [morpheusthewhite/spicetify-themes#587]
**Describe the bug**
When using Dribblish the song queue button does not display. The song queue is there and works as expected, but the SVG icon is not displayed. I haven't tried reproducing this with any other themes, but the issue goes away when the Dribblish extension is disabled, even if the Dribblish theme is enabled.

I was able to isolate the issue to this line of code [here](https://github.com/morpheusthewhite/spicetify-themes/blob/67cfad34cb5779b6a83820b17dd999c57b7d7cb4/Dribbblish/dribbblish.js#L110):
```js
waitForElement([
    ".Root__nav-bar .LayoutResizer__input, .Root__nav-bar .LayoutResizer__resize-bar input"
], ([resizer]) => {
    const observer = new MutationObserver(updateVariable);
    observer.observe(resizer, { attributes: true, attributeFilter: ["value"]});
    function updateVariable() {
        let value = resizer.value;
        if (value < 121) {
            value = 72;
            document.documentElement.classList.add("sidebar-hide-text"); // this line of code
        } else {
            document.documentElement.classList.remove("sidebar-hide-text");
        }
        document.documentElement.style.setProperty(
            "--sidebar-width", value + "px");
    }
    updateVariable();
});
```
it seems it hides this icon because the filter just hides all "small" svgs?

**Edit**
Adding this
```css
html.sidebar-hide-text .GlueDropTarget span {
    display: flex;
}
```
after [this](https://github.com/morpheusthewhite/spicetify-themes/blob/67cfad34cb5779b6a83820b17dd999c57b7d7cb4/Dribbblish/user.css#L372) rule seems to solve the issue but i'm not sure what other side effects this might have.
 
On a side note there seems to be an unrelated error that file `/images/tracklist-row-song-fallback.svg` does not exist (at least on my installation).

**To Reproduce**
1. install Dribblish as per the instructions in the README

**Expected behavior**
The song queue icon is displayed.

**Screenshots**
With `dribblish.js` loaded
![image](https://user-images.githubusercontent.com/9454576/139014498-b57b0098-deb5-4ce1-9b9a-8543356819ab.png)
Without
![image](https://user-images.githubusercontent.com/9454576/139015386-3df87951-0084-460f-a1d2-a3d284ac2cff.png)

**Logs**
![image](https://user-images.githubusercontent.com/9454576/139014721-5e10b120-1b93-4926-a782-ba680be81cdc.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: Spotify for Windows 1.1.70.610.g4585142b
 - Spicetify version: 2.7.0
 - Theme: Dribblish

**Comment by emekoi** [comment]
i just noticed there are some issues when the side bar is small as possible with the code i originally posted but the more specific rule does not have those issues.
![image](https://user-images.githubusercontent.com/9454576/139717252-3b5228bd-d90a-48c5-b04d-8d4aac4a7982.png)

**Comment by khanhas** [comment]
Fixed.
