### ISSUE TITLE
Not able to configure themes

### ISSUE THREAD

**Issue by emeraldqueen2703** [morpheusthewhite/spicetify-themes#590]
**im not able to configure themes or change it**
i installed the themes and dribbblish was applied, but then when i wanted to change the colour to nord dark, it shows the theme didnt exist

**Expected behavior**
Colour of theme to be changed to nord dark

![image](https://user-images.githubusercontent.com/75775120/139475769-a86de7fc-de10-4557-b268-3a3f23472d4b.png)

**Specifics (please complete the following information):**
 - OS: windows
 - Spotify version
1.1.71.560.gc21c3367
 - Spicetify version idk
 - Theme name -all

**Comment by morpheusthewhite** [comment]
You didn't follow instructions, the Dribbblish folder is missing in the spicetify folder

**Comment by emeraldqueen2703** [comment]
> You didn't follow instructions, the Dribbblish folder is missing in the spicetify folder

umm no i have it
![image](https://user-images.githubusercontent.com/75775120/139534515-9095269f-e667-499d-b58b-af6d3fe67b93.png)

**Comment by williamckha** [comment]
Take the Dribblish folder out of the spicetify-themes-master folder and copy it into the spicetify Themes folder

**Comment by emeraldqueen2703** [comment]
> Take the Dribblish folder out of the spicetify-themes-master folder and copy it into the spicetify Themes folder

ok thanks!
