### ISSUE TITLE
[FLUENT] I can't scroll to my playlist

### ISSUE THREAD

**Issue by soapsmellsnice** [morpheusthewhite/spicetify-themes#596]
Is there any way to solve this problem?
![awdawfffff](https://user-images.githubusercontent.com/93475261/139781635-a04b91c7-19ca-4dfa-97ea-8196003c337e.png)

**Comment by williamckha** [comment]
Did you add these two lines to the Patch section of your config-xpui.ini file?
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

**Comment by soapsmellsnice** [comment]
> 
> 
> Did you add these two lines to the Patch section of your config-xpui.ini file?
> 
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> ```

Thanks mate, problem solved
