### ISSUE TITLE
For Dribblish, Play & Pause buttons glitched

### ISSUE THREAD

**Issue by sebastianking39** [morpheusthewhite/spicetify-themes#597]
In Dribblish, the Play and Pause buttons are glitched

I just installed the theme nord-dark

it should only show one not this

![Screenshot 2021-11-02 193522](https://user-images.githubusercontent.com/63021947/139966316-60e0f740-79d5-45ea-a5c0-f3ff639bd24d.jpg)

System Info:
Windows 11
Spotify Version 1.1.71.560.gc21c3367
Spicetify Version 2.7.1
Theme: Dribblish

**Comment by lunadu321** [comment]
I had the same issue but I have fixed it now. Have you installed the Fluent theme as well? The extensions of dribbblish and fluent contradict each other, so if you want to use Dribbblish, uninstall or disable fluent.js.

**Comment by sebastianking39** [comment]
also how do u get lyrics

**Comment by lunadu321** [comment]
https://github.com/khanhas/spicetify-cli/wiki/Custom-Apps#lyrics-plus
https://github.com/khanhas/spicetify-cli/wiki/Extensions#pop-up-lyrics
The custom app is not working currently, we are waiting for a new release so for the moment try the latter one.

**Comment by sebastianking39** [comment]
how do i install?

**Comment by khanhas** [comment]
I can't replicate this.
Please update everything to the latest (Spotify, spicetify and dribbblish) and see if it's still a problem.

**Comment by iainawatson** [comment]
Hi, can confirm removing fluent solved this issue for me. Using the code:

`spicetify config extensions fluent.js-`
