### ISSUE TITLE
[FLUENT] Dark won't show playlist icons, home, library and search icons, and all control buttons 

### ISSUE THREAD

**Issue by thatcatfromspace** [morpheusthewhite/spicetify-themes#598]
**Bug**
The theme has installed seemingly well overall but most icons won't show up. Any help is really appreciated!
![image](https://user-images.githubusercontent.com/79753351/140016694-59e3207f-1266-4f03-bcda-89ee065ff1d6.png)

**To Reproduce**
- Install Spicetify with the Fluent Dark theme
- Open app

>Console log:
![image](https://user-images.githubusercontent.com/79753351/140016568-5e850b2c-cdb3-499a-8508-e0dc5b6634f3.png)

**Specifics :**
 - OS: Windows 7 x32
 - Spotify version: Spotify for Windows 1.1.71.560.gc21c3367
 - Spicetify version 2.7.1 x32
 - Fluent Dark

**Comment by soapsmellsnice** [comment]
Paste this in your (powershell) console 

`cd "$(spicetify -c | Split-Path)\Themes\Fluent"
Copy-Item fluent.js ..\..\Extensions
spicetify config extensions fluent.js
spicetify config current_theme Fluent color_scheme dark
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply`

**Comment by soapsmellsnice** [comment]
Paste this in your console 

> cd "$(spicetify -c | Split-Path)\Themes\Fluent"
> Copy-Item fluent.js ..\..\Extensions
> spicetify config extensions fluent.js
> spicetify config current_theme Fluent color_scheme dark
> spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
> spicetify apply
>

**Comment by thatcatfromspace** [comment]
![image](https://user-images.githubusercontent.com/79753351/140720355-7e6eeed8-86c4-4cf7-b230-502b80efb183.png)
Is there anything I should change with the directory? It won't run the first line individually either

**Comment by thatcatfromspace** [comment]
Thanks a ton for this, didn't notice this in the repo. Had changed the theme and color scheme in cofig.ini but forgot to inject the CSS assets. Thanks again!
