### ISSUE TITLE
[Dribbblish] Unreadable context menu

### ISSUE THREAD

**Issue by Thera-code** [morpheusthewhite/spicetify-themes#600]
When I click to open an items context menu the text as well as the background are completely black, making a lot of menus a pain to use.
![Scsh-3](https://user-images.githubusercontent.com/62468600/140590866-68c6c968-d273-473f-85ea-6f5e212455eb.png)
I found out that changing the main variable in the color.ini file also changes that text's color, but that those two are connected seems odd to me.

**To Reproduce**
1. Install Spicetify
2. Install spicetify themes
3. Install Dribbblish using the given bash commands in the Readme file
4. Start Spotify

**Specifics**
 - OS: Arch Linux
 - Spotify version [e.g. 1.1.68.632]
 - Spicetify version [e.g. 2.7.2]
 - Dribbblish

**Comment by khanhas** [comment]
I just updated css-map.
Please run `spicetify restore backup apply` and it should be normal now.
