### ISSUE TITLE
[Dribblish] Black Box behind Playing Song

### ISSUE THREAD

**Issue by Wawwior** [morpheusthewhite/spicetify-themes#603]
**Describe the bug**
There is a weird black box behind the playing song icon and name.

**To Reproduce**
1. Install Spicetify via Powershell
2. Install Dribbblish Theme via Powershell
3. Use 'spicetify apply'
4. See Error

**Expected behavior**
Look like on the Dribbblish screenshots.

**Screenshots**
![Screenshot 2021-11-08 212626](https://user-images.githubusercontent.com/45405580/140814550-1088fce3-8407-4f16-937a-be3b3947383f.png)

**Logs**
![image](https://user-images.githubusercontent.com/45405580/140815239-7970647f-3401-4263-9a6c-8a6a0907fb7e.png)

**Specifics:**
 - OS: Windows 10
 - Spotify 1.1.71.560.gc21c3367
 - Spicetify 2.7.2
 - Dribbblish

**Comment by khanhas** [comment]
Fixed.
