### ISSUE TITLE
[Fluent] Sidebar Icons not aligned (HOME, SEARCH, LIBRARY)

### ISSUE THREAD

**Issue by Blehblahblew** [morpheusthewhite/spicetify-themes#605]
The left sidebar icons are not aligned 

- Home
- Search
- Library

 ![image](https://user-images.githubusercontent.com/79393502/141032048-02df35c2-d326-484a-8051-273ae568317c.png)

**To Reproduce**
Install Spicetify
Install Fluent

 **Expected Result**
 Icons should be aligned with the left sidebar

 **Actual Result**
 Icons are not aligned with the left sidebar
 
 System info:
Spotify: **1.1.71.560.gc21c3367**
Spicetify: **2.7.2**
Theme: **Fluent**
OS: **Windows 10**

**Comment by Blehblahblew** [comment]
![image](https://user-images.githubusercontent.com/79393502/141035092-dbc4e8f4-e34c-4274-bbcd-d5da616c3196.png)

**Comment by williamckha** [comment]
Are you on the latest version of Fluent? Latest version fixes this issue

**Comment by Blehblahblew** [comment]
Could've sworn i installed the latest update, but turns out i didnt, 

**SOLUTION**
Update to the latest fluent 
thanks to williamckha for the tip
