### ISSUE TITLE
[Dribblish] Fade-in on buddy-feed

### ISSUE THREAD

**Issue by leonscm** [morpheusthewhite/spicetify-themes#606]
How do I get the fade in from the playlist-list on my buddy-feed like this:
![InkedScreenshot 2021-11-12 230320_LI](https://user-images.githubusercontent.com/68074724/141540484-159627e2-0599-4c0d-b97d-4db9c84becba.jpg)
(changed this in dev-tools, don't know how to do it in user.css tho)

**Comment by morpheusthewhite** [comment]
Please use Discord or reddit for suggestions. Use GitHub only for reporting issues.

**Comment by morpheusthewhite** [comment]
https://github.com/morpheusthewhite/spicetify-themes#troubleshooting
