### ISSUE TITLE
Fluent Bugging After Restart

### ISSUE THREAD

**Issue by sebastianking39** [morpheusthewhite/spicetify-themes#607]
I have Fluent and now after a restart it's bugged.

All I did was restart my computer!

![image](https://user-images.githubusercontent.com/63021947/141601766-aac96a9c-2ba6-492d-b59f-34768e86e721.png)

Console:

3vendor~xpui.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Translations')
    at fluent.js:77
    at i (vendor~xpui.js:1)
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621847)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624431)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859649)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883381)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096964)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829185)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883160)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868039)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866961)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2829457
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096964)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829185)
    at yr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829402)
    at vr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829337)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2867460)
    at il (https://xpui.app.spotify.com/vendor~xpui.js:29:2893731)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2896842)
    at https://xpui.app.spotify.com/xpui.js:1:1042488
(anonymous) @ vendor~xpui.js:1
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
sentry.io/api/114855/store/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at d.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021110901.js:10 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021110901.js:10
pubads_impl_2021110901.js:10 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021110901.js:10
VM35:9 Ads: HPTO HTML DFP Template: No iframe found for third party click tracking.
pubads_impl_2021110901.js:10 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021110901.js:10
pubads_impl_2021110901.js:10 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021110901.js:10
VM43:9 Ads: HPTO HTML DFP Template: No iframe found for third party click tracking.
banner:292 Pageview ok.
banner:300 View event ok.
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/566.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

 - Win 11
 - Fluent

**Comment by sebastianking39** [comment]
if anybody needs anything ill be glad to add info

**Comment by void206551** [comment]
Your spicetify might be out of date. I had the same issue and running `spicetify upgrade` and `spicetify restore backup apply` fixed it for me.

**Comment by sebastianking39** [comment]
Thanks it worked!
