### ISSUE TITLE
[Fluent] folder Picture won't load and play/pause button not showing correctly

### ISSUE THREAD

**Issue by amirhossein1371** [morpheusthewhite/spicetify-themes#608]
![Untitled](https://user-images.githubusercontent.com/47679425/141642395-1ab98b0e-a5e5-4274-ba0c-b33e0f9a304a.png)

**Comment by morpheusthewhite** [comment]
You didn't install Fluent properly. Please follow the instructions 

https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent#install
