### ISSUE TITLE
Dribbblish broken with new update (1.1.72.439)

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [morpheusthewhite/spicetify-themes#611]
![Screenshot_9](https://user-images.githubusercontent.com/70870070/141799369-972db40d-0f87-4aac-bd18-17fad54f0b31.png)

**Comment by thespyboss** [comment]
Its doing the same for me also 
![image](https://user-images.githubusercontent.com/42257053/142085663-c8f8ef3c-b948-4b23-ab05-f8de4eeb82bc.png)

**Comment by trashcatt** [comment]
I got it working correctly by reinstalling Spotify.

**Comment by thespyboss** [comment]
thanks a ton @trashcatt ! that worked for me

**Comment by trashcatt** [comment]
> 
> 
> thanks a ton @trashcatt ! that worked for me

Glad I could help. :D

**Comment by 1-minute-to-midnight** [comment]
Reinstalling didn't work on Arch Linux

**Comment by 1-minute-to-midnight** [comment]
Nevermind it started working now
