### ISSUE TITLE
Fluent media controls look weird when casting

### ISSUE THREAD

**Issue by RaddedMC** [morpheusthewhite/spicetify-themes#620]
Looks like the Spotify Connect bar is pushing the UI close to the edge of the media control bar
<img width="812" alt="image" src="https://user-images.githubusercontent.com/66137579/143510533-1c1271d1-d3ae-4f72-a0ea-d7219bc9d088.png">

**Comment by williamckha** [comment]
c066278 adds styling to connect bar
