### ISSUE TITLE
Fluent theme issue with sidebar and play button

### ISSUE THREAD

**Issue by FC5570** [morpheusthewhite/spicetify-themes#625]
Hello. I use the fluent theme with `dark` scheme. I'm having issues with the Sidebar playlist icons not displaying and the playbutton is not displaying. I have attached the images below.

![image](https://user-images.githubusercontent.com/68158483/143778686-a3908a70-e207-4504-b11c-9520a75af893.png)
![image](https://user-images.githubusercontent.com/68158483/143778693-fcf36b24-2eba-43d4-9fa9-4aba516fb37d.png)

I have also done the following changes to spicetify's config as said in the theme's [readme](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent#important).
```
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,
```
 - OS: Windows 11
 - Spotify version - 1.1.73.517.gbef50fdb
 - Spicetify version - 2.8.3

**Comment by hazre** [comment]
same issue here

**Comment by FC5570** [comment]
@williamckha Will a fix for this be released?

**Comment by sagars007** [comment]
I had the same issue before and fixed it. The fluent.js file was missing. You need to follow the installation commands in the Fluent theme's readme and not the one given in the main spicetify-themes readme. The code to include fluent.js is there. 
[Install fluent theme via powershell](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent#install)

**Comment by FC5570** [comment]
My bad, I reinstalled spicetify and forgot to follow the steps. Thanks @sagars007!
