### ISSUE TITLE
[Windows] cp * "$(spicetify -c | Split-Path)\Themes\" -Recurse doesn't work

### ISSUE THREAD

**Issue by THEWOKE** [morpheusthewhite/spicetify-themes#629]
I get the following message when running the above command "`cp` is not recognized as an internal or external command, operable program or batch file"

![image](https://user-images.githubusercontent.com/55265881/144355718-7f7f8109-81ca-44c0-8cd4-0372476a1555.png)

I searched online and apparently cp is a UNIX command so the Windows cp equivalent is "copy". I then tried copy * "$(spicetify -c | Split-Path)\Themes\" -Recurse but get the problem "The syntax of the command is incorrect"

![image](https://user-images.githubusercontent.com/55265881/144355850-2c57b386-b89d-496e-830e-2d7bec567aad.png)

**Comment by williamckha** [comment]
You must run the commands in PowerShell, not command prompt
