### ISSUE TITLE
Jasmine Theme

### ISSUE THREAD

**Issue by Axieum** [morpheusthewhite/spicetify-themes#63]
Hi there,

I've created a Spicetify theme - heavily inspired by Lovelace - called **Jasmine**, and am wondering if you'd be happy to show it off here?

Here is the repository source: [Axieum/Jasmine-Spicetify-Theme](https://github.com/Axieum/Jasmine-Spicetify-Theme)

You could link the above repository into its own folder (as a [submodule](http://help.github.com/submodules/)).

**Comment by morpheusthewhite** [comment]
If you want you can add it to the collection, just follow the instructions in the README
