### ISSUE TITLE
[Dribbblish] sidebar icons not working

### ISSUE THREAD

**Issue by notprash** [morpheusthewhite/spicetify-themes#640]
sidebar icons are not working. I have done all the things currently but still does not work
![image](https://user-images.githubusercontent.com/67903361/145668553-7db558d8-19e6-47ab-919c-25e69c39e726.png)

**Comment by DeadTec9s** [comment]
yeah same thing has happened to me

**Comment by notprash** [comment]
fixed with the new spicetify update
