### ISSUE TITLE
[Dribbblish] How to move song progress times

### ISSUE THREAD

**Issue by jabreen** [morpheusthewhite/spicetify-themes#643]
I have gone into the `user.css` file and changed `display = none' to 'display = flex` under the `.playback-bar__progress-time` variable. Doing this has brought back the song progress times, but the one on the left needs to be moved. Is there a way to move the playback bar by modifying the CSS file?

**To Reproduce:**
1. Open `user.ccs` in the Dribbblish theme folder. If you are on Windows, it will be located at `%userprofile%\.spicetify\Themes\Dribblish\user.css`.
2. Modify `display = none` under `.playback-bar__progress-time-elapsed {` (line 401) to `display = flex`
![image](https://user-images.githubusercontent.com/77906597/145923347-13313290-b5d8-4b77-bf37-f4c6e946a486.png)
3. Run `spicetify update` in terminal
4. Reboot Spotify
5. The playback buttons will be off-center as shown in the screenshots.

![image](https://user-images.githubusercontent.com/77906597/145922906-b0bc9d8a-de43-44d2-835b-7aa1879412d6.png)
The one on the far left diverging away from the playback bar is the issue.

OS: Windows 10
Spotify: Most recent version
Spicetify: Most recent version
Theme name: Dribbblish

**Comment by morpheusthewhite** [comment]
Please use Discord or Reddit for asking this kind of questions. Use GitHub issue for reporting bugs
