### ISSUE TITLE
[Dribbblish] How to get rid of glow on song bar

### ISSUE THREAD

**Issue by jabreen** [morpheusthewhite/spicetify-themes#644]
I have noticed the song bar has a white glow on it and I was wondering if there was a way to get rid of it. I'm assuming it would be in the CSS file, but I'm not sure what to look for.

**Screenshots**
![image](https://user-images.githubusercontent.com/77906597/145926217-5ab59278-0420-4324-b0a0-109e1c5fe96e.png)

OS: Windows 10
Spotify: Most recent version
Spicetify: Most recent version
Theme: Dribbblish

**Comment by leonscm** [comment]
Delete this line in the user.css file:

.main-nowPlayingBar-container {
    border-radius: 0 0 var(--main-corner-radius) var(--main-corner-radius);
    background-color: unset;
    **background: radial-gradient(ellipse at right 50% bottom -80px, rgba(var(--spice-rgb-sidebar), 0.55), var(--spice-main) 60%);**
    border-top: 0;
    min-width: 518px;
}

**Comment by jabreen** [comment]
Thank you! This worked, but it made the entire bar the same color as the theme and It's made it fairly unreadable.
![image](https://user-images.githubusercontent.com/77906597/146090039-d0cfc824-9cde-4cbc-9d37-57ca1fe809cd.png)
Would there be a way to change the color of the play bar back to what it was beforehand?

**Comment by leonscm** [comment]
Try changing background-color to var(--spice-main)
