### ISSUE TITLE
spicetify themes are corrupt on winrar

### ISSUE THREAD

**Issue by Killertodo2** [morpheusthewhite/spicetify-themes#645]

**Comment by morpheusthewhite** [comment]
What does this mean? How are we supposed to help you?

**Comment by Killertodo2** [comment]
i fixed the problem, i just had to fix the corrupt file but now on spotify the themes are incomplete or messed up. 
![Screenshot (14)](https://user-images.githubusercontent.com/71413699/146279912-c83bf766-0279-4416-9c4c-31dcb1c4c9b0.png)
