### ISSUE TITLE
[Fluent] Misaligned Icons on the sidebar + 2 back buttons

### ISSUE THREAD

**Issue by realkinja** [morpheusthewhite/spicetify-themes#648]
**Describe the bug**
Home, Library and Search icons on the sidebar are misaligned.
And there are 2 back buttons, one covered by the normal Spotify menu button.

**To Reproduce**
1. Download the spicetify-themes repository through the Code button and click Download ZIP.
2. Extract the "Fluent" folder to the Themes folder inside of .spicetify (located in your user folder.)
3. Follow the steps in the readme.md
4. See the misaligned icons. Might just be me.

**Expected behavior**
This is how it should've looked like.
![image](https://user-images.githubusercontent.com/78376161/146697115-7cf5bf0b-0106-4090-a7b0-4796c638ab84.png)

**Screenshots**
![image2](https://user-images.githubusercontent.com/78376161/146696696-c40c55a1-eebe-4f66-8113-955e33877548.png)

**Logs**
![image](https://user-images.githubusercontent.com/78376161/146696593-71044adb-6cfd-450c-9aa6-85aeef06a117.png)

**Specifics:**
 - OS: [Windows 11 Home]
 - Spotify version [Spotify for Windows 1.1.74.631.g0b24d9ad]
 - Spicetify version [2.8.3]
 - Fluent

**Comment by youngerstar** [comment]
Same problem. 
And the cover of playlist looks strange.
![image](https://user-images.githubusercontent.com/46211595/146767682-3f53210a-0fed-46f5-8627-264e8902afd5.png)
For example, 
![image](https://user-images.githubusercontent.com/46211595/146767768-6b843f48-5c1e-4861-a562-a5ae09bc1254.png)
![image](https://user-images.githubusercontent.com/46211595/146767826-a6a8aa4e-fdf7-4356-b4a1-6b253947ed05.png)

**Comment by EpicBProgrammingOnReddit** [comment]
So Where's The Patch? Can Anyone Comment On This & Make A Patch To Fix This?

**Comment by NaufalF22** [comment]
I kinda fix the misalign icon
add margin-left=20px at all icon like at ss
![image](https://user-images.githubusercontent.com/63091744/147396457-e37a35f1-e151-4b2b-9d49-d93b979f0d4c.png)
Result
![image](https://user-images.githubusercontent.com/63091744/147396465-a5e3e758-6b63-45f7-8c66-352700a97f76.png)

**Comment by Be1zebub** [comment]
#655 js fixed, sidebar icons is also fixed.

the classes and names of the buttons are mixed up for some reason, main-topBar-back has the aria-label "Forawrd". It seems that if I make a fix, it will only work on this version of spotify, and on older versions it will break the layout.
![wtf](https://i.imgur.com/Bp4Dxzm.png)
I think that the only way is to make a js patch - so that it checks if the classes are mixed up and fix them.

**Comment by Be1zebub** [comment]
elegant way found, i fixed this with :nth-child
this should work on any of spotify ver
![](https://raw.githubusercontent.com/Be1zebub/spicetify-themes/master/Fluent/screenshots/comfy-2.jpg)

**Comment by Be1zebub** [comment]
issue solved, try a new ver
https://github.com/morpheusthewhite/spicetify-themes/pull/655/files/b449e4e0309faf39e4e3b8309e0f830550d772fb
