### ISSUE TITLE
Unable to resize sidebar + progress bar not being displayed

### ISSUE THREAD

**Issue by stpnwf** [morpheusthewhite/spicetify-themes#656]
**Describe the bug**
1. Can't resize sidebar
2. Progress bar disappeared 

3. Not a bug, just an idea. I think the Artist Image disappears too quickly upon scrolling.

**Screenshots**

https://user-images.githubusercontent.com/81482539/148321596-b59c6979-40b2-4dc2-88d7-d5bf5446ac53.mp4

**Specifics (please complete the following information):**
 - OS: Ubuntu 20.04
 - Spotify version: 1.1.72.439.gc253025e
 - Spicetify version: 2.8.3
 - Theme name: Dribbblish

**Comment by morpheusthewhite** [comment]
That is probably caused by some recent Spotify update, to can try to revert to a previous version

**Comment by CharlieS1103** [comment]
@morpheusthewhite Nah, if you look at the spotify version they're on 72. @stpnwf Mind sending your config file?

**Comment by stpnwf** [comment]
> @morpheusthewhite Nah, if you look at the spotify version they're on 72. @stpnwf Mind sending your config file?

For some reason, re running the config commands after the Spotify and Spicetify update failed to copy dribbblish.js to the Extensions folder. Running the command to inject didn't return an error, so I just assumed it had went through all the times I re run it. Pasting it there and re runing the injecting command fixed issues 1. and 2. Thank you!
