### ISSUE TITLE
[Dribbblish] Tokyonight colorscheme

### ISSUE THREAD

**Issue by SyedAhkam** [morpheusthewhite/spicetify-themes#664]
Hey! I've been trying to implement a tokyonight colorscheme for the Dribbblish theme.

Although I am not a UI designer and I have idea about theming elements of an application. I took the color codes from [here](https://github.com/enkia/tokyo-night-vscode-theme) and came up with this.

### This is how it looks presently
![](https://syed.needs.rest/r/kyhsmhbjp0a.png)

### Using this colors config

```ini
[tokyonight]
main_fg                               = f7768e
active_control_fg                     = f7768e
secondary_fg                          = c0caf5
main_bg                               = 24283b
secondary_bg                          = 1a1b26
sidebar_and_player_bg                 = 24283b
cover_overlay_and_shadow              = c0caf5
indicator_fg_and_button_bg            = 9ece6a
pressing_fg                           = 73daca
slider_bg                             = 73daca

sidebar_indicator_and_hover_button_bg = 2ac3de
scrollbar_fg_and_selected_row_bg      = 2ac3de

pressing_button_fg                    = c0caf5
pressing_button_bg                    = 2ac3de
selected_button                       = 1a1b26
miscellaneous_bg                      = ff9e64
miscellaneous_hover_bg                = e0af68
preserve_1                            = a9b1d6
```

I am aware of the buttons' text fg not being readable, that needs to be fixed. It's not ready yet. I believe this could transform into something even better, anyone willing to help me out? We could make a PR once its upto mark.

**Comment by morpheusthewhite** [comment]
You can probably reach more people by chatting on the Discord channel. 

Once you are ready, just open the PR
