### ISSUE TITLE
[Fluent] Play button and icon bug

### ISSUE THREAD

**Issue by RadNotRed** [morpheusthewhite/spicetify-themes#682]
**Describe the bug**
The play button is all white and folder / playlist icons don't load

**To Reproduce**
open spotify

**Expected behavior**
Play button is visible, icons for folders/playlists load

**Screenshots**
![image](https://user-images.githubusercontent.com/80015713/154560991-0a53eddb-46df-42cc-b364-b20c5b87fb5d.png)
![image](https://user-images.githubusercontent.com/80015713/154561027-7aad2c60-3c6b-4fa4-b6d7-a49d52caa2b7.png)

**Logs**
```console
fluent.js:28 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at replacePlaylistIcons (fluent.js:28:31)
    at fluent.js:47:5
    at waitForElement (fluent.js:6:7)
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.79.763.gc2965cdf
 - Spicetify version 2.9.0
 - Fluent

**Comment by nanchaara** [comment]
fixed on spicetify 2.9.1 update!
