### ISSUE TITLE
[Turntable] Unable to exit the turntable. ESC not working. 

### ISSUE THREAD

**Issue by Ruixi-Zhang** [morpheusthewhite/spicetify-themes#714]
**Describe the bug**
When I tried to exit the turntable using the ESC button, the entire app will freeze into a black screen. I have to restart the entire app to make it work.

**To Reproduce**
1. Config turntable extension
2. Play a song
3. Click on the Turntable button on the top left of the screen
4. Try to exit the Turntable with ESC

**Expected behavior**
After clicking ESC, the turntable should be exit and return to the normal page.

**Specifics (please complete the following information):**
* Spotify version [1.1.81.604.gccacfc8c]
* Spicetify version [2.9.4]
* Theme name: Turntable

**Comment by grasonchan** [comment]
@Ruixi-Zhang It has been fixed, pls wait for the PR to be merged and try it. Thanks for your feedback.
