### ISSUE TITLE
[Bloom] Icons/song name not centered

### ISSUE THREAD

**Issue by h2v** [morpheusthewhite/spicetify-themes#737]
**Describe the bug**
Icons in bloom theme not centered.

**To Reproduce**
1. Go to Spicetify
3. Apply Bloom theme
4. Observe

**Expected behavior**
Icons to be aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/98252522/164861385-42baf609-bc67-4af3-af89-38f2cdc5b5d3.png)

**Specifics (please complete the following information):**
 - OS: Win 10
 - Spotify version 1.1.83.956.gbe7ea9a7
 - Spicetify version 2.9.6
 - Bloom

**Comment by trashcatt** [comment]
I'm also having this issue but I'm on Win 11.

**Comment by nimsandu** [comment]
I'm sorry to hear that sir
you might install the theme using marketplace
plz reset the marketplace by clicking settings icon on marketplace>scroll all the way down and click [reset marketplace]
And run following command

### Windows (PowerShell)

```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

this must fix that

**Comment by trashcatt** [comment]
> 

That did not fix it.

**Comment by nimsandu** [comment]
Oh 
Plz remove whole spicetify folder and uninstall Spotify

Then install Spotify and run above command
And let me know

**Comment by nimsandu** [comment]
Spicetify folder located in 
C/user/(user name)/.spicetify 

Delete the whole folder 
And uninstall Spotify

**Comment by trashcatt** [comment]
Still the same thing.

**Comment by nimsandu** [comment]
Ill try fixing that asap sir

Plz mention your screen resolution

**Comment by trashcatt** [comment]
> Ill try fixing that asap sir
> 
> Plz mention your screen resolution

1440p

**Comment by Owen1713** [comment]
Having the exact same issue as @xelemir, any fixes yet?

**Comment by xelemir** [comment]
@Owen1713 i gave up on Spicetify as there seems to be a new issue every other day. Spotify apparently doesn't like 3rd party tools to inject code and I'm not willing to deal with constantly buggy software. :(
