### ISSUE TITLE
[Dribbblish] Playlists not showing correctly

### ISSUE THREAD

**Issue by DArkErAsEr-BeAsT** [morpheusthewhite/spicetify-themes#83]
In the screenshots it seems like the big cover photos (see Jacob Lee image) of playlists and artists are much more high-res in your screenshots, than they are on my machine after applying the theme. Do you have any idea why that might be happening ?
Apart from that I love the idea of the theme, great job !!

**Comment by khanhas** [comment]
How does it look like on your side? 
But actually on mine, not all cover images are high res though. They just look acceptable.

**Comment by DArkErAsEr-BeAsT** [comment]
![image](https://user-images.githubusercontent.com/31793252/81411807-2c486600-9143-11ea-9d67-224d867d997a.png)
Like this for example. I don't think that ist's really an issue one can counter since it must be a scaling issue, spotify not giving covers of that size no ?

**Comment by leviticuskrunk** [comment]
hello, i have a problem with the dribbblish theme: the theme works fine except for the sidebar, it has labels on the sidebar instead of the icons. anyone know how to fix this?
![Spotify_AumP3JOdfp](https://user-images.githubusercontent.com/64995076/81464816-7ee35a00-91f7-11ea-9618-a314729ef60d.png)

**Comment by khanhas** [comment]
@leviticuskrunk Please follow the command chain in the theme Readme page

**Comment by ewen-lbh** [comment]
@leviticuskrunk More specifically you have to activate the extension `dribbblish.js` which you need to move from `Themes/Dribbblish` to `Extensions`

**Comment by emino07** [comment]
@leviticuskrunk @khanhas  I have the same issue with the latest version of spotify and spicetify. I think that the extension breaks if you have playlist folders in your library.

**Comment by khanhas** [comment]
@emino07 Oh my. I totally forgot about playlist folder case.
Seem like it re-render  itself whenever we open an folder.

**Comment by shitobu** [comment]
thanks for the help up there guys, i got a question that kind-of applies to this it won't hide the windows toolbar once i applied the flag in README.MD (on windows)

**Comment by DArkErAsEr-BeAsT** [comment]
> hello, i have a problem with the dribbblish theme: the theme works fine except for the sidebar, it has labels on the sidebar instead of the icons. anyone know how to fix this?
> ![Spotify_AumP3JOdfp](https://user-images.githubusercontent.com/64995076/81464816-7ee35a00-91f7-11ea-9618-a314729ef60d.png)

**Comment by DArkErAsEr-BeAsT** [comment]
> @emino07 Oh my. I totally forgot about playlist folder case.
> Seem like it re-render itself whenever we open an folder.

so about this, do you know of any way to stop it from re-rendering itself ?

**Comment by khanhas** [comment]
[dribbblish.js.zip](https://github.com/morpheusthewhite/spicetify-themes/files/4605481/dribbblish.js.zip)
This is my attempt, I got work to do so I can't continue on this until next weekend.
Tell me what you think and and better idea/solution if you have one.

**Comment by DArkErAsEr-BeAsT** [comment]
yeah nice work with the quick fix man ! 
I don't know very good at javascript so I'm not going to presume that I can do a better job than you.
However if you could look at it again when you have the time it would be greatly appreciated.
Keep up the good work mate, cheers !

**Comment by khanhas** [comment]
Updated in repo, please pull to update.

**Comment by Belmaj** [comment]
> Updated in repo, please pull to update.
> 
> What it should look like right now:
> ![Screenshot_20200510_234329](https://user-images.githubusercontent.com/26436809/81500848-28ba0800-9318-11ea-8fae-15df0c7c3ece.png)

sir can you give me the link for this tutorial how to add side bar in spotify.

**Comment by khanhas** [comment]
> sir can you give me the link for this tutorial how to add side bar in spotify.
The sidebar is always there in Spotify. I just changed its appearance with CSS and JS. Take a look at `dribbblish.js` I guess.

**Comment by yannick-craens** [comment]
Hi,

I am trying to edit the border colors but not the colors of the other elements. Is there a way to specify only these elements? Atm I have only found .LeftSiderBar and the bottom left gradient.

Thanks in advance,
Yannick

**Comment by khanhas** [comment]
> Hi,
> 
> I am trying to edit the border colors but not the colors of the other elements. Is there a way to specify only these elements? Atm I have only found .LeftSiderBar and the bottom left gradient.
> 
> Thanks in advance,
> Yannick

What kind of border?

**Comment by yannick-craens** [comment]
> What kind of border?

The left sidebar that includes playlists, icons etc that wraps all around the screen.

**Comment by swingcake** [comment]
@khanhas Is it possible to get rounded (curved) edges like in the following screenshot on Windows?

> ![Screenshot_20200510_234329](https://user-images.githubusercontent.com/26436809/81500848-28ba0800-9318-11ea-8fae-15df0c7c3ece.png)

**Comment by khanhas** [comment]
@swingcake I'm sorry, there's none.

**Comment by leviticuskrunk** [comment]
Hello, I am using the new dribbblish.js extension as provided here, and the "recently played" button does not have an associated icon with it. How do I fix this? I only modified the font and that's it.
![Spotify_mU0SDy2x1r](https://user-images.githubusercontent.com/64995076/82851939-ef96b000-9f33-11ea-93b2-e1e3edca6b8e.png)

**Comment by khanhas** [comment]
@leviticuskrunk Please upgrade to Spicetify v0.9.9. then run 
```
spicetify restore backup apply
```

**Comment by leviticuskrunk** [comment]
@khanhas 
After re-running the install command in Powershell, Spicetify remains at v0.9.8. How do I manually upgrade it to v0.9.9? Thanks in advance.
![powershell_vF9ISNUtLn](https://user-images.githubusercontent.com/64995076/82891973-33fc6d00-9f81-11ea-85a7-6e4b9941dfb8.png)

**Comment by khanhas** [comment]
@leviticuskrunk
```
cd ~\spicetify-cli
.\spicetify.exe restore backup apply
```

**Comment by jimcorrigan** [comment]
![image](https://user-images.githubusercontent.com/65959673/82905112-71d1a500-9f31-11ea-87f5-b904e15e7b7f.png)

It is possible to hide the three buttons on right? (close, minimize and maximize)

thanks for the theme!

**Comment by khanhas** [comment]
[SpotifyNoControl.zip](https://github.com/morpheusthewhite/spicetify-themes/files/4682451/SpotifyNoControl.zip)
@jimcorrigan Try this. I just made it this week.

**Comment by jimcorrigan** [comment]
![image](https://user-images.githubusercontent.com/65959673/82905357-caa13d80-9f31-11ea-9528-0acdbf35e72a.png)

It is possible to hide the three buttons on right? (close, maximize and minimize)

thanks for the theme!

**Comment by camjac251** [comment]
Is that exe the only way to get Windows right icons to disappear?
![image](https://user-images.githubusercontent.com/6313132/83163137-4b963b80-a0d0-11ea-91ba-01567e145d81.png)

**Comment by khanhas** [comment]
It doesn't work or something?

**Comment by camjac251** [comment]
I am using a regular Spotify install with `--transparent-window-controls` after in the Target field on the shortcut. It doesn't seem to hide though.

That exe you linked, is a patched? Required?

**Comment by khanhas** [comment]
It just searches for those "icons" and hide them away.
If you already have Spotify opening, running the file I gave will hide them immediately.
Otherwise, running it will execute Spotify.exe and automatically hide those icons right after.

**Comment by BelamiONE** [comment]
I couldn't, can you help me?

**Comment by 906532645** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/18509861/83460024-4f042c80-a41a-11ea-915c-afe0560ed7e2.png)
![Screenshot_2](https://user-images.githubusercontent.com/18509861/83460025-4f9cc300-a41a-11ea-8e7c-debcf7962fea.png)
![Screenshot_1](https://user-images.githubusercontent.com/18509861/83460026-4f9cc300-a41a-11ea-9aa7-3e3910c1ec67.png)

**Comment by kindababylon** [comment]
Anyone tell me what i have to do with this code: 
cd "$(spicetify -c | Split-Path)\Themes\Dribbblish"
Copy-Item dribbblish.js ..\..\Extensions
spicetify config extensions dribbblish.js
spicetify config current_theme Dribbblish color_scheme base
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply

**Comment by khanhas** [comment]
@kindababylon Copy and paste them to Powershell terminal
Please copy again from the readme page

**Comment by kindababylon** [comment]
am i need to change smth in code?

**Comment by khanhas** [comment]
@kindababylon No

**Comment by kindababylon** [comment]
![image](https://user-images.githubusercontent.com/66326735/83601824-678f5680-a582-11ea-9a88-bf50199b770f.png)

**Comment by kindababylon** [comment]
in which folder i'm need to write this code?

**Comment by khanhas** [comment]
Can you move this conversation to somewhere else?
You not even install Spicetify!

**Comment by khanhas** [comment]
@kindababylon Can you ask your question on Spicetify Spectrum so people can help you there?
You did not even install Spicetify!

**Comment by kindababylon** [comment]
i installed

**Comment by kindababylon** [comment]
![image](https://user-images.githubusercontent.com/66326735/83603754-09fd0900-a586-11ea-819b-0f2ee29ce76c.png)

**Comment by khanhas** [comment]
You got this far and asked me "what to do with these code"?
How do you run `spicetify` back then?

**Comment by kindababylon** [comment]
i just do like in tutorial https://vk.com/video-63127337_456239292

**Comment by kindababylon** [comment]
maybe i did something wrong? Can you do tutorial how to install these theme

**Comment by morpheusthewhite** [comment]
@kindababylon please don't use GitHub issues for support, all necessary instructions are provided in the README; for further support, as said by @khanhas, use the Spectrum chat

**Comment by Vedaant-Rajoo** [comment]
How do you uninstall this theme?
You should give a guide to that too/

**Comment by morpheusthewhite** [comment]
A `spicetify restore` should be enough
