### ISSUE TITLE
[Ziro] Stuck on settings

### ISSUE THREAD

**Issue by KnoyanMitsu** [morpheusthewhite/spicetify-themes#858]
spicetify 2.14.1

stuck on settings and cannot click close 
very weird i change ziro theme but this Dribbblish settings

![image](https://user-images.githubusercontent.com/65282316/199398077-5b7627dc-4ba3-47b5-ac78-756c9e9933de.png)

**Comment by Sasikuttan2163** [comment]
Could you paste the output of `spicetify config` here?

**Comment by Sasikuttan2163** [comment]
The dribblish-dynamic JS is still loaded. Try removing it by `spicetify config extensions dribbblish-dynamic.js-`
