### ISSUE TITLE
[Dribbbish]Local files tab has no icon

### ISSUE THREAD

**Issue by UrSok** [morpheusthewhite/spicetify-themes#88]
![image](https://user-images.githubusercontent.com/5286851/81582281-8867f000-93b8-11ea-9489-e3ced16ccfc9.png)

**Comment by khanhas** [comment]
I believed I added last week:
https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/dribbblish.js#L101

**Comment by UrSok** [comment]
Just appeared for me after theme reinstall.
