### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by bondalovskiy** [morpheusthewhite/spicetify-themes#95]
Hi, how can I set default theme again? I can just delete spicetify, but I need it for lyrics

**Comment by morpheusthewhite** [comment]
Run `spicetify restore`

**Comment by kguidonimartins** [comment]
Just registering another solution. You can leave the `current_theme` blank in the configuration file:

```
current_theme           =
```

Then run:

```bash
spicetify apply
```
