### ISSUE TITLE
Handle is Invalid.

### ISSUE THREAD

**Issue by GreenGradientMan** [morpheusthewhite/spicetify-themes#96]
Hey! i’m using the dribbblish theme on windows 10 using power shell and the setup ran smoothly except for one error that’s preventing the theme from working. when spicetify apply is commanded, everything is green across the board except for “Transfering extensions”. the error reads “red C: \Users\robod\.spicetify\Extensions\dribblish.js : The handle is invalid” I’ve checked to make sure the folders and pathways are there, but it’s till not working. Help please?

**Comment by khanhas** [comment]
It's dribbblish.js` with 3 `b`

**Comment by GreenGradientMan** [comment]
That was a mistype here, but i went and downloaded the dribbblish.js zip file you commented on a different issue and that fixed the error. Only issue i’m having now is the theme is half applied so i’m going to see if there were any commands i didn’t run yet
