### ISSUE TITLE
Sidebar uses text not icons

### ISSUE THREAD

**Issue by GeorgeBarlow** [morpheusthewhite/spicetify-themes#97]
![6W1w081](https://user-images.githubusercontent.com/27292008/83623612-73cae200-a589-11ea-85c2-7c3f9d3f6414.png)

The sidebar is showing text rather than icons, I followed the steps in the README, is it obvious what I've done wrong?

**Comment by khanhas** [comment]
https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#how-to-install
