### ISSUE TITLE
Dribbblish theme sidebar icons broken with recursive playlist folders

### ISSUE THREAD

**Issue by Sparoney** [morpheusthewhite/spicetify-themes#99]
Hi,

Recently, the Dribbblish theme has stuffed up, the icons on the sidebar aren't showing. I've seen other users with the same issue but you've closed all their issues and told them to reinstall it.

I have reinstalled the theme, following all the commands in the readme. I even downgraded to an older version of Spotify. I've reinstalled Spicetify. The sidebar icons are still broken. I'm using Windows 10.

Looking at the console, there appears to be an error in the ``loadPlaylistImage`` function in the dribbblish.js extension.

```
Uncaught TypeError: Cannot read property 'href' of undefined
    at loadPlaylistImage (dribbblish.js:30)
    at dribbblish.js:54
    at i (zlink.bundle.js:59)
    at waitForElement (dribbblish.js:4)
    at i (zlink.bundle.js:59)
```
Line 30 of the .js file is ``const href = link.href.replace("app:", "");``

Something somehow has broken and I can't seem to fix it (and I'm guessing other users too).

Hopefully you are able to provide a fix.

**Comment by Sparoney** [comment]
Ok I found the issue. One of my playlist folders when opened, stuffs up all the icons, and they are fixed when it is closed. I think it's because that playlist folder has other playlist folders inside of it.

**Comment by khanhas** [comment]
Huh, I think I well tested both playlist folder and recursive folder cases. Can you temporarily disable `dribbblish.js` and screenshot your playlist folder structure?
Also you don't have to downgrade Spotify version. It's just make it harder to debug.

**Comment by mrForestA** [comment]
I am experiencing the same issue

**Comment by BehdadEs** [comment]
I also have this issue.
Sidebar icons are not showing they just show a small text
![Screenshot from 2020-06-19 17-58-58](https://user-images.githubusercontent.com/39169918/85137561-a564ce00-b256-11ea-9512-9741abff9837.png)

**Comment by vandan-school** [comment]
I am having the same issue as everyone else... only text is showing : (

**Comment by khanhas** [comment]
@BehdadEs , @vandan-school  https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish#how-to-install

**Comment by J370** [comment]
Had earlier experienced the same issue at first and tried going through the installation again to no avail.

Took hint from this [issue](https://github.com/morpheusthewhite/spicetify-themes/issues/83) that it could have had something to do with the [dribbblish.js](https://github.com/morpheusthewhite/spicetify-themes/issues/83#issuecomment-626140404) file. After further inspection into what was being run, I noticed that there was an error raised with regards to this particular dribbblish.js javascript file. Upon further investigation into the file itself, I realised that for some reasons, when pulling from github, another file is pulled instead of the javascript file that was required.

What I did to solve my issue was to locate the [corresponding file on github](https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/dribbblish.js) and replaced the one that is in the Extensions. I suggest that @BehdadEs and @vandan-school give this a try to see if this would fix their issue.

**Comment by ChoogleGrome** [comment]
Having the same issue, tried this but didn't work for me. Also tried reinstalling

> Had earlier experienced the same issue at first and tried going through the installation again to no avail.
> 
> Took hint from this [issue](https://github.com/morpheusthewhite/spicetify-themes/issues/83) that it could have had something to do with the [dribbblish.js](https://github.com/morpheusthewhite/spicetify-themes/issues/83#issuecomment-626140404) file. After further inspection into what was being run, I noticed that there was an error raised with regards to this particular dribbblish.js javascript file. Upon further investigation into the file itself, I realised that for some reasons, when pulling from github, another file is pulled instead of the javascript file that was required.
> 
> What I did to solve my issue was to locate the [corresponding file on github](https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/dribbblish.js) and replaced the one that is in the Extensions. I suggest that @BehdadEs and @vandan-school give this a try to see if this would fix their issue.

**Comment by Adamwgoh** [comment]
@Sparoney You are correct in that the bug is in dribbblish.js, a very simple traceback through the commits with 0 js knowledge and you can guess where the error was merged in. Fixed mine but would prefer author to fix this issue him/herself as this is her repo.

**Comment by ChoogleGrome** [comment]
@khanhas i was able to fix the issue on my end by adding a if statement after `link` is defined.
`
for (let i = 0; i < sidebarItem.length; i++) {
            const item = sidebarItem[i];
            const link = item.getElementsByTagName("a")[0];
            if (link === undefined) { continue }
            const href = link.href.replace("app:", "");

            if (href.indexOf("playlist-folder") != -1) {
                const button = item.getElementsByTagName("button")[0]
                button.classList.add("Button", "Button--style-icon-background", "Button--size-28",);
                item.setAttribute("data-tooltip", item.innerText);
                link.firstChild.innerText = item.innerText.slice(0, 3);
                continue;
            }

            Spicetify.CosmosAPI.resolver.get({
                url: `sp://core-playlist/v1/playlist/${href}/metadata`,
                body: { policy: { picture: true } },
            }, (err, res) => {
                if (err) return;
                const meta = res.getJSONBody().metadata;
                item.firstChild.className = "playlist-picture"
                item.firstChild.style.backgroundImage = `url(${meta.picture})`;
                item.firstChild.setAttribute("data-tooltip", item.textContent);
            });
        }
`

**Comment by vandan-school** [comment]
@ChoogleGrome What exactly did you do? Because I have the exact same thing as you showed in the screenshot.

**Comment by khanhas** [comment]
@ChoogleGrome Thanks for the fix. I don't know how that case would ever happen but if it works on yours, maybe it would work for others.

`dribbblish.js` update was pused. If you have this problem, please `git pull` or download newest theme package to update.

**Comment by ChoogleGrome** [comment]
> @ChoogleGrome What exactly did you do? Because I have the exact same thing as you showed in the screenshot.

I added a if statement after `link` was defined in dribbblish.js. I saw in the console that the `link` variable was coming up undefined, so I basically just skipped one iteration of the loop if it was undefined and it seemed to work. @vandan-school

**Comment by khanhas** [comment]
That makes sense. Thanks again.
